from selenium.webdriver.common.by import By


class ObliJobDataPageLocators(object):
    oblijobdata = (By.XPATH, '//*[@id="tabdivisonsid"]/ul/li/a/span[1]/i')
    oblijobdata_filled = (By.XPATH, '//*[@id="tabdivisonsid"]/ul/li/a/span[2]/i')
    oblijobdata_reset = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[1]/ul/li[2]/a')
    oblijobdata_exit = (By.XPATH, '//*[@id="aExistingForm"]')
    oblijobdata_save = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[4]/ul/li[2]/a')
    oblijobdata_cancel = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[4]/ul/li[1]/a')
    save_form = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[4]/ul/li[2]/a')
    save_form_popup = (By.XPATH, '//*[@id="AlmostDoneModal"]/div/div/div/form/div[3]/div/button')
    save_form_close_X = (By.XPATH, '//*[@id="SavedSuccessfullyModel"]/div/div/a')

    # 16JB 16JT 23XL
    M16JB_JT_Default = (By.XPATH, '//*[@id="a"]')
    M16JB_JT_carrier_obli_assemble_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div/div/div[1]/div[3]/ul/li[2]/label/span')
    M16JB_JT_carrier_obli_assemble_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div/div/div[1]/div[3]/ul/li[1]/label/span')
    M16JB_JT_carrier_obli_leak_test_yes =(By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div/div/div[2]/div[3]/ul/li[2]/label/span')
    M16JB_JT_carrier_obli_leak_test_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div/div/div[2]/div[3]/ul/li[1]/label/span')
    M16JB_JT_carrier_obli_dehydrate_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div/div/div[3]/div[3]/ul/li[2]/label/span')
    M16JB_JT_carrier_obli_dehydrate_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div/div/div[3]/div[3]/ul/li[1]/label/span')
    M16JB_JT_carrier_obli_charging_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div/div/div[4]/div[3]/ul/li[2]/label/span')
    M16JB_JT_carrier_obli_charging_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div/div/div[4]/div[3]/ul/li[1]/label/span')
    M16JB_JT_carrier_obli_operating_hrs_05 = 8
    M16JB_JT_carrier_job_install_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[3]/div/div/div/div/div[1]/div[3]/ul/li[2]/label/span')
    M16JB_JT_carrier_job_install_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[3]/div/div/div/div/div[1]/div[3]/ul/li[1]/label/span')
    M16JB_JT_carrier_job_assemble_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[3]/div/div/div/div/div[2]/div[3]/ul/li[2]/label/span')
    M16JB_JT_carrier_job_assemble_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[3]/div/div/div/div/div[2]/div[3]/ul/li[1]/label/span')
    M16JB_JT_carrier_job_details_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[3]/div/div/div/div/div[3]/div[3]/ul/li[2]/label/span')
    M16JB_JT_carrier_job_details_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[3]/div/div/div/div/div[3]/div[3]/ul/li[1]/label/span')
    M16JB_JT_carrier_job_design_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[3]/div/div/div/div/div[4]/div[3]/ul/li[2]/label/span')
    M16JB_JT_carrier_job_design_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[3]/div/div/div/div/div[4]/div[3]/ul/li[1]/label/span')
    M16JB_JT_carrier_job_diags_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[3]/div/div/div/div/div[5]/div[3]/ul/li[2]/label/span')
    M16JB_JT_carrier_job_diags_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[3]/div/div/div/div/div[5]/div[3]/ul/li[1]/label/span')
    # 19PICC6, 19XL, 19XRD, 19XRE, 19XRPIC5, 19XRV, 23XRV, 17DA, 32XR, 19XR
    M32XR_Default = (By.XPATH, '//*[@id="a"]')
    M32XR_carrier_obli_assemble_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[3]/div[2]/div/div/div/div[2]/div/div/div/div/div[1]/div[3]/ul/li[2]/label/span')
    M32XR_carrier_obli_assemble_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[3]/div[2]/div/div/div/div[2]/div/div/div/div/div[1]/div[3]/ul/li[1]/label/span')
    M32XR_carrier_obli_leak_test_yes =(By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[3]/div[2]/div/div/div/div[2]/div/div/div/div/div[2]/div[3]/ul/li[2]/label/span')
    M32XR_carrier_obli_leak_test_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[3]/div[2]/div/div/div/div[2]/div/div/div/div/div[2]/div[3]/ul/li[1]/label/span')
    M32XR_carrier_obli_dehydrate_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[3]/div[2]/div/div/div/div[2]/div/div/div/div/div[3]/div[3]/ul/li[2]/label/span')
    M32XR_carrier_obli_dehydrate_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[3]/div[2]/div/div/div/div[2]/div/div/div/div/div[3]/div[3]/ul/li[1]/label/span')
    M32XR_carrier_obli_charging_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[3]/div[2]/div/div/div/div[2]/div/div/div/div/div[4]/div[3]/ul/li[2]/label/span')
    M32XR_carrier_obli_charging_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[3]/div[2]/div/div/div/div[2]/div/div/div/div/div[4]/div[3]/ul/li[1]/label/span')
    M32XR_carrier_obli_operating_hrs_05 = 8
    M32XR_carrier_job_install_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[3]/div[2]/div/div/div/div[3]/div/div/div/div/div[1]/div[3]/ul/li[2]/label/span')
    M32XR_carrier_job_install_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[3]/div[2]/div/div/div/div[3]/div/div/div/div/div[1]/div[3]/ul/li[1]/label/span')
    M32XR_carrier_job_assemble_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[3]/div[2]/div/div/div/div[3]/div/div/div/div/div[2]/div[3]/ul/li[2]/label/span')
    M32XR_carrier_job_assemble_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[3]/div[2]/div/div/div/div[3]/div/div/div/div/div[2]/div[3]/ul/li[1]/label/span')
    M32XR_carrier_job_details_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[3]/div[2]/div/div/div/div[3]/div/div/div/div/div[3]/div[3]/ul/li[2]/label/span')
    M32XR_carrier_job_details_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[3]/div[2]/div/div/div/div[3]/div/div/div/div/div[3]/div[3]/ul/li[1]/label/span')
    M32XR_carrier_job_design_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[3]/div[2]/div/div/div/div[3]/div/div/div/div/div[4]/div[3]/ul/li[2]/label/span')
    M32XR_carrier_job_design_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[3]/div[2]/div/div/div/div[3]/div/div/div/div/div[4]/div[3]/ul/li[1]/label/span')
    M32XR_carrier_job_diags_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[3]/div[2]/div/div/div/div[3]/div/div/div/div/div[5]/div[3]/ul/li[2]/label/span')
    M32XR_carrier_job_diags_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[3]/div[2]/div/div/div/div[3]/div/div/div/div/div[5]/div[3]/ul/li[1]/label/span')
