from selenium.webdriver.common.by import By


class ReflogPageLocators(object):
    form_title = (By.XPATH,'//*[@id="content"]/div[1]/div[2]/ng-include[3]/div[1]/div[1]/div[1]/div[1]/h1[1]')
    add_log_btn = (By.XPATH,'//*[@id="content"]/div[1]/div[2]/ng-include[3]/div[1]/div[1]/div[1]/div[2]/div[1]/div['
                             '3]/div[1]/div[1]/button[1]')
    form_plant_lbl = (By.XPATH, '//*[@id="content"]/div[1]/div[2]/ng-include[3]/div[1]/div[1]/div[1]/div[1]/div[1]/p[1]/span[1]')
    form_plant_val= (By.XPATH,'//*[@id="content"]/div[1]/div[2]/ng-include[3]/div[1]/div[1]/div[1]/div[1]/div[1]/p[1]/input[1]')
    form_refrigerant_lbl = (By.XPATH,'//*[@id="content"]/div[1]/div[2]/ng-include[3]/div[1]/div[1]/div[1]/div[1]/div[1]/p[1]/span[1]')
    form_refrigerant_val = (By.XPATH, '//*[@id="content"]/div[1]/div[2]/ng-include[3]/div[1]/div[1]/div[1]/div[1]/div[1]/p[1]/input[1]')
    edit_log = (By.XPATH,'//*[@id="content"]/div[1]/div[2]/ng-include[3]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[4]/ul[1]/li[1]/a[1]/i[1]')
    del_log = (By.XPATH,'//*[@id="content"]/div[1]/div[2]/ng-include[3]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[4]')
    form_cancel = (By.XPATH,'//*[@id="content"]/div[1]/div[2]/ng-include[3]/div[1]/div[1]/div[1]/ul[1]/li[1]/a[1]')
    form_save = (By.XPATH,'//*[@id="content"]/div[1]/div[2]/ng-include[3]/div[1]/div[1]/div[1]/ul[1]/li[2]/a[1]')
    form_exit = (By.XPATH,'//*[@id="content"]/div[1]/div[2]/ng-include[3]/div[1]/div[1]/div[1]/div[1]/ul[1]/li[1]/a')
    log_exit = (By.XPATH,'//*[@id="aExistingForm"]')
    log_save = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/ul/li[2]/a')
    log_cancel = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/ul/li[1]/a')
    log_reset = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[1]/ul/li[2]')
    M16JB_Default =(By.XPATH,'//*[@id="output"]')
    M16JB_EVAP_OPER_HRS_Desc = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div['
                                    '2]/div[2]/form/div/div[1]/div[1]/div/div/div[1]/label/span')
    M16JB_EVAP_OPER_HRS_Val = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[1]/div[1]/div/div/div[1]/div/input')
    M16JB_EVAP_EWT_Desc= (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[1]/div[1]/div/div/div[2]/label/span')
    M16JB_EVAP_EWT_Val= (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[1]/div[1]/div/div/div[2]/div/input')
    M16JB_EVAP_LWT_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[1]/div[1]/div/div/div[3]/label/span')
    M16JB_EVAP_LWT_Val= (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[1]/div[1]/div/div/div[3]/div/input')
    M16JB_EVAP_RefTemp_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[1]/div[1]/div/div/div[4]/label/span')
    M16JB_EVAP_RefTemp_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[1]/div[1]/div/div/div[4]/div/input')
    M16JB_EVAP_Refpump_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[1]/div[1]/div/div/div[5]/label/span')
    M16JB_EVAP_Refpump_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[1]/div[1]/div/div/div[5]/div/input')

    M16JB_EVAP_SpGrRef_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div['
                                      '2]/form/div/div[1]/div[1]/div/div/div[6]/label/span')
    M16JB_EVAP_SpGrRef_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div['
                                     '2]/form/div/div[1]/div[1]/div/div/div[6]/div/input')
    M16JB_EVAP_CycGrdValv_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div['
                                         '2]/div[2]/form/div/div[1]/div[1]/div/div/div[7]/label/span')
    M16JB_EVAP_CycGrdValv_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[1]/div[1]/div/div/div[7]/div/input')
    M16JB_EVAP_CHWPD_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[1]/div[1]/div/div/div[8]/label/span')
    M16JB_EVAP_CHWPD_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[1]/div[1]/div/div/div[8]/div/input')
    M16JB_EVAP_RefrLvlSen_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[1]/div[1]/div/div/div[9]/label/span')
    M16JB_EVAP_RefrLvlSen_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[1]/div[1]/div/div/div[9]/div/input')
    M16JB_EVAP_Usr1_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[1]/div[1]/div/div/div[10]/label/span')
    M16JB_EVAP_Usr1_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[1]/div[1]/div/div/div[10]/div/input')
    M16JB_EVAP_Usr2_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[1]/div[1]/div/div/div[11]/label/span')
    M16JB_EVAP_Usr2_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[1]/div[1]/div/div/div[11]/div/input')
    M16JB_ABSORB_CWInTemp_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[2]/div[1]/div/div/div[1]/label/span')
    M16JB_ABSORB_CWInTemp_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[2]/div[1]/div/div/div[1]/div/input')
    M16JB_ABSORB_CWOutTemp_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[2]/div[1]/div/div/div[2]/label/span')
    M16JB_ABSORB_CWOutTemp_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[2]/div[1]/div/div/div[2]/div/input')
    M16JB_ABSORB_WkLvAbsTemp_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[2]/div[1]/div/div/div[3]/label/span')
    M16JB_ABSORB_WkLvAbsTemp_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[2]/div[1]/div/div/div[3]/div/input')
    M16JB_ABSORB_WkLvAbsSampTemp_Desc = (By.XPATH,
                                     '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div['
                                     '2]/form/div/div[2]/div[1]/div/div/div[4]/label/span')
    M16JB_ABSORB_WkLvAbsSampTemp_Val = (By.XPATH,
                                    '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div['
                                    '2]/form/div/div[2]/div[1]/div/div/div[4]/div/input')

    M16JB_ABSORB_SpGrWkLvAbsSamp_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include['
                                                '1]/div/div/div[2]/div[2]/form/div/div[2]/div[1]/div/div/div[5]/label/span')
    M16JB_ABSORB_SpGrWkLvAbsSamp_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include['
                                               '1]/div/div/div[2]/div[2]/form/div/div[2]/div[1]/div/div/div[5]/div/input')
    M16JB_ABSORB_WkLvAbsHiHX2Temp_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include['
                                                 '1]/div/div/div[2]/div[2]/form/div/div[2]/div[1]/div/div/div[6]/label/span')
    M16JB_ABSORB_WkLvAbsHiHX2Temp_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include['
                                                '1]/div/div/div[2]/div[2]/form/div/div[2]/div[1]/div/div/div[6]/div/input')
    M16JB_ABSORB_WkLvAbsHiHXTemp_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include['
                                                '1]/div/div/div[2]/div[2]/form/div/div[2]/div[1]/div/div/div[7]/label/span')
    M16JB_ABSORB_WkLvAbsHiHXTemp_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include['
                                               '1]/div/div/div[2]/div[2]/form/div/div[2]/div[1]/div/div/div[7]/div/input')
    M16JB_ABSORB_WkLvAbsHiHX1Temp_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include['
                                                 '1]/div/div/div[2]/div[2]/form/div/div[2]/div[1]/div/div/div[8]/label/span')
    M16JB_ABSORB_WkLvAbsHiHX1Temp_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include['
                                                '1]/div/div/div[2]/div[2]/form/div/div[2]/div[1]/div/div/div[8]/div/input')
    M16JB_ABSORB_SolsprTemp_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div['
                                           '2]/div[2]/form/div/div[2]/div[1]/div/div/div[9]/label/span')
    M16JB_ABSORB_SolsprTemp_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div['
                                          '2]/div[2]/form/div/div[2]/div[1]/div/div/div[9]/div/input')
    M16JB_ABSORB_CoolWPD_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div['
                                        '2]/div[2]/form/div/div[2]/div[1]/div/div/div[10]/label/span')
    M16JB_ABSORB_CoolWPD_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div['
                                       '2]/form/div/div[2]/div[1]/div/div/div[10]/div/input')
    M16JB_ABSORB_PmpPres_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div['
                                        '2]/div[2]/form/div/div[2]/div[1]/div/div/div[11]/label/span')
    M16JB_ABSORB_PmpPres_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div['
                                       '2]/form/div/div[2]/div[1]/div/div/div[11]/div/input')
    M16JB_ABSORB_SollvlLCD_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div['
                                          '2]/div[2]/form/div/div[2]/div[1]/div/div/div[12]/label/span')
    M16JB_ABSORB_SollvlLCD_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div['
                                         '2]/div[2]/form/div/div[2]/div[1]/div/div/div[12]/div/input')
    M16JB_COND_LWT_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[3]/div[1]/div/div/div[1]/label/span')
    M16JB_COND_LWT_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[3]/div[1]/div/div/div[1]/div/input')
    M16JB_COND_VapCondTemp_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[3]/div[1]/div/div/div[2]/label/span')
    M16JB_COND_VapCondTemp_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[3]/div[1]/div/div/div[2]/div/input')
    M16JB_COND_CWPD_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[3]/div[1]/div/div/div[3]/label/span')
    M16JB_COND_CWPD_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[3]/div[1]/div/div/div[3]/div/input')
    M16JB_COND_Usr3_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[3]/div[1]/div/div/div[4]/label/span')
    M16JB_COND_Usr3_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[3]/div[1]/div/div/div[4]/div/input')
    M16JB_GEN_StrLG1Temp_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[4]/div[1]/div/div/div[1]/label/span')
    M16JB_GEN_StrLG1Temp_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[4]/div[1]/div/div/div[1]/div/input')
    M16JB_GEN_StrLHX1_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[4]/div[1]/div/div/div[2]/label/span')
    M16JB_GEN_StrLHX1_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[4]/div[1]/div/div/div[2]/div/input')
    M16JB_GEN_StrLG2Temp_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[4]/div[1]/div/div/div[3]/label/span')
    M16JB_GEN_StrLG2Temp_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[4]/div[1]/div/div/div[3]/div/input')
    M16JB_GEN_StrLHX2_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[4]/div[1]/div/div/div[4]/label/span')
    M16JB_GEN_StrLHX2_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[4]/div[1]/div/div/div[4]/div/input')
    M16JB_GEN_CondTempG2_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[4]/div[1]/div/div/div[5]/label/span')
    M16JB_GEN_CondTempG2_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[4]/div[1]/div/div/div[5]/div/input')
    M16JB_GEN_G1IntPres_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[4]/div[1]/div/div/div[6]/label/span')
    M16JB_GEN_G1IntPres_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[4]/div[1]/div/div/div[6]/div/input')
    M16JB_GEN_StrmPresSupl_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[4]/div[1]/div/div/div[7]/label/span')
    M16JB_GEN_StrmPresSupl_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[4]/div[1]/div/div/div[7]/div/input')
    M16JB_GEN_StrmPresChil_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[4]/div[1]/div/div/div[8]/label/span')
    M16JB_GEN_StrmPresChil_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[4]/div[1]/div/div/div[8]/div/input')
    M16JB_GEN_CapValvPerc_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[4]/div[1]/div/div/div[9]/label/span')
    M16JB_GEN_CapValvPerc_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[4]/div[1]/div/div/div[9]/div/input')

    M16JB_ADD_DATA_WkConc_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[5]/div[1]/div/div/div[1]/label/span')
    M16JB_ADD_DATA_WkConc_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[5]/div[1]/div/div/div[1]/div/input')
    M16JB_ADD_DATA_WkSatTemp_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[5]/div[1]/div/div/div[2]/label/span')
    M16JB_ADD_DATA_WkSatTemp_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[5]/div[1]/div/div/div[2]/div/input')
    M16JB_ADD_DATA_StrConcG1_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[5]/div[1]/div/div/div[3]/label/span')
    M16JB_ADD_DATA_StrConcG1_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[5]/div[1]/div/div/div[3]/div/input')
    M16JB_ADD_DATA_StrConcG2_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[5]/div[1]/div/div/div[4]/label/span')
    M16JB_ADD_DATA_StrConcG2_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[5]/div[1]/div/div/div[4]/div/input')
    M16JB_ADD_DATA_AbsLos_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[5]/div[1]/div/div/div[5]/label/span')
    M16JB_ADD_DATA_AbsLos_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[5]/div[1]/div/div/div[5]/div/input')
    M16JB_ADD_DATA_EvapAproch_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[5]/div[1]/div/div/div[6]/label/span')
    M16JB_ADD_DATA_EvapAproch_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[5]/div[1]/div/div/div[6]/div/input')
    M16JB_ADD_DATA_AbsAproch_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[5]/div[1]/div/div/div[7]/label/span')
    M16JB_ADD_DATA_AbsAproch_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[5]/div[1]/div/div/div[7]/div/input')
    M16JB_ADD_DATA_CondAproch_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[5]/div[1]/div/div/div[8]/label/span')
    M16JB_ADD_DATA_CondAproch_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[5]/div[1]/div/div/div[8]/div/input')
    #17DA,17EX,19EX,19DV,19XL,19XR***
    M17DA_Cooler_Pres_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[1]/div[1]/div[1]/div/div[1]/label/span')
    M17DA_Cooler_Pres_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[1]/div[1]/div[1]/div/div[1]/div/input')
    M17DA_Cooler_Temp_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[1]/div[1]/div[1]/div/div[2]/label/span')
    M17DA_Cooler_Temp_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div['
                                    '2]/form/div/div[1]/div[1]/div[1]/div/div[2]/div/input')
    M17DA_Cooler_ShutLvl_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[1]/div[1]/div[1]/div/div[3]/label/span')
    M17DA_Cooler_ShutLvl_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div['
                                       '2]/form/div/div[1]/div[1]/div[1]/div/div[3]/div/input')
    M17DA_Cooler_BrineTempIn_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[1]/div[2]/div[2]/div/div/div/div[1]/label')
    M17DA_Cooler_BrineTempIn_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[1]/div[2]/div[2]/div/div/div/div[1]/input')
    M17DA_Cooler_BrineTempOut_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[1]/div[2]/div[2]/div/div/div/div[2]/label')
    M17DA_Cooler_BrineTempOut_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[1]/div[2]/div[2]/div/div/div/div[2]/input')
    M17DA_Condenser_Pres_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[2]/div[1]/div[1]/div/div[1]/label/span')
    M17DA_Condenser_Pres_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[2]/div[1]/div[1]/div/div[1]/div/input')
    M17DA_Condenser_Temp_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[2]/div[1]/div[1]/div/div[2]/label/span')
    M17DA_Condenser_Temp_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div['
                                       '2]/form/div/div[2]/div[1]/div[1]/div/div[2]/div/input')
    M17DA_Condenser_WaterTempIn_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[2]/div[2]/div[2]/div/div/div/div[1]/label')
    M17DA_Condenser_WaterTempIn_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[2]/div[2]/div[2]/div/div/div/div[1]/input')
    M17DA_Condenser_WaterTempOut_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[2]/div[2]/div[2]/div/div/div/div[2]/label')
    M17DA_Condenser_WaterTempOut_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[2]/div[2]/div[2]/div/div/div/div[2]/input')
    M17DA_Default = (By.XPATH, '//*[@id="output"]')
    M17DA_Compressor_DampPos_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[3]/div[1]/div[1]/h3')
    M17DA_Compressor_DampPos_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[3]/div[1]/div[1]/div/div/div/input')
    M17DA_Compressor_OilPresSuply_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div[1]/div[1]/label')
    M17DA_Compressor_OilPresSuply_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div[1]/div[1]/input')
    M17DA_Compressor_OilPressealHous_Desc=(By.XPATH,'//*[@id="content"]/div[1]/div[2]/check-list[2]/ng-include[1]/div[1]/div[1]/div[2]/div[2]/form[1]/div[1]/div[3]/div[2]/div[2]/div[1]/div[1]/div[1]/div[2]/label[1]')
    M17DA_Compressor_OilPressealHous_Val=(By.XPATH,'//*[@id="content"]/div[1]/div[2]/check-list[2]/ng-include[1]/div[1]/div[1]/div[2]/div[2]/form[1]/div[1]/div[3]/div[2]/div[2]/div[1]/div[1]/div[1]/div[2]/input')
    M17DA_Compressor_OilTempResv_Desc=(By.XPATH,'//*[@id="content"]/div[1]/div[2]/check-list[2]/ng-include[1]/div[1]/div[1]/div[2]/div[2]/form[1]/div[1]/div[3]/div[2]/div[2]/div[1]/div[1]/div[2]/div[1]/label[1]')
    M17DA_Compressor_OilTempResv_Val=(By.XPATH,'//*[@id="content"]/div[1]/div[2]/check-list[2]/ng-include[1]/div[1]/div[1]/div[2]/div[2]/form[1]/div[1]/div[3]/div[2]/div[2]/div[1]/div[1]/div[2]/div[1]/input')
    M17DA_Compressor_OilTemplvl_Desc=(By.XPATH,'//*[@id="content"]/div[1]/div[2]/check-list[2]/ng-include[1]/div[1]/div[1]/div[2]/div[2]/form[1]/div[1]/div[3]/div[2]/div[2]/div[1]/div[1]/div[2]/div[2]/label[1]')
    M17DA_Compressor_OilTemplvl_Val=(By.XPATH,'//*[@id="content"]/div[1]/div[2]/check-list[2]/ng-include[1]/div[1]/div[1]/div[2]/div[2]/form[1]/div[1]/div[3]/div[2]/div[2]/div[1]/div[1]/div[2]/div[2]/input')
    M17DA_Compressor_BearTempThrustEnd_Desc=(By.XPATH,'//*[@id="content"]/div[1]/div[2]/check-list[2]/ng-include[1]/div[1]/div[1]/div[2]/div[2]/form[1]/div[1]/div[3]/div[1]/div[3]/div[1]/div[1]/label[1]/span[1]')
    M17DA_Compressor_BearTempThrustEnd_Val=(By.XPATH,'//*[@id="content"]/div[1]/div[2]/check-list[2]/ng-include[1]/div[1]/div[1]/div[2]/div[2]/form[1]/div[1]/div[3]/div[1]/div[3]/div[1]/div[1]/div/input')
    M17DA_Compressor_BearTempSealEnd_Desc=(By.XPATH,'//*[@id="content"]/div[1]/div[2]/check-list[2]/ng-include[1]/div[1]/div[1]/div[2]/div[2]/form[1]/div[1]/div[3]/div[1]/div[3]/div[1]/div[2]/label[1]/span[1]')
    M17DA_Compressor_BearTempSealEnd_Val=(By.XPATH,'//*[@id="content"]/div[1]/div[2]/check-list[2]/ng-include[1]/div[1]/div[1]/div[2]/div[2]/form[1]/div[1]/div[3]/div[1]/div[3]/div[1]/div[2]/div/input')
    M17DA_Gearoil_Press_Desc= (By.XPATH,'//*[@id="content"]/div[1]/div[2]/check-list[2]/ng-include[1]/div[1]/div[1]/div[2]/div[2]/form[1]/div[1]/div[4]/div[1]/div[1]/div[1]/div[1]/label[1]/span[1]')
    M17DA_Gearoil_Press_Val= (By.XPATH,'//*[@id="content"]/div[1]/div[2]/check-list[2]/ng-include[1]/div[1]/div[1]/div[2]/div[2]/form[1]/div[1]/div[4]/div[1]/div[1]/div[1]/div[1]/div/input')
    M17DA_Gearoil_Temp_Desc= (By.XPATH,'//*[@id="content"]/div[1]/div[2]/check-list[2]/ng-include[1]/div[1]/div[1]/div[2]/div[2]/form[1]/div[1]/div[4]/div[1]/div[1]/div[1]/div[2]/label[1]/span[1')
    M17DA_Gearoil_Temp_Val= (By.XPATH,'//*[@id="content"]/div[1]/div[2]/check-list[2]/ng-include[1]/div[1]/div[1]/div[2]/div[2]/form[1]/div[1]/div[4]/div[1]/div[1]/div[1]/div[2]/div/input')
    M17DA_Prime_A_Desc=(By.XPATH,'//*[@id="content"]/div[1]/div[2]/check-list[2]/ng-include[1]/div[1]/div[1]/div[2]/div[2]/form[1]/div[1]/div[5]/div[1]/div[1]/div[1]/div[1]/label[1]/span[1]')
    M17DA_Prime_A_Val=(By.XPATH,'//*[@id="content"]/div[1]/div[2]/check-list[2]/ng-include[1]/div[1]/div[1]/div[2]/div[2]/form[1]/div[1]/div[5]/div[1]/div[1]/div[1]/div[1]/div/input')
    M17DA_Prime_B_Desc=(By.XPATH,'//*[@id="content"]/div[1]/div[2]/check-list[2]/ng-include[1]/div[1]/div[1]/div[2]/div[2]/form[1]/div[1]/div[5]/div[1]/div[1]/div[1]/div[2]/label[1]/span[1]')
    M17DA_Prime_B_Val=(By.XPATH,'//*[@id="content"]/div[1]/div[2]/check-list[2]/ng-include[1]/div[1]/div[1]/div[2]/div[2]/form[1]/div[1]/div[5]/div[1]/div[1]/div[1]/div[2]/div/input')
    M17DA_Prime_C_Desc=(By.XPATH,'//*[@id="content"]/div[1]/div[2]/check-list[2]/ng-include[1]/div[1]/div[1]/div[2]/div[2]/form[1]/div[1]/div[5]/div[1]/div[1]/div[1]/div[3]/label[1]/span[1]')
    M17DA_Prime_C_Val=(By.XPATH,'//*[@id="content"]/div[1]/div[2]/check-list[2]/ng-include[1]/div[1]/div[1]/div[2]/div[2]/form[1]/div[1]/div[5]/div[1]/div[1]/div[1]/div[3]/div/input')
    M17DA_Prime_D_Desc=(By.XPATH,'//*[@id="content"]/div[1]/div[2]/check-list[2]/ng-include[1]/div[1]/div[1]/div[2]/div[2]/form[1]/div[1]/div[5]/div[1]/div[1]/div[1]/div[4]/label[1]/span[1]')
    M17DA_Prime_D_Val=(By.XPATH,'//*[@id="content"]/div[1]/div[2]/check-list[2]/ng-include[1]/div[1]/div[1]/div[2]/div[2]/form[1]/div[1]/div[5]/div[1]/div[1]/div[1]/div[4]/div/input')

    #19XRD,19EX,19RDE,19XRV,19XRPIC5,23XL,32XR
    M19XR_Default = (By.XPATH, '//*[@id="output"]')
    M19XR_Cooler_Refrig_Press_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[1]/div[1]/div[1]/div/div[1]/label/span')
    M19XR_Cooler_Refrig_Press_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[1]/div[1]/div[1]/div/div[1]/div/input')
    M19XR_Cooler_Refrig_Temp_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[1]/div[1]/div[1]/div/div[2]/label/span')
    M19XR_Cooler_Refrig_Temp_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[1]/div[1]/div[1]/div/div[2]/div/input')
    M19XR_Cooler_Water_PressIn_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[1]/div[2]/div[2]/div/div/div[1]/div[1]/label')
    M19XR_Cooler_Water_PressIn_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[1]/div[2]/div[2]/div/div/div[1]/div[1]/input')
    M19XR_Cooler_Water_PressOut_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include['
                                               '1]/div/div/div[2]/div[2]/form/div/div[1]/div[2]/div[2]/div/div/div[1]/div[2]/label')
    M19XR_Cooler_Water_PressOut_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div['
                                              '2]/div[2]/form/div/div[1]/div[2]/div[2]/div/div/div[1]/div[2]/input')
    M19XR_Cooler_Water_PressGPM_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include['
                                               '1]/div/div/div[2]/div[2]/form/div/div[1]/div[2]/div[2]/div/div/div[1]/div[3]/label')
    M19XR_Cooler_Water_PressGPM_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div['
                                              '2]/div[2]/form/div/div[1]/div[2]/div[2]/div/div/div[1]/div[3]/input')
    M19XR_Cooler_Water_TempIn_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[1]/div[2]/div[2]/div/div/div[2]/div[1]/label')
    M19XR_Cooler_Water_TempIn_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[1]/div[2]/div[2]/div/div/div[2]/div[1]/input')
    M19XR_Cooler_Water_TempOut_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[1]/div[2]/div[2]/div/div/div[2]/div[2]/label')
    M19XR_Cooler_Water_TempOut_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[1]/div[2]/div[2]/div/div/div[2]/div[2]/input')
    M19XR_Cond_Refrig_Press_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[]/div[1]/div[1]/div/div[1]/label/span')
    M19XR_Cond_Refrig_Press_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[2]/div[1]/div[1]/div/div[1]/div/input')
    M19XR_Cond_Refrig_Temp_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[2]/div[1]/div[1]/div/div[2]/label/span')
    M19XR_Cond_Refrig_Temp_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[2]/div[1]/div[1]/div/div[2]/div/input')
    M19XR_Cond_Water_PressIn_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[2]/div[2]/div[2]/div/div/div[1]/div[1]/label')
    M19XR_Cond_Water_PressIn_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[2]/div[2]/div[2]/div/div/div[1]/div[1]/input')
    M19XR_Cond_Water_PressOut_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div['
                                             '2]/div[2]/form/div/div[2]/div[2]/div[2]/div/div/div[1]/div[2]/label')
    M19XR_Cond_Water_PressOut_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div['
                                            '2]/div[2]/form/div/div[2]/div[2]/div[2]/div/div/div[1]/div[2]/input')
    M19XR_Cond_Water_PressGPM_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div['
                                             '2]/div[2]/form/div/div[2]/div[2]/div[2]/div/div/div[1]/div[3]/label')
    M19XR_Cond_Water_PressGPM_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div['
                                            '2]/div[2]/form/div/div[2]/div[2]/div[2]/div/div/div[1]/div[3]/input')
    M19XR_Cond_Water_TempIn_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[2]/div[2]/div[2]/div/div/div[2]/div[1]/label')
    M19XR_Cond_Water_TempIn_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[2]/div[2]/div[2]/div/div/div[2]/div[1]/input')
    M19XR_Cond_Water_TempOut_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[2]/div[2]/div[2]/div/div/div[2]/div[2]/label')
    M19XR_Cond_Water_TempOut_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[2]/div[2]/div[2]/div/div/div[2]/div[2]/input')
    M19XR_Compressor_BearingTemp_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[3]/div[1]/div[1]/h3')
    M19XR_Compressor_BearingTemp_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[3]/div[1]/div[1]/div/div/div/input')
    M19XR_Compressor_OilPressDiff_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[3]/div[1]/div[2]/div/div[1]/label')
    M19XR_Compressor_OilPressDiff_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[3]/div[1]/div[2]/div/div[1]/div/input')
    M19XR_Compressor_OilTempResv_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[3]/div[1]/div[2]/div/div[2]/label')
    M19XR_Compressor_OilTempResv_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[3]/div[1]/div[2]/div/div[2]/div/input')
    M19XR_Compressor_Oillvl_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[3]/div[1]/div[2]/div/div[3]/label')
    M19XR_Compressor_Oillvl_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[3]/div[1]/div[2]/div/div[3]/div/input')
    M19XR_Compressor_Oillvl23_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div['
                                           '2]/div[2]/form/div/div[3]/div[1]/div[' \
    '2]/div/div[4]/div/input')
    M19XR_Compressor_MotorFLA_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[3]/div[2]/div[3]/div/div/div[1]/label/span')
    M19XR_Compressor_MotorFLA_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[3]/div[2]/div[3]/div/div/div[1]/div/input')
    M19XR_Compressor_MotorAmp_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[3]/div[2]/div[3]/div/div/div[2]/label/span')
    M19XR_Compressor_MotorAmp_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[3]/div[2]/div[3]/div/div/div[2]/div/input')


    #23XRV
    M23XRV_Default = (By.XPATH, '//*[@id="output"]')
    M23XRV_Cooler_Refrig_Press_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div['
                                          '2]/div[2]/form/div/div[1]/div[1]/div[1]/div/div[1]/label/span')
    M23XRV_Cooler_Refrig_Press_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[1]/div[1]/div[1]/div/div[1]/div/input')
    M23XRV_Cooler_Refrig_Temp_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[1]/div[1]/div[1]/div/div[2]/label/span')
    M23XRV_Cooler_Refrig_Temp_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[1]/div[1]/div[1]/div/div[2]/div/input')
    M23XRV_Cooler_Water_PressIn_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[1]/div[2]/div[2]/div/div/div[1]/div[1]/label')
    M23XRV_Cooler_Water_PressIn_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[1]/div[2]/div[2]/div/div/div[1]/div[1]/input')
    M23XRV_Cooler_Water_PressOut_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include['
                                                '1]/div/div/div[2]/div[2]/form/div/div[1]/div[2]/div[2]/div/div/div[1]/div[2]/label')
    M23XRV_Cooler_Water_PressOut_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include['
                                               '1]/div/div/div[2]/div[2]/form/div/div[1]/div[2]/div[2]/div/div/div[1]/div[2]/input')
    M23XRV_Cooler_Water_PressGPM_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include['
                                                '1]/div/div/div[2]/div[2]/form/div/div[1]/div[2]/div[2]/div/div/div[1]/div[3]/label')
    M23XRV_Cooler_Water_PressGPM_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include['
                                               '1]/div/div/div[2]/div[2]/form/div/div[1]/div[2]/div[2]/div/div/div['
                                               '1]/div[3]/input')
    M23XRV_Cooler_Water_TempIn_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[1]/div[2]/div[2]/div/div/div[2]/div[1]/label')
    M23XRV_Cooler_Water_TempIn_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[1]/div[2]/div[2]/div/div/div[2]/div[1]/input')
    M23XRV_Cooler_Water_TempOut_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[1]/div[2]/div[2]/div/div/div[2]/div[2]/label')
    M23XRV_Cooler_Water_TempOut_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[1]/div[2]/div[2]/div/div/div[2]/div[2]/input')
    M23XRV_Cond_Refrig_Press_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[]/div[1]/div[1]/div/div[1]/label/span')
    M23XRV_Cond_Refrig_Press_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[2]/div[1]/div[1]/div/div[1]/div/input')
    M23XRV_Cond_Refrig_Temp_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[2]/div[1]/div[1]/div/div[2]/label/span')
    M23XRV_Cond_Refrig_Temp_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[2]/div[1]/div[1]/div/div[2]/div/input')
    M23XRV_Cond_Water_PressIn_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[2]/div[2]/div[2]/div/div/div[1]/div[1]/label')
    M23XRV_Cond_Water_PressIn_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[2]/div[2]/div[2]/div/div/div[1]/div[1]/input')
    M23XRV_Cond_Water_PressOut_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div['
                                              '2]/div[2]/form/div/div[2]/div[2]/div[2]/div/div/div[1]/div[2]/label')
    M23XRV_Cond_Water_PressOut_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div['
                                             '2]/div[2]/form/div/div[2]/div[2]/div[2]/div/div/div[1]/div[2]/input')
    M23XRV_Cond_Water_PressGPM_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div['
                                              '2]/div[2]/form/div/div[2]/div[2]/div[2]/div/div/div[1]/div[3]/label')
    M23XRV_Cond_Water_PressGPM_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div['
                                             '2]/div[2]/form/div/div[2]/div[2]/div[2]/div/div/div[1]/div[3]/input')
    M23XRV_Cond_Water_TempIn_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[2]/div[2]/div[2]/div/div/div[2]/div[1]/label')
    M23XRV_Cond_Water_TempIn_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[2]/div[2]/div[2]/div/div/div[2]/div[1]/input')
    M23XRV_Cond_Water_TempOut_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[2]/div[2]/div[2]/div/div/div[2]/div[2]/label')
    M23XRV_Cond_Water_TempOut_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[2]/div[2]/div[2]/div/div/div[2]/div[2]/input')
    M23XRV_Concen_ReclaimDelta_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[3]/div[1]/div/div/div[1]/label/span')
    M23XRV_Concen_ReclaimDelta_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[3]/div[1]/div/div/div[1]/div/input')
    M23XRV_Concen_OilReclaimOP_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[3]/div[1]/div/div/div[2]/label/span')
    M23XRV_Concen_OilReclaimOP_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[3]/div[1]/div/div/div[2]/div/input')
    M23XRV_Concen_Oillvl_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[3]/div[1]/div/div/div[3]/label/span')
    M23XRV_Concen_Oillvl_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[3]/div[1]/div/div/div[3]/div/input')
    M23XRV_Compressor_ReoilPresDeltaP_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[4]/div[1]/div/div/div[1]/label/span')
    M23XRV_Compressor_ReoilPresDeltaP_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[4]/div[1]/div/div/div[1]/div/input')
    M23XRV_Compressor_oilsumpTemp_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[4]/div[1]/div/div/div[2]/label/span')
    M23XRV_Compressor_oilsumpTemp_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[4]/div[1]/div/div/div[2]/div/input')
    M23XRV_Compressor_CompDischTemp_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[4]/div[1]/div/div/div[3]/label/span')
    M23XRV_Compressor_CompDischTemp_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[4]/div[1]/div/div/div[3]/div/input')
    M23XRV_VFD_avgCurrent_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[5]/div[1]/div/div/div[1]/label/span')
    M23XRV_VFD_avgCurrent_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[5]/div[1]/div/div/div[1]/div/input')
    M23XRV_VFD_avgVolt_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[5]/div[1]/div/div/div[2]/label/span')
    M23XRV_VFD_avgVolt_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[5]/div[1]/div/div/div[2]/div/input')
    M23XRV_VFD_lineKW_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[5]/div[1]/div/div/div[3]/label/span')
    M23XRV_VFD_lineKW_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[5]/div[1]/div/div/div[3]/div/input')
    M23XRV_VFD_avgLoadCurrent_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[5]/div[1]/div/div/div[4]/label/span')
    M23XRV_VFD_avgLoadCurrent_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[5]/div[1]/div/div/div[4]/div/input')
    M23XRV_VFD_InvTemp_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[5]/div[1]/div/div/div[5]/label/span')
    M23XRV_VFD_InvTemp_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[5]/div[1]/div/div/div[5]/div/input')
    M23XRV_VFD_RectifTemp_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[5]/div[1]/div/div/div[6]/label/span')
    M23XRV_VFD_RectifTemp_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[5]/div[1]/div/div/div[6]/div/input')
    M23XRV_VFD_CoolantFlw_Desc=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[5]/div[1]/div/div/div[7]/label/span')
    M23XRV_VFD_CoolantFlw_Val=(By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[5]/div[1]/div/div/div[7]/div/input')

    #30HX,30MP,30RAP,30RB,30XAXW,30XV,30XA
    M30HX_Default = (By.XPATH, '//*[@id="output"]')
    M30HX_CirA_btn = (By.XPATH,'//*[@id="myAccordion"]/div[1]/div[1]/h4[1]/a')
    M30HX_CirB_btn = (By.XPATH,'//*[@id="myAccordion"]/div[2]/div[1]/h4[1]/a')
    M30HX_CirC_btn = (By.XPATH,'//*[@id="myAccordion"]/div[3]/div[1]/h4[1]/a')
    M30HX_CirA_OperHrs_Desc = (By.XPATH,'//*[@id="collapsible-1"]/div[1]/div[1]/div/div/div[1]/label/span')
    M30HX_CirA_OperHrs_Val = (By.XPATH,'//*[@id="collapsible-1"]/div[1]/div[1]/div/div/div[1]/div/input')
    M30HX_CirA_Starts_Desc = (By.XPATH,'//*[@id="collapsible-1"]/div[1]/div[1]/div/div/div[2]/label/span')
    M30HX_CirA_Starts_Val = (By.XPATH,'//*[@id="collapsible-1"]/div[1]/div[1]/div/div/div[2]/div/input')
    M30HX_CirA_Capacity_Desc = (By.XPATH,'//*[@id="collapsible-1"]/div[1]/div[1]/div/div/div[3]/label/span')
    M30HX_CirA_Capacity_Val = (By.XPATH,'//*[@id="collapsible-1"]/div[1]/div[1]/div/div/div[3]/div/input')
    M30HX_CirA_DischargePres_Desc = (By.XPATH,'//*[@id="collapsible-1"]/div[1]/div[1]/div/div/div[4]/label/span')
    M30HX_CirA_DischargePres_Val = (By.XPATH,'//*[@id="collapsible-1"]/div[1]/div[1]/div/div/div[4]/div/input')
    M30HX_CirA_SatCondTemp_Desc = (By.XPATH,'//*[@id="collapsible-1"]/div[1]/div[1]/div/div/div[5]/label/span')
    M30HX_CirA_SatCondTemp_Val = (By.XPATH,'//*[@id="collapsible-1"]/div[1]/div[1]/div/div/div[5]/div/input')
    M30HX_CirA_SuctTemp_Desc = (By.XPATH,'//*[@id="collapsible-1"]/div[1]/div[1]/div/div/div[6]/label/span')
    M30HX_CirA_SuctTemp_Val = (By.XPATH,'//*[@id="collapsible-1"]/div[1]/div[1]/div/div/div[6]/div/input')
    M30HX_CirA_SuperHeat_Desc = (By.XPATH,'//*[@id="collapsible-1"]/div[1]/div[1]/div/div/div[7]/label/span')
    M30HX_CirA_SuperHeat_Val = (By.XPATH,'//*[@id="collapsible-1"]/div[1]/div[1]/div/div/div[7]/div/input')
    M30HX_CirA_ChwDeltaP_Desc = (By.XPATH,'//*[@id="collapsible-1"]/div[1]/div[1]/div/div/div[8]/label/span')
    M30HX_CirA_ChwDeltaP_Val = (By.XPATH,'//*[@id="collapsible-1"]/div[1]/div[1]/div/div/div[8]/div/input')
    M30HX_CirA_Sst_Desc = (By.XPATH,'//*[@id="collapsible-1"]/div[1]/div[1]/div/div/div[9]/label/span')
    M30HX_CirA_Sst_Val = (By.XPATH,'//*[@id="collapsible-1"]/div[1]/div[1]/div/div/div[9]/div/input')
    M30HX_CirA_OilPress_Desc = (By.XPATH,'//*[@id="collapsible-1"]/div[1]/div[1]/div/div/div[10]/label/span')
    M30HX_CirA_OilPress_Val = (By.XPATH,'//*[@id="collapsible-1"]/div[1]/div[1]/div/div/div[10]/div/input')
    M30HX_CirA_EXV_Desc = (By.XPATH,'//*[@id="collapsible-1"]/div[1]/div[1]/div/div/div[11]/label/span')
    M30HX_CirA_EXV_Val = (By.XPATH,'//*[@id="collapsible-1"]/div[1]/div[1]/div/div/div[11]/div/input')
    M30HX_CirA_WaterIn_Desc = (By.XPATH,'//*[@id="collapsible-1"]/div[1]/div[1]/div/div/div[12]/label/span')
    M30HX_CirA_WaterIn_Val = (By.XPATH,'//*[@id="collapsible-1"]/div[1]/div[1]/div/div/div[12]/div/input')
    M30HX_CirA_WaterOut_Desc = (By.XPATH,'//*[@id="collapsible-1"]/div[1]/div[1]/div/div/div[13]/label/span')
    M30HX_CirA_WaterOut_Val = (By.XPATH,'//*[@id="collapsible-1"]/div[1]/div[1]/div/div/div[13]/div/input')
    M30HX_CirA_EconPress_Desc = (By.XPATH,'//*[@id="collapsible-1"]/div[1]/div[1]/div/div/div[14]/label/span')
    M30HX_CirA_EconPress_Val = (By.XPATH,'//*[@id="collapsible-1"]/div[1]/div[1]/div/div/div[14]/div/input')
    M30HX_CirA_IntFD_Desc = (By.XPATH,'//*[@id="collapsible-1"]/div[1]/div[1]/div/div/div[15]/label/span')
    M30HX_CirA_IntFD_Val = (By.XPATH,'//*[@id="collapsible-1"]/div[1]/div[1]/div/div/div[15]/div/input')
    M30HX_CirA_SGT_Desc = (By.XPATH,'//*[@id="collapsible-1"]/div[1]/div[1]/div/div/div[16]/label/span')
    M30HX_CirA_SGT_Val = (By.XPATH,'//*[@id="collapsible-1"]/div[1]/div[1]/div/div/div[16]/div/input')
    M30HX_CirA_Usr1_Desc = (By.XPATH,'//*[@id="collapsible-1"]/div[1]/div[1]/div/div/div[17]/label/span')
    M30HX_CirA_Usr1_val = (By.XPATH,'//*[@id="collapsible-1"]/div[1]/div[1]/div/div/div[17]/div/input')
    M30HX_CirA_Usr2_Desc = (By.XPATH,'//*[@id="collapsible-1"]/div[1]/div[1]/div/div/div[18]/label/span')
    M30HX_CirA_Usr2_val = (By.XPATH,'//*[@id="collapsible-1"]/div[1]/div[1]/div/div/div[18]/div/input')
    M30HX_CirA_Usr3_Desc = (By.XPATH,'//*[@id="collapsible-1"]/div[1]/div[1]/div/div/div[19]/label/span')
    M30HX_CirA_Usr3_val = (By.XPATH,'//*[@id="collapsible-1"]/div[1]/div[1]/div/div/div[19]/div/input')
    M30HX_CirA_Usr4_Desc = (By.XPATH,'//*[@id="collapsible-1"]/div[1]/div[1]/div/div/div[20]/label/span')
    M30HX_CirA_Usr4_val = (By.XPATH,'//*[@id="collapsible-1"]/div[1]/div[1]/div/div/div[20]/div/input')
    M30HX_CirA_Comp1MotorAmpL1_Desc = (By.XPATH,'//*[@id="collapsible-1"]/div[2]/div[1]/div/div/div[1]/label/span')
    M30HX_CirA_Comp1MotorAmpL1_Val = (By.XPATH,'//*[@id="collapsible-1"]/div[2]/div[1]/div/div/div[1]/div/input')
    M30HX_CirA_Comp1MotorAmpL2_Desc = (By.XPATH,'//*[@id="collapsible-1"]/div[2]/div[1]/div/div/div[2]/label/span')
    M30HX_CirA_Comp1MotorAmpL2_Val = (By.XPATH,'//*[@id="collapsible-1"]/div[2]/div[1]/div/div/div[2]/div/input')
    M30HX_CirA_Comp1MotorAmpL3_Desc = (By.XPATH,'//*[@id="collapsible-1"]/div[2]/div[1]/div/div/div[3]/label/span')
    M30HX_CirA_Comp1MotorAmpL3_Val = (By.XPATH,'//*[@id="collapsible-1"]/div[2]/div[1]/div/div/div[3]/div/input')
    M30HX_CirA_Comp1MotorAmpL4_Desc = (By.XPATH,'//*[@id="collapsible-1"]/div[2]/div[1]/div/div/div[4]/label/span')
    M30HX_CirA_Comp1MotorAmpL4_Val = (By.XPATH,'//*[@id="collapsible-1"]/div[2]/div[1]/div/div/div[4]/div/input')
    M30HX_CirA_Comp2MotorAmpL1_Desc = (By.XPATH,'//*[@id="collapsible-1"]/div[3]/div[1]/div/div/div[1]/label/span')
    M30HX_CirA_Comp2MotorAmpL1_Val = (By.XPATH,'//*[@id="collapsible-1"]/div[3]/div[1]/div/div/div[1]/div/input')
    M30HX_CirA_Comp2MotorAmpL2_Desc = (By.XPATH,'//*[@id="collapsible-1"]/div[3]/div[1]/div/div/div[2]/label/span')
    M30HX_CirA_Comp2MotorAmpL2_Val = (By.XPATH,'//*[@id="collapsible-1"]/div[3]/div[1]/div/div/div[2]/div/input')
    M30HX_CirA_Comp2MotorAmpL3_Desc = (By.XPATH,'//*[@id="collapsible-1"]/div[3]/div[1]/div/div/div[3]/label/span')
    M30HX_CirA_Comp2MotorAmpL3_Val = (By.XPATH,'//*[@id="collapsible-1"]/div[3]/div[1]/div/div/div[3]/div/input')
    M30HX_CirA_Comp2MotorAmpL4_Desc = (By.XPATH,'//*[@id="collapsible-1"]/div[3]/div[1]/div/div/div[4]/label/span')
    M30HX_CirA_Comp2MotorAmpL4_Val = (By.XPATH,'//*[@id="collapsible-1"]/div[3]/div[1]/div/div/div[4]/div/input')
    M30HX_CirA_Comp3MotorAmpL1_Desc = (By.XPATH,'//*[@id="collapsible-1"]/div[4]/div[1]/div/div/div[1]/label/span')
    M30HX_CirA_Comp3MotorAmpL1_Val = (By.XPATH,'//*[@id="collapsible-1"]/div[4]/div[1]/div/div/div[1]/div/input')
    M30HX_CirA_Comp3MotorAmpL2_Desc = (By.XPATH,'//*[@id="collapsible-1"]/div[4]/div[1]/div/div/div[2]/label/span')
    M30HX_CirA_Comp3MotorAmpL2_Val = (By.XPATH,'//*[@id="collapsible-1"]/div[4]/div[1]/div/div/div[2]/div/input')
    M30HX_CirA_Comp3MotorAmpL3_Desc = (By.XPATH,'//*[@id="collapsible-1"]/div[4]/div[1]/div/div/div[3]/label/span')
    M30HX_CirA_Comp3MotorAmpL3_Val = (By.XPATH,'//*[@id="collapsible-1"]/div[4]/div[1]/div/div/div[3]/div/input')
    M30HX_CirA_Comp3MotorAmpL4_Desc = (By.XPATH,'//*[@id="collapsible-1"]/div[4]/div[1]/div/div/div[4]/label/span')
    M30HX_CirA_Comp3MotorAmpL4_Val = (By.XPATH,'//*[@id="collapsible-1"]/div[4]/div[1]/div/div/div[4]/div/input')
    M30HX_CirA_Comp4MotorAmpL1_Desc = (By.XPATH,'//*[@id="collapsible-1"]/div[5]/div[1]/div/div/div[1]/label/span')
    M30HX_CirA_Comp4MotorAmpL1_Val = (By.XPATH,'//*[@id="collapsible-1"]/div[5]/div[1]/div/div/div[1]/div/input')
    M30HX_CirA_Comp4MotorAmpL2_Desc = (By.XPATH,'//*[@id="collapsible-1"]/div[5]/div[1]/div/div/div[2]/label/span')
    M30HX_CirA_Comp4MotorAmpL2_Val = (By.XPATH,'//*[@id="collapsible-1"]/div[5]/div[1]/div/div/div[2]/div/input')
    M30HX_CirA_Comp4MotorAmpL3_Desc = (By.XPATH,'//*[@id="collapsible-1"]/div[5]/div[1]/div/div/div[3]/label/span')
    M30HX_CirA_Comp4MotorAmpL3_Val = (By.XPATH,'//*[@id="collapsible-1"]/div[5]/div[1]/div/div/div[3]/div/input')
    M30HX_CirA_Comp4MotorAmpL4_Desc = (By.XPATH,'//*[@id="collapsible-1"]/div[5]/div[1]/div/div/div[4]/label/span')
    M30HX_CirA_Comp4MotorAmpL4_Val = (By.XPATH,'//*[@id="collapsible-1"]/div[5]/div[1]/div/div/div[4]/div/input')
    M30HX_CirA_PMChecklistChkpump_Desc = (By.XPATH,'//*[@id="collapsible-1"]/div[6]/div[1]/div/div/div[1]/label/span')
    M30HX_CirA_PMChecklistChkpump_val = (By.XPATH,'//*[@id="collapsible-1"]/div[6]/div[1]/div/div/div[1]/div/input')
    M30HX_CirA_PMChecklistChkStrn_Desc = (By.XPATH,'//*[@id="collapsible-1"]/div[6]/div[1]/div/div/div[2]/label/span')
    M30HX_CirA_PMChecklistChkStrn_val = (By.XPATH,'//*[@id="collapsible-1"]/div[6]/div[1]/div/div/div[2]/div/input')
    M30HX_CirA_PMChecklistChkCondCoil_Desc = (By.XPATH,'//*[@id="collapsible-1"]/div[6]/div[1]/div/div/div[3]/label/span')
    M30HX_CirA_PMChecklistChkCondCoil_val = (By.XPATH,'//*[@id="collapsible-1"]/div[6]/div[1]/div/div/div[3]/div/input')
    M30HX_CirA_PMChecklistChkVSD_Desc = (By.XPATH,'//*[@id="collapsible-1"]/div[6]/div[1]/div/div/div[4]/label/span')
    M30HX_CirA_PMChecklistChkVSD_val = (By.XPATH,'//*[@id="collapsible-1"]/div[6]/div[1]/div/div/div[4]/div/input')
    M30HX_CirA_PMChecklistChkCondFan_Desc = (By.XPATH,'//*[@id="collapsible-1"]/div[6]/div[1]/div/div/div[5]/label/span')
    M30HX_CirA_PMChecklistChkCondFan_val = (By.XPATH,'//*[@id="collapsible-1"]/div[6]/div[1]/div/div/div[5]/div/input')
    M30HX_CirA_PMChecklistChkSetpnt_Desc = (By.XPATH,'//*[@id="collapsible-1"]/div[6]/div[1]/div/div/div[6]/label/span')
    M30HX_CirA_PMChecklistChkSetpnt_val = (By.XPATH,'//*[@id="collapsible-1"]/div[6]/div[1]/div/div/div[6]/div/input')
    M30HX_CirA_PMChecklistChkRefType_Desc = (By.XPATH,'//*[@id="collapsible-1"]/div[6]/div[1]/div/div/div[7]/label/span')
    M30HX_CirA_PMChecklistChkRefType_val = (By.XPATH,'//*[@id="collapsible-1"]/div[6]/div[1]/div/div/div[7]/div/input')
    M30HX_CirB_OperHrs_Desc = (By.XPATH,'//*[@id="collapsible-2"]/div[1]/div[1]/div/div/div[1]/label/span')
    M30HX_CirB_OperHrs_Val = (By.XPATH,'//*[@id="collapsible-2"]/div[1]/div[1]/div/div/div[1]/div/input')
    M30HX_CirB_Starts_Desc = (By.XPATH,'//*[@id="collapsible-2"]/div[1]/div[1]/div/div/div[2]/label/span')
    M30HX_CirB_Starts_Val = (By.XPATH,'//*[@id="collapsible-2"]/div[1]/div[1]/div/div/div[2]/div/input')
    M30HX_CirB_Capacity_Desc = (By.XPATH,'//*[@id="collapsible-2"]/div[1]/div[1]/div/div/div[3]/label/span')
    M30HX_CirB_Capacity_Val = (By.XPATH,'//*[@id="collapsible-2"]/div[1]/div[1]/div/div/div[3]/div/input')
    M30HX_CirB_DischargePres_Desc = (By.XPATH,'//*[@id="collapsible-2"]/div[1]/div[1]/div/div/div[4]/label/span')
    M30HX_CirB_DischargePres_Val = (By.XPATH,'//*[@id="collapsible-2"]/div[1]/div[1]/div/div/div[4]/div/input')
    M30HX_CirB_SatCondTemp_Desc = (By.XPATH,'//*[@id="collapsible-2"]/div[1]/div[1]/div/div/div[5]/label/span')
    M30HX_CirB_SatCondTemp_Val = (By.XPATH,'//*[@id="collapsible-2"]/div[1]/div[1]/div/div/div[5]/div/input')
    M30HX_CirB_SuctTemp_Desc = (By.XPATH,'//*[@id="collapsible-2"]/div[1]/div[1]/div/div/div[6]/label/span')
    M30HX_CirB_SuctTemp_Val = (By.XPATH,'//*[@id="collapsible-2"]/div[1]/div[1]/div/div/div[6]/div/input')
    M30HX_CirB_SuperHeat_Desc = (By.XPATH,'//*[@id="collapsible-2"]/div[1]/div[1]/div/div/div[7]/label/span')
    M30HX_CirB_SuperHeat_Val = (By.XPATH,'//*[@id="collapsible-2"]/div[1]/div[1]/div/div/div[7]/div/input')
    M30HX_CirB_ChwDeltaP_Desc = (By.XPATH,'//*[@id="collapsible-2"]/div[1]/div[1]/div/div/div[8]/label/span')
    M30HX_CirB_ChwDeltaP_Val = (By.XPATH,'//*[@id="collapsible-2"]/div[1]/div[1]/div/div/div[8]/div/input')
    M30HX_CirB_Sst_Desc = (By.XPATH,'//*[@id="collapsible-2"]/div[1]/div[1]/div/div/div[9]/label/span')
    M30HX_CirB_Sst_Val = (By.XPATH,'//*[@id="collapsible-2"]/div[1]/div[1]/div/div/div[9]/div/input')
    M30HX_CirB_OilPress_Desc = (By.XPATH,'//*[@id="collapsible-2"]/div[1]/div[1]/div/div/div[10]/label/span')
    M30HX_CirB_OilPress_Val = (By.XPATH,'//*[@id="collapsible-2"]/div[1]/div[1]/div/div/div[10]/div/input')
    M30HX_CirB_EXV_Desc = (By.XPATH,'//*[@id="collapsible-2"]/div[1]/div[1]/div/div/div[11]/label/span')
    M30HX_CirB_EXV_Val = (By.XPATH,'//*[@id="collapsible-2"]/div[1]/div[1]/div/div/div[11]/div/input')
    M30HX_CirB_WaterIn_Desc = (By.XPATH,'//*[@id="collapsible-2"]/div[1]/div[1]/div/div/div[12]/label/span')
    M30HX_CirB_WaterIn_Val = (By.XPATH,'//*[@id="collapsible-2"]/div[1]/div[1]/div/div/div[12]/div/input')
    M30HX_CirB_WaterOut_Desc = (By.XPATH,'//*[@id="collapsible-2"]/div[1]/div[1]/div/div/div[13]/label/span')
    M30HX_CirB_WaterOut_Val = (By.XPATH,'//*[@id="collapsible-2"]/div[1]/div[1]/div/div/div[13]/div/input')
    M30HX_CirB_EconPress_Desc = (By.XPATH,'//*[@id="collapsible-2"]/div[1]/div[1]/div/div/div[14]/label/span')
    M30HX_CirB_EconPress_Val = (By.XPATH,'//*[@id="collapsible-2"]/div[1]/div[1]/div/div/div[14]/div/input')
    M30HX_CirB_IntFD_Desc = (By.XPATH,'//*[@id="collapsible-2"]/div[1]/div[1]/div/div/div[15]/label/span')
    M30HX_CirB_IntFD_Val = (By.XPATH,'//*[@id="collapsible-2"]/div[1]/div[1]/div/div/div[15]/div/input')
    M30HX_CirB_SGT_Desc = (By.XPATH,'//*[@id="collapsible-2"]/div[1]/div[1]/div/div/div[16]/label/span')
    M30HX_CirB_SGT_Val = (By.XPATH,'//*[@id="collapsible-2"]/div[1]/div[1]/div/div/div[16]/div/input')
    M30HX_CirB_Usr1_Desc = (By.XPATH,'//*[@id="collapsible-2"]/div[1]/div[1]/div/div/div[17]/label/span')
    M30HX_CirB_Usr1_val = (By.XPATH,'//*[@id="collapsible-2"]/div[1]/div[1]/div/div/div[17]/div/input')
    M30HX_CirB_Usr2_Desc = (By.XPATH,'//*[@id="collapsible-2"]/div[1]/div[1]/div/div/div[18]/label/span')
    M30HX_CirB_Usr2_val = (By.XPATH,'//*[@id="collapsible-2"]/div[1]/div[1]/div/div/div[18]/div/input')
    M30HX_CirB_Usr3_Desc = (By.XPATH,'//*[@id="collapsible-2"]/div[1]/div[1]/div/div/div[19]/label/span')
    M30HX_CirB_Usr3_val = (By.XPATH,'//*[@id="collapsible-2"]/div[1]/div[1]/div/div/div[19]/div/input')
    M30HX_CirB_Usr4_Desc = (By.XPATH,'//*[@id="collapsible-2"]/div[1]/div[1]/div/div/div[20]/label/span')
    M30HX_CirB_Usr4_val = (By.XPATH,'//*[@id="collapsible-2"]/div[1]/div[1]/div/div/div[20]/div/input')
    M30HX_CirB_Comp1MotorAmpL1_Desc = (By.XPATH,'//*[@id="collapsible-2"]/div[2]/div[1]/div/div/div[1]/label/span')
    M30HX_CirB_Comp1MotorAmpL1_Val = (By.XPATH,'//*[@id="collapsible-2"]/div[2]/div[1]/div/div/div[1]/div/input')
    M30HX_CirB_Comp1MotorAmpL2_Desc = (By.XPATH,'//*[@id="collapsible-2"]/div[2]/div[1]/div/div/div[2]/label/span')
    M30HX_CirB_Comp1MotorAmpL2_Val = (By.XPATH,'//*[@id="collapsible-2"]/div[2]/div[1]/div/div/div[2]/div/input')
    M30HX_CirB_Comp1MotorAmpL3_Desc = (By.XPATH,'//*[@id="collapsible-2"]/div[2]/div[1]/div/div/div[3]/label/span')
    M30HX_CirB_Comp1MotorAmpL3_Val = (By.XPATH,'//*[@id="collapsible-2"]/div[2]/div[1]/div/div/div[3]/div/input')
    M30HX_CirB_Comp1MotorAmpL4_Desc = (By.XPATH,'//*[@id="collapsible-2"]/div[2]/div[1]/div/div/div[4]/label/span')
    M30HX_CirB_Comp1MotorAmpL4_Val = (By.XPATH,'//*[@id="collapsible-2"]/div[2]/div[1]/div/div/div[4]/div/input')
    M30HX_CirB_Comp2MotorAmpL1_Desc = (By.XPATH,'//*[@id="collapsible-2"]/div[3]/div[1]/div/div/div[1]/label/span')
    M30HX_CirB_Comp2MotorAmpL1_Val = (By.XPATH,'//*[@id="collapsible-2"]/div[3]/div[1]/div/div/div[1]/div/input')
    M30HX_CirB_Comp2MotorAmpL2_Desc = (By.XPATH,'//*[@id="collapsible-2"]/div[3]/div[1]/div/div/div[2]/label/span')
    M30HX_CirB_Comp2MotorAmpL2_Val = (By.XPATH,'//*[@id="collapsible-2"]/div[3]/div[1]/div/div/div[2]/div/input')
    M30HX_CirB_Comp2MotorAmpL3_Desc = (By.XPATH,'//*[@id="collapsible-2"]/div[3]/div[1]/div/div/div[3]/label/span')
    M30HX_CirB_Comp2MotorAmpL3_Val = (By.XPATH,'//*[@id="collapsible-2"]/div[3]/div[1]/div/div/div[3]/div/input')
    M30HX_CirB_Comp2MotorAmpL4_Desc = (By.XPATH,'//*[@id="collapsible-2"]/div[3]/div[1]/div/div/div[4]/label/span')
    M30HX_CirB_Comp2MotorAmpL4_Val = (By.XPATH,'//*[@id="collapsible-2"]/div[3]/div[1]/div/div/div[4]/div/input')
    M30HX_CirB_Comp3MotorAmpL1_Desc = (By.XPATH,'//*[@id="collapsible-2"]/div[4]/div[1]/div/div/div[1]/label/span')
    M30HX_CirB_Comp3MotorAmpL1_Val = (By.XPATH,'//*[@id="collapsible-2"]/div[4]/div[1]/div/div/div[1]/div/input')
    M30HX_CirB_Comp3MotorAmpL2_Desc = (By.XPATH,'//*[@id="collapsible-2"]/div[4]/div[1]/div/div/div[2]/label/span')
    M30HX_CirB_Comp3MotorAmpL2_Val = (By.XPATH,'//*[@id="collapsible-2"]/div[4]/div[1]/div/div/div[2]/div/input')
    M30HX_CirB_Comp3MotorAmpL3_Desc = (By.XPATH,'//*[@id="collapsible-2"]/div[4]/div[1]/div/div/div[3]/label/span')
    M30HX_CirB_Comp3MotorAmpL3_Val = (By.XPATH,'//*[@id="collapsible-2"]/div[4]/div[1]/div/div/div[3]/div/input')
    M30HX_CirB_Comp3MotorAmpL4_Desc = (By.XPATH,'//*[@id="collapsible-2"]/div[4]/div[1]/div/div/div[4]/label/span')
    M30HX_CirB_Comp3MotorAmpL4_Val = (By.XPATH,'//*[@id="collapsible-2"]/div[4]/div[1]/div/div/div[4]/div/input')
    M30HX_CirB_Comp4MotorAmpL1_Desc = (By.XPATH,'//*[@id="collapsible-2"]/div[5]/div[1]/div/div/div[1]/label/span')
    M30HX_CirB_Comp4MotorAmpL1_Val = (By.XPATH,'//*[@id="collapsible-2"]/div[5]/div[1]/div/div/div[1]/div/input')
    M30HX_CirB_Comp4MotorAmpL2_Desc = (By.XPATH,'//*[@id="collapsible-2"]/div[5]/div[1]/div/div/div[2]/label/span')
    M30HX_CirB_Comp4MotorAmpL2_Val = (By.XPATH,'//*[@id="collapsible-2"]/div[5]/div[1]/div/div/div[2]/div/input')
    M30HX_CirB_Comp4MotorAmpL3_Desc = (By.XPATH,'//*[@id="collapsible-2"]/div[5]/div[1]/div/div/div[3]/label/span')
    M30HX_CirB_Comp4MotorAmpL3_Val = (By.XPATH,'//*[@id="collapsible-2"]/div[5]/div[1]/div/div/div[3]/div/input')
    M30HX_CirB_Comp4MotorAmpL4_Desc = (By.XPATH,'//*[@id="collapsible-2"]/div[5]/div[1]/div/div/div[4]/label/span')
    M30HX_CirB_Comp4MotorAmpL4_Val = (By.XPATH,'//*[@id="collapsible-2"]/div[5]/div[1]/div/div/div[4]/div/input')
    M30HX_CirB_PMChecklistChkpump_Desc = (By.XPATH,'//*[@id="collapsible-2"]/div[6]/div[1]/div/div/div[1]/label/span')
    M30HX_CirB_PMChecklistChkpump_val = (By.XPATH,'//*[@id="collapsible-2"]/div[6]/div[1]/div/div/div[1]/div/input')
    M30HX_CirB_PMChecklistChkStrn_Desc = (By.XPATH,'//*[@id="collapsible-2"]/div[6]/div[1]/div/div/div[2]/label/span')
    M30HX_CirB_PMChecklistChkStrn_val = (By.XPATH,'//*[@id="collapsible-2"]/div[6]/div[1]/div/div/div[2]/div/input')
    M30HX_CirB_PMChecklistChkCondCoil_Desc = (By.XPATH,'//*[@id="collapsible-2"]/div[6]/div[1]/div/div/div[3]/label/span')
    M30HX_CirB_PMChecklistChkCondCoil_val = (By.XPATH,'//*[@id="collapsible-2"]/div[6]/div[1]/div/div/div[3]/div/input')
    M30HX_CirB_PMChecklistChkVSD_Desc = (By.XPATH,'//*[@id="collapsible-2"]/div[6]/div[1]/div/div/div[4]/label/span')
    M30HX_CirB_PMChecklistChkVSD_val = (By.XPATH,'//*[@id="collapsible-2"]/div[6]/div[1]/div/div/div[4]/div/input')
    M30HX_CirB_PMChecklistChkCondFan_Desc = (By.XPATH,'//*[@id="collapsible-2"]/div[6]/div[1]/div/div/div[5]/label/span')
    M30HX_CirB_PMChecklistChkCondFan_val = (By.XPATH,'//*[@id="collapsible-2"]/div[6]/div[1]/div/div/div[5]/div/input')
    M30HX_CirB_PMChecklistChkSetpnt_Desc = (By.XPATH,'//*[@id="collapsible-2"]/div[6]/div[1]/div/div/div[6]/label/span')
    M30HX_CirB_PMChecklistChkSetpnt_val = (By.XPATH,'//*[@id="collapsible-2"]/div[6]/div[1]/div/div/div[6]/div/input')
    M30HX_CirB_PMChecklistChkRefType_Desc = (By.XPATH,'//*[@id="collapsible-2"]/div[6]/div[1]/div/div/div[7]/label/span')
    M30HX_CirB_PMChecklistChkRefType_val = (By.XPATH,'//*[@id="collapsible-2"]/div[6]/div[1]/div/div/div[7]/div/input')
    M30HX_CirC_OperHrs_Desc = (By.XPATH,'//*[@id="collapsible-3"]/div[1]/div[1]/div/div/div[1]/label/span')
    M30HX_CirC_OperHrs_Val = (By.XPATH,'//*[@id="collapsible-3"]/div[1]/div[1]/div/div/div[1]/div/input')
    M30HX_CirC_Starts_Desc = (By.XPATH,'//*[@id="collapsible-3"]/div[1]/div[1]/div/div/div[2]/label/span')
    M30HX_CirC_Starts_Val = (By.XPATH,'//*[@id="collapsible-3"]/div[1]/div[1]/div/div/div[2]/div/input')
    M30HX_CirC_Capacity_Desc = (By.XPATH,'//*[@id="collapsible-3"]/div[1]/div[1]/div/div/div[3]/label/span')
    M30HX_CirC_Capacity_Val = (By.XPATH,'//*[@id="collapsible-3"]/div[1]/div[1]/div/div/div[3]/div/input')
    M30HX_CirC_DischargePres_Desc = (By.XPATH,'//*[@id="collapsible-3"]/div[1]/div[1]/div/div/div[4]/label/span')
    M30HX_CirC_DischargePres_Val = (By.XPATH,'//*[@id="collapsible-3"]/div[1]/div[1]/div/div/div[4]/div/input')
    M30HX_CirC_SatCondTemp_Desc = (By.XPATH,'//*[@id="collapsible-3"]/div[1]/div[1]/div/div/div[5]/label/span')
    M30HX_CirC_SatCondTemp_Val = (By.XPATH,'//*[@id="collapsible-3"]/div[1]/div[1]/div/div/div[5]/div/input')
    M30HX_CirC_SuctTemp_Desc = (By.XPATH,'//*[@id="collapsible-3"]/div[1]/div[1]/div/div/div[6]/label/span')
    M30HX_CirC_SuctTemp_Val = (By.XPATH,'//*[@id="collapsible-3"]/div[1]/div[1]/div/div/div[6]/div/input')
    M30HX_CirC_SuperHeat_Desc = (By.XPATH,'//*[@id="collapsible-3"]/div[1]/div[1]/div/div/div[7]/label/span')
    M30HX_CirC_SuperHeat_Val = (By.XPATH,'//*[@id="collapsible-3"]/div[1]/div[1]/div/div/div[7]/div/input')
    M30HX_CirC_ChwDeltaP_Desc = (By.XPATH,'//*[@id="collapsible-3"]/div[1]/div[1]/div/div/div[8]/label/span')
    M30HX_CirC_ChwDeltaP_Val = (By.XPATH,'//*[@id="collapsible-3"]/div[1]/div[1]/div/div/div[8]/div/input')
    M30HX_CirC_Sst_Desc = (By.XPATH,'//*[@id="collapsible-3"]/div[1]/div[1]/div/div/div[9]/label/span')
    M30HX_CirC_Sst_Val = (By.XPATH,'//*[@id="collapsible-3"]/div[1]/div[1]/div/div/div[9]/div/input')
    M30HX_CirC_OilPress_Desc = (By.XPATH,'//*[@id="collapsible-3"]/div[1]/div[1]/div/div/div[10]/label/span')
    M30HX_CirC_OilPress_Val = (By.XPATH,'//*[@id="collapsible-3"]/div[1]/div[1]/div/div/div[10]/div/input')
    M30HX_CirC_EXV_Desc = (By.XPATH,'//*[@id="collapsible-3"]/div[1]/div[1]/div/div/div[11]/label/span')
    M30HX_CirC_EXV_Val = (By.XPATH,'//*[@id="collapsible-3"]/div[1]/div[1]/div/div/div[11]/div/input')
    M30HX_CirC_WaterIn_Desc = (By.XPATH,'//*[@id="collapsible-3"]/div[1]/div[1]/div/div/div[12]/label/span')
    M30HX_CirC_WaterIn_Val = (By.XPATH,'//*[@id="collapsible-3"]/div[1]/div[1]/div/div/div[12]/div/input')
    M30HX_CirC_WaterOut_Desc = (By.XPATH,'//*[@id="collapsible-3"]/div[1]/div[1]/div/div/div[13]/label/span')
    M30HX_CirC_WaterOut_Val = (By.XPATH,'//*[@id="collapsible-3"]/div[1]/div[1]/div/div/div[13]/div/input')
    M30HX_CirC_EconPress_Desc = (By.XPATH,'//*[@id="collapsible-3"]/div[1]/div[1]/div/div/div[14]/label/span')
    M30HX_CirC_EconPress_Val = (By.XPATH,'//*[@id="collapsible-3"]/div[1]/div[1]/div/div/div[14]/div/input')
    M30HX_CirC_IntFD_Desc = (By.XPATH,'//*[@id="collapsible-3"]/div[1]/div[1]/div/div/div[15]/label/span')
    M30HX_CirC_IntFD_Val = (By.XPATH,'//*[@id="collapsible-3"]/div[1]/div[1]/div/div/div[15]/div/input')
    M30HX_CirC_SGT_Desc = (By.XPATH,'//*[@id="collapsible-3"]/div[1]/div[1]/div/div/div[16]/label/span')
    M30HX_CirC_SGT_Val = (By.XPATH,'//*[@id="collapsible-3"]/div[1]/div[1]/div/div/div[16]/div/input')
    M30HX_CirC_Usr1_Desc = (By.XPATH,'//*[@id="collapsible-3"]/div[1]/div[1]/div/div/div[17]/label/span')
    M30HX_CirC_Usr1_val = (By.XPATH,'//*[@id="collapsible-3"]/div[1]/div[1]/div/div/div[17]/div/input')
    M30HX_CirC_Usr2_Desc = (By.XPATH,'//*[@id="collapsible-3"]/div[1]/div[1]/div/div/div[18]/label/span')
    M30HX_CirC_Usr2_val = (By.XPATH,'//*[@id="collapsible-3"]/div[1]/div[1]/div/div/div[18]/div/input')
    M30HX_CirC_Usr3_Desc = (By.XPATH,'//*[@id="collapsible-3"]/div[1]/div[1]/div/div/div[19]/label/span')
    M30HX_CirC_Usr3_val = (By.XPATH,'//*[@id="collapsible-3"]/div[1]/div[1]/div/div/div[19]/div/input')
    M30HX_CirC_Usr4_Desc = (By.XPATH,'//*[@id="collapsible-3"]/div[1]/div[1]/div/div/div[20]/label/span')
    M30HX_CirC_Usr4_val = (By.XPATH,'//*[@id="collapsible-3"]/div[1]/div[1]/div/div/div[20]/div/input')
    M30HX_CirC_Comp1MotorAmpL1_Desc = (By.XPATH,'//*[@id="collapsible-3"]/div[2]/div[1]/div/div/div[1]/label/span')
    M30HX_CirC_Comp1MotorAmpL1_Val = (By.XPATH,'//*[@id="collapsible-3"]/div[2]/div[1]/div/div/div[1]/div/input')
    M30HX_CirC_Comp1MotorAmpL2_Desc = (By.XPATH,'//*[@id="collapsible-3"]/div[2]/div[1]/div/div/div[2]/label/span')
    M30HX_CirC_Comp1MotorAmpL2_Val = (By.XPATH,'//*[@id="collapsible-3"]/div[2]/div[1]/div/div/div[2]/div/input')
    M30HX_CirC_Comp1MotorAmpL3_Desc = (By.XPATH,'//*[@id="collapsible-3"]/div[2]/div[1]/div/div/div[3]/label/span')
    M30HX_CirC_Comp1MotorAmpL3_Val = (By.XPATH,'//*[@id="collapsible-3"]/div[2]/div[1]/div/div/div[3]/div/input')
    M30HX_CirC_Comp1MotorAmpL4_Desc = (By.XPATH,'//*[@id="collapsible-3"]/div[2]/div[1]/div/div/div[4]/label/span')
    M30HX_CirC_Comp1MotorAmpL4_Val = (By.XPATH,'//*[@id="collapsible-3"]/div[2]/div[1]/div/div/div[4]/div/input')
    M30HX_CirC_Comp2MotorAmpL1_Desc = (By.XPATH,'//*[@id="collapsible-3"]/div[3]/div[1]/div/div/div[1]/label/span')
    M30HX_CirC_Comp2MotorAmpL1_Val = (By.XPATH,'//*[@id="collapsible-3"]/div[3]/div[1]/div/div/div[1]/div/input')
    M30HX_CirC_Comp2MotorAmpL2_Desc = (By.XPATH,'//*[@id="collapsible-3"]/div[3]/div[1]/div/div/div[2]/label/span')
    M30HX_CirC_Comp2MotorAmpL2_Val = (By.XPATH,'//*[@id="collapsible-3"]/div[3]/div[1]/div/div/div[2]/div/input')
    M30HX_CirC_Comp2MotorAmpL3_Desc = (By.XPATH,'//*[@id="collapsible-3"]/div[3]/div[1]/div/div/div[3]/label/span')
    M30HX_CirC_Comp2MotorAmpL3_Val = (By.XPATH,'//*[@id="collapsible-3"]/div[3]/div[1]/div/div/div[3]/div/input')
    M30HX_CirC_Comp2MotorAmpL4_Desc = (By.XPATH,'//*[@id="collapsible-3"]/div[3]/div[1]/div/div/div[4]/label/span')
    M30HX_CirC_Comp2MotorAmpL4_Val = (By.XPATH,'//*[@id="collapsible-3"]/div[3]/div[1]/div/div/div[4]/div/input')
    M30HX_CirC_Comp3MotorAmpL1_Desc = (By.XPATH,'//*[@id="collapsible-3"]/div[4]/div[1]/div/div/div[1]/label/span')
    M30HX_CirC_Comp3MotorAmpL1_Val = (By.XPATH,'//*[@id="collapsible-3"]/div[4]/div[1]/div/div/div[1]/div/input')
    M30HX_CirC_Comp3MotorAmpL2_Desc = (By.XPATH,'//*[@id="collapsible-3"]/div[4]/div[1]/div/div/div[2]/label/span')
    M30HX_CirC_Comp3MotorAmpL2_Val = (By.XPATH,'//*[@id="collapsible-3"]/div[4]/div[1]/div/div/div[2]/div/input')
    M30HX_CirC_Comp3MotorAmpL3_Desc = (By.XPATH,'//*[@id="collapsible-3"]/div[4]/div[1]/div/div/div[3]/label/span')
    M30HX_CirC_Comp3MotorAmpL3_Val = (By.XPATH,'//*[@id="collapsible-3"]/div[4]/div[1]/div/div/div[3]/div/input')
    M30HX_CirC_Comp3MotorAmpL4_Desc = (By.XPATH,'//*[@id="collapsible-3"]/div[4]/div[1]/div/div/div[4]/label/span')
    M30HX_CirC_Comp3MotorAmpL4_Val = (By.XPATH,'//*[@id="collapsible-3"]/div[4]/div[1]/div/div/div[4]/div/input')
    M30HX_CirC_Comp4MotorAmpL1_Desc = (By.XPATH,'//*[@id="collapsible-3"]/div[5]/div[1]/div/div/div[1]/label/span')
    M30HX_CirC_Comp4MotorAmpL1_Val = (By.XPATH,'//*[@id="collapsible-3"]/div[5]/div[1]/div/div/div[1]/div/input')
    M30HX_CirC_Comp4MotorAmpL2_Desc = (By.XPATH,'//*[@id="collapsible-3"]/div[5]/div[1]/div/div/div[2]/label/span')
    M30HX_CirC_Comp4MotorAmpL2_Val = (By.XPATH,'//*[@id="collapsible-3"]/div[5]/div[1]/div/div/div[2]/div/input')
    M30HX_CirC_Comp4MotorAmpL3_Desc = (By.XPATH,'//*[@id="collapsible-3"]/div[5]/div[1]/div/div/div[3]/label/span')
    M30HX_CirC_Comp4MotorAmpL3_Val = (By.XPATH,'//*[@id="collapsible-3"]/div[5]/div[1]/div/div/div[3]/div/input')
    M30HX_CirC_Comp4MotorAmpL4_Desc = (By.XPATH,'//*[@id="collapsible-3"]/div[5]/div[1]/div/div/div[4]/label/span')
    M30HX_CirC_Comp4MotorAmpL4_Val = (By.XPATH,'//*[@id="collapsible-3"]/div[5]/div[1]/div/div/div[4]/div/input')
    M30HX_CirC_PMChecklistChkpump_Desc = (By.XPATH,'//*[@id="collapsible-3"]/div[6]/div[1]/div/div/div[1]/label/span')
    M30HX_CirC_PMChecklistChkpump_val = (By.XPATH,'//*[@id="collapsible-3"]/div[6]/div[1]/div/div/div[1]/div/input')
    M30HX_CirC_PMChecklistChkStrn_Desc = (By.XPATH,'//*[@id="collapsible-3"]/div[6]/div[1]/div/div/div[2]/label/span')
    M30HX_CirC_PMChecklistChkStrn_val = (By.XPATH,'//*[@id="collapsible-3"]/div[6]/div[1]/div/div/div[2]/div/input')
    M30HX_CirC_PMChecklistChkCondCoil_Desc = (By.XPATH,'//*[@id="collapsible-3"]/div[6]/div[1]/div/div/div[3]/label/span')
    M30HX_CirC_PMChecklistChkCondCoil_val = (By.XPATH,'//*[@id="collapsible-3"]/div[6]/div[1]/div/div/div[3]/div/input')
    M30HX_CirC_PMChecklistChkVSD_Desc = (By.XPATH,'//*[@id="collapsible-3"]/div[6]/div[1]/div/div/div[4]/label/span')
    M30HX_CirC_PMChecklistChkVSD_val = (By.XPATH,'//*[@id="collapsible-3"]/div[6]/div[1]/div/div/div[4]/div/input')
    M30HX_CirC_PMChecklistChkCondFan_Desc = (By.XPATH,'//*[@id="collapsible-3"]/div[6]/div[1]/div/div/div[5]/label/span')
    M30HX_CirC_PMChecklistChkCondFan_val = (By.XPATH,'//*[@id="collapsible-3"]/div[6]/div[1]/div/div/div[5]/div/input')
    M30HX_CirC_PMChecklistChkSetpnt_Desc = (By.XPATH,'//*[@id="collapsible-3"]/div[6]/div[1]/div/div/div[6]/label/span')
    M30HX_CirC_PMChecklistChkSetpnt_val = (By.XPATH,'//*[@id="collapsible-3"]/div[6]/div[1]/div/div/div[6]/div/input')
    M30HX_CirC_PMChecklistChkRefType_Desc = (By.XPATH,'//*[@id="collapsible-3"]/div[6]/div[1]/div/div/div[7]/label/span')
    M30HX_CirC_PMChecklistChkRefType_val = (By.XPATH,'//*[@id="collapsible-3"]/div[6]/div[1]/div/div/div[7]/div/input')

    #30XWV,30XW
    M30XW_Default = (By.XPATH, '//*[@id="output"]')
    M30XW_percCapacperCirA_Desc = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[1]/div[1]/div/div/div[1]/label/span')
    M30XW_percCapacperCirA_Val = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[1]/div[1]/div/div/div[1]/div/input')
    M30XW_percCapacperCirB_Desc = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[1]/div[1]/div/div/div[2]/label/span')
    M30XW_percCapacperCirB_Val = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[1]/div[1]/div/div/div[2]/div/input')
    M30XW_coolerRef_suctPressA_Desc = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[2]/div[1]/div[1]/div/div[1]/label/span')
    M30XW_coolerRef_suctPressA_Val = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[2]/div[1]/div[1]/div/div[1]/div/input')
    M30XW_coolerRef_suctTempA_Desc = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[2]/div[1]/div[1]/div/div[2]/label/span')
    M30XW_coolerRef_suctTempA_Val = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[2]/div[1]/div[1]/div/div[2]/div/input')
    M30XW_coolerRef_EconPressA_Desc = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[2]/div[1]/div[1]/div/div[3]/label/span')
    M30XW_coolerRef_EconPressA_Val = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[2]/div[1]/div[1]/div/div[3]/div/input')
    M30XW_coolerRef_EXVA_Desc = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[2]/div[1]/div[1]/div/div[4]/label/span')
    M30XW_coolerRef_EXVA_Val = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[2]/div[1]/div[1]/div/div[4]/div/input')
    M30XW_coolerRef_SuctPressB_Desc = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[2]/div[1]/div[1]/div/div[5]/label/span')
    M30XW_coolerRef_SuctPressB_Val = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[2]/div[1]/div[1]/div/div[5]/div/input')
    M30XW_coolerRef_SatSuctTempB_Desc = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[2]/div[1]/div[1]/div/div[6]/label/span')
    M30XW_coolerRef_SatSuctTempB_Val = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[2]/div[1]/div[1]/div/div[6]/div/input')
    M30XW_coolerRef_EconPressB_Desc = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[2]/div[1]/div[1]/div/div[7]/label/span')
    M30XW_coolerRef_EconPressB_Val = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[2]/div[1]/div[1]/div/div[7]/div/input')
    M30XW_coolerRef_EXVB_Desc = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[2]/div[1]/div[1]/div/div[8]/label/span')
    M30XW_coolerRef_EXVB_Val = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[2]/div[1]/div[1]/div/div[8]/div/input')
    M30XW_coolerWaterPressIn_Desc = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[2]/div[2]/div[2]/div/div/div[1]/div[1]/label')
    M30XW_coolerWaterPressIn_Val = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[2]/div[2]/div[2]/div/div/div[1]/div[1]/input')
    M30XW_coolerWaterPressOut_Desc = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[2]/div[2]/div[2]/div/div/div[1]/div[2]/label')
    M30XW_coolerWaterPressOut_Val = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[2]/div[2]/div[2]/div/div/div[1]/div[2]/input')
    M30XW_coolerWaterTempIn_Desc = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[2]/div[2]/div[2]/div/div/div[2]/div[1]/label')
    M30XW_coolerWaterTempIn_Val = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[2]/div[2]/div[2]/div/div/div[2]/div[1]/input')
    M30XW_coolerWaterTempOut_Desc = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[2]/div[2]/div[2]/div/div/div[2]/div[2]/label')
    M30XW_coolerWaterTempOut_Val = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[2]/div[2]/div[2]/div/div/div[2]/div[2]/input')
    M30XW_CondRef_DiscPressA_Desc = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[3]/div[1]/div[1]/div/div[1]/label/span')
    M30XW_CondRef_DiscPressA_Val = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[3]/div[1]/div[1]/div/div[1]/div/input')
    M30XW_CondRef_SatCondTempA_Desc = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[3]/div[1]/div[1]/div/div[2]/label/span')
    M30XW_CondRef_SatCondTempA_Val = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[3]/div[1]/div[1]/div/div[2]/div/input')
    M30XW_CondRef_DiscPressB_Desc = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[3]/div[1]/div[1]/div/div[3]/label/span')
    M30XW_CondRef_DiscPressB_Val = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[3]/div[1]/div[1]/div/div[3]/div/input')
    M30XW_CondRef_SatCondTempB_Desc = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[3]/div[1]/div[1]/div/div[4]/label/span')
    M30XW_CondRef_SatCondTempB_Val = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[3]/div[1]/div[1]/div/div[4]/div/input')
    M30XW_CondWater_PressIn_Desc = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div[1]/div[1]/label')
    M30XW_CondWater_PressIn_Val = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div[1]/div[1]/input')
    M30XW_CondWater_PressOut_Desc = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div[1]/div[2]/label')
    M30XW_CondWater_PressOut_Val = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div['
                                         '2]/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div[1]/div[2]/input')
    M30XW_CondWater_TempIn_Desc = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div[2]/div[1]/label')
    M30XW_CondWater_TempIn_Val = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div[2]/div[1]/input')
    M30XW_CondWater_TempOut_Desc = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div[2]/div[1]/label')
    M30XW_CondWater_TempOut_Val = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div[2]/div[2]/input')
    M30XW_CondWater_OAT_Desc = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[3]/div[2]/div[3]/div/div/div/div/label')
    M30XW_CondWater_OAT_Val = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[3]/div[2]/div[3]/div/div/div/div/input')
    M30XW_CompA1_DischGasTemp_Desc = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[4]/div[1]/div[1]/div/div/label/span')
    M30XW_CompA1_DischGasTemp_Val = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[4]/div[1]/div[1]/div/div/div/input')
    M30XW_CompA1_oilpressDiff_Desc = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[4]/div[2]/div[2]/div/div/div[1]/div[1]/label')
    M30XW_CompA1_oilpressDiff_Val = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[4]/div[2]/div[2]/div/div/div[1]/div[1]/input')
    M30XW_CompA1_oilpress_Desc = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[4]/div[2]/div[2]/div/div/div[1]/div[2]/label')
    M30XW_CompA1_oilpress_Val = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[4]/div[2]/div[2]/div/div/div[1]/div[2]/input')
    M30XW_CompA1_MotorTemp_Desc = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[4]/div[2]/div[2]/div/div/div[2]/div[1]/label')
    M30XW_CompA1_MotorTemp_Val = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[4]/div[2]/div[2]/div/div/div[2]/div[1]/input')
    M30XW_CompA2_DischGasTemp_Desc = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[5]/div[1]/div[1]/div/div/label/span')
    M30XW_CompA2_DischGasTemp_Val = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[5]/div[1]/div[1]/div/div/div/input')
    M30XW_CompA2_oilpressDiff_Desc = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[5]/div[2]/div[2]/div/div/div[1]/div[1]/label')
    M30XW_CompA2_oilpressDiff_Val = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[5]/div[2]/div[2]/div/div/div[1]/div[1]/input')
    M30XW_CompA2_oilpress_Desc = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[5]/div[2]/div[2]/div/div/div[1]/div[2]/label')
    M30XW_CompA2_oilpress_Val = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[5]/div[2]/div[2]/div/div/div[1]/div[2]/input')
    M30XW_CompA2_MotorTemp_Desc = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[5]/div[2]/div[2]/div/div/div[2]/div[1]/label')
    M30XW_CompA2_MotorTemp_Val = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[5]/div[2]/div[2]/div/div/div[2]/div[1]/input')
    M30XW_CompB1_DischGasTemp_Desc = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[6]/div[1]/div[1]/div/div/label/span')
    M30XW_CompB1_DischGasTemp_Val = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[6]/div[1]/div[1]/div/div/div/input')
    M30XW_CompB1_oilpressDiff_Desc = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[6]/div[2]/div[2]/div/div/div[1]/div[1]/label')
    M30XW_CompB1_oilpressDiff_Val = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[6]/div[2]/div[2]/div/div/div[1]/div[1]/input')
    M30XW_CompB1_oilpress_Desc = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[6]/div[2]/div[2]/div/div/div[1]/div[2]/label')
    M30XW_CompB1_oilpress_Val = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[6]/div[2]/div[2]/div/div/div[1]/div[2]/input')
    M30XW_CompB1_MotorTemp_Desc = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[6]/div[2]/div[2]/div/div/div[2]/div[1]/label')
    M30XW_CompB1_MotorTemp_Val = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[6]/div[2]/div[2]/div/div/div[2]/div[1]/input')
    M30XW_CompB2_DischGasTemp_Desc = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[7]/div[1]/div[1]/div/div/label/span')
    M30XW_CompB2_DischGasTemp_Val = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[7]/div[1]/div[1]/div/div/div/input')
    M30XW_CompB2_oilpressDiff_Desc = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[7]/div[2]/div[2]/div/div/div[1]/div[1]/label')
    M30XW_CompB2_oilpressDiff_Val = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[7]/div[2]/div[2]/div/div/div[1]/div[1]/input')
    M30XW_CompB2_oilpress_Desc = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[7]/div[2]/div[2]/div/div/div[1]/div[2]/label')
    M30XW_CompB2_oilpress_Val = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[7]/div[2]/div[2]/div/div/div[1]/div[2]/input')
    M30XW_CompB2_MotorTemp_Desc = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[7]/div[2]/div[2]/div/div/div[2]/div[1]/label')
    M30XW_CompB2_MotorTemp_Val = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[1]/div/div/div[2]/div[2]/form/div/div[7]/div[2]/div[2]/div/div/div[2]/div[1]/input')