from selenium.webdriver.common.by import By


class StartUpPageLocators(object):
    startupmenu = (By.XPATH, '//*[@id="tabdivisonsid"]/ul/li/a/span[1]/i')
    startupmenu_filled = (By.XPATH, '//*[@id="tabdivisonsid"]/ul/li/a/span[2]/i')
    startupmenu_reset = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[1]/ul/li[2]/a')
    startupmenu_exit = (By.XPATH, '//*[@id="aExistingForm"]')
    startupmenu_save = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[4]/ul/li[2]/a')
    startupmenu_cancel = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[4]/ul/li[1]/a')
    save_form = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[4]/ul/li[2]/a')
    save_form_popup = (By.XPATH, '//*[@id="AlmostDoneModal"]/div/div/div/form/div[3]/div/button')
    save_form_close_X = (By.XPATH, '//*[@id="SavedSuccessfullyModel"]/div/div/a')

    M39MN_option_wiring_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div/div/div[1]/div[2]/div[2]/ul[1]/li[2]/label/span')
    M39MN_option_wiring_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div/div/div[1]/div[2]/div[2]/ul[1]/li[1]/label/span')
    M39MN_option_vfd_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div/div/div[2]/div[2]/div[2]/ul[1]/li[2]/label/span')
    M39MN_option_vfd_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div/div/div[2]/div[2]/div[2]/ul[1]/li[1]/label/span')
    M39MN_option_rotation_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div/div/div[3]/div[2]/div[2]/ul[1]/li[2]/label/span')
    M39MN_option_rotation_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div/div/div[3]/div[2]/div[2]/ul[1]/li[1]/label/span')
    M39MN_option_pulleys_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div/div/div[4]/div[2]/div[2]/ul[1]/li[2]/label/span')
    M39MN_option_pullyes_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div/div/div[4]/div[2]/div[2]/ul[1]/li[1]/label/span')
    M39MN_option_sheaves_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div/div/div[5]/div[2]/div[2]/ul[1]/li[2]/label/span')
    M39MN_option_sheaves_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div/div/div[5]/div[2]/div[2]/ul[1]/li[1]/label/span')
    M39MN_option_assembly_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div/div/div[6]/div[2]/div[2]/ul[1]/li[2]/label/span')
    M39MN_option_assembly_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div/div/div[6]/div[2]/div[2]/ul[1]/li[1]/label/span')
    M39MN_Default = (By.XPATH, '//*[@id="a"]')
    M39MN_option_rpm_05 = 56
    M39MN_option_db_temp_05 = 57
    M39MN_option_wb_temp_05 = 58
    M39MN_option_leave_db_temp_05 = 59
    M39MN_option_leave_wb_temp_05 = 60
    M39MN_option_enter_temp_05 = 61
    M39MN_option_leave_temp_05 = 62
    M39MN_option_condensate_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div/div/div[16]/div[2]/div[2]/ul[1]/li[2]/label/span')
    M39MN_option_condensate_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div/div/div[16]/div[2]/div[2]/ul[1]/li[1]/label/span')
    M39MN_option_pitch_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div/div/div[17]/div[2]/div[2]/ul[1]/li[2]/label/span')
    M39MN_option_pitch_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div/div/div[17]/div[2]/div[2]/ul[1]/li[1]/label/span')
    M39MN_option_vibration_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div/div/div[18]/div[2]/div[2]/ul[1]/li[2]/label/span')
    M39MN_option_vibration_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div/div/div[18]/div[2]/div[2]/ul[1]/li[1]/label/span')
    M39MN_option_airflow_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div/div/div[19]/div[2]/div[2]/ul[1]/li[2]/label/span')
    M39MN_option_airflow_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div/div/div[19]/div[2]/div[2]/ul[1]/li[1]/label/span')

    M39MW_option_wiring_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div/div/div[1]/div[2]/div[2]/ul[1]/li[2]/label/span')
    M39MW_option_wiring_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div/div/div[1]/div[2]/div[2]/ul[1]/li[1]/label/span')
    M39MW_option_vfd_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div/div/div[2]/div[2]/div[2]/ul[1]/li[2]/label/span')
    M39MW_option_vfd_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div/div/div[2]/div[2]/div[2]/ul[1]/li[1]/label/span')
    M39MW_option_rotation_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div/div/div[3]/div[2]/div[2]/ul[1]/li[2]/label/span')
    M39MW_option_rotation_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div/div/div[3]/div[2]/div[2]/ul[1]/li[1]/label/span')
    M39MW_option_pulleys_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div/div/div[4]/div[2]/div[2]/ul[1]/li[2]/label/span')
    M39MW_option_pullyes_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div/div/div[4]/div[2]/div[2]/ul[1]/li[1]/label/span')
    M39MW_option_sheaves_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div/div/div[5]/div[2]/div[2]/ul[1]/li[2]/label/span')
    M39MW_option_sheaves_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div/div/div[5]/div[2]/div[2]/ul[1]/li[1]/label/span')
    M39MW_option_assembly_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div/div/div[6]/div[2]/div[2]/ul[1]/li[2]/label/span')
    M39MW_option_assembly_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div/div/div[6]/div[2]/div[2]/ul[1]/li[1]/label/span')
    M39MW_Default = (By.XPATH, '//*[@id="a"]')
    M39MW_option_rpm_05 = 148
    M39MW_option_db_temp_05 = 149
    M39MW_option_wb_temp_05 = 150
    M39MW_option_leave_db_temp_05 = 151
    M39MW_option_leave_wb_temp_05 = 152
    M39MW_option_enter_temp_05 = 153
    M39MW_option_leave_temp_05 = 154
    M39MW_option_condensate_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div/div/div[16]/div[2]/div[2]/ul[1]/li[2]/label/span')
    M39MW_option_condensate_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div/div/div[16]/div[2]/div[2]/ul[1]/li[1]/label/span')
    M39MW_option_pitch_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div/div/div[17]/div[2]/div[2]/ul[1]/li[2]/label/span')
    M39MW_option_pitch_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div/div/div[17]/div[2]/div[2]/ul[1]/li[1]/label/span')
    M39MW_option_vibration_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div/div/div[18]/div[2]/div[2]/ul[1]/li[2]/label/span')
    M39MW_option_vibration_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div/div/div[18]/div[2]/div[2]/ul[1]/li[1]/label/span')
    M39MW_option_airflow_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div/div/div[19]/div[2]/div[2]/ul[1]/li[2]/label/span')
    M39MW_option_airflow_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div/div/div[19]/div[2]/div[2]/ul[1]/li[1]/label/span')

    M48A2_ele_sup_volts_L12_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div[1]/div[1]/div/div/input')
    M48A2_ele_sup_volts_L23_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div[1]/div[2]/div/div/input')
    M48A2_ele_sup_volts_L31_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div[1]/div[3]/div/div/input')
    M48A2_ele_comp1_amps_L1_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div[2]/div[1]/div/div/input')
    M48A2_ele_comp1_amps_L2_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div[2]/div[2]/div/div/input')
    M48A2_ele_comp1_amps_L3_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div[2]/div[3]/div/div/input')
    M48A2_ele_comp2_amps_L1_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div[3]/div[1]/div/div/input')
    M48A2_ele_comp2_amps_L2_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div[3]/div[2]/div/div/input')
    M48A2_ele_comp2_amps_L3_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div[3]/div[3]/div/div/input')
    M48A2_ele_sup_fan_amps_SAV_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div[4]/div[1]/div/div/input')
    M48A2_ele_sup_fan_amps_VAV_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div[4]/div[2]/div/div/input')
    M48A2_ele_exh_fan_amps_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div[5]/div/div/div/input')
    M48A2_temp_out_air_temp_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[3]/div/div/div[1]/div/div/div/input')
    M48A2_temp_ret_air_temp1_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[3]/div/div/div[2]/div[1]/div/div/input')
    M48A2_temp_ret_air_temp2_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[3]/div/div/div[2]/div[2]/div/div/input')
    M48A2_temp_cool_sup_air_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[3]/div/div/div[3]/div/div/div/input')
    M48A2_temp_heat_sup_air_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[3]/div/div/div[4]/div/div/div/input')
    M48A2_temp_ele_sup_air_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[3]/div/div/div[5]/div/div/div/input')
    M48A2_pre_gas_inlet_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[4]/div/div/div[1]/div/div/div/input')
    M48A2_pre_gas_manifold1_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[4]/div/div/div[2]/div[1]/div/div/input')
    M48A2_pre_gas_manifold2_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[4]/div/div/div[2]/div[2]/div/div/input')
    M48A2_pre_gas_ref_suction1_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[4]/div/div/div[3]/div[1]/div/div/input')
    M48A2_pre_gas_ref_suction2_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[4]/div/div/div[3]/div[2]/div/div/input')
    M48A2_pre_gas_ref_dischrge1_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[4]/div/div/div[4]/div[1]/div/div/input')
    M48A2_pre_gas_ref_dischrge2_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[4]/div/div/div[4]/div[2]/div/div/input')
    M48A2_pre_gas_ref_chrge_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[4]/div/div/div[5]/div/div/div/div/div/div/div[3]/ul/li[2]/label/span')
    M48A2_pre_gas_ref_chrge_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[4]/div/div/div[5]/div/div/div/div/div/div/div[3]/ul/li[1]/label/span')

    M48A3_ele_sup_volts_L12_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div[1]/div[1]/div/div/input')
    M48A3_ele_sup_volts_L23_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div[1]/div[2]/div/div/input')
    M48A3_ele_sup_volts_L31_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div[1]/div[3]/div/div/input')
    M48A3_ele_comp1_amps_L1_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div[2]/div[1]/div/div/input')
    M48A3_ele_comp1_amps_L2_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div[2]/div[2]/div/div/input')
    M48A3_ele_comp1_amps_L3_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div[2]/div[3]/div/div/input')
    M48A3_ele_comp2_amps_L1_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div[3]/div[1]/div/div/input')
    M48A3_ele_comp2_amps_L2_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div[3]/div[2]/div/div/input')
    M48A3_ele_comp2_amps_L3_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div[3]/div[3]/div/div/input')
    M48A3_ele_sup_fan_amps_SAV_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div[4]/div[1]/div/div/input')
    M48A3_ele_sup_fan_amps_VAV_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div[4]/div[2]/div/div/input')
    M48A3_ele_exh_fan_amps_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div[5]/div/div/div/input')
    M48A3_temp_out_air_temp_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[3]/div/div/div[1]/div/div/div/input')
    M48A3_temp_ret_air_temp1_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[3]/div/div/div[2]/div[1]/div/div/input')
    M48A3_temp_ret_air_temp2_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[3]/div/div/div[2]/div[2]/div/div/input')
    M48A3_temp_cool_sup_air_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[3]/div/div/div[3]/div/div/div/input')
    M48A3_temp_heat_sup_air_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[3]/div/div/div[4]/div/div/div/input')
    M48A3_temp_ele_sup_air_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[3]/div/div/div[5]/div/div/div/input')
    M48A3_pre_gas_inlet_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[4]/div/div/div[1]/div/div/div/input')
    M48A3_pre_gas_manifold1_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[4]/div/div/div[2]/div[1]/div/div/input')
    M48A3_pre_gas_manifold2_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[4]/div/div/div[2]/div[2]/div/div/input')
    M48A3_pre_gas_ref_suction1_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[4]/div/div/div[3]/div[1]/div/div/input')
    M48A3_pre_gas_ref_suction2_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[4]/div/div/div[3]/div[2]/div/div/input')
    M48A3_pre_gas_ref_dischrge1_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[4]/div/div/div[4]/div[1]/div/div/input')
    M48A3_pre_gas_ref_dischrge2_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[4]/div/div/div[4]/div[2]/div/div/input')
    M48A3_pre_gas_ref_chrge_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[4]/div/div/div[5]/div/div/div/div/div/div/div[3]/ul/li[2]/label/span')
    M48A3_pre_gas_ref_chrge_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[4]/div/div/div[5]/div/div/div/div/div/div/div[3]/ul/li[1]/label/span')

    M50A3_ele_sup_volts_L12_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div[1]/div[1]/div/div/input')
    M50A3_ele_sup_volts_L23_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div[1]/div[2]/div/div/input')
    M50A3_ele_sup_volts_L31_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div[1]/div[3]/div/div/input')
    M50A3_ele_comp1_amps_L1_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div[2]/div[1]/div/div/input')
    M50A3_ele_comp1_amps_L2_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div[2]/div[2]/div/div/input')
    M50A3_ele_comp1_amps_L3_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div[2]/div[3]/div/div/input')
    M50A3_ele_comp2_amps_L1_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div[3]/div[1]/div/div/input')
    M50A3_ele_comp2_amps_L2_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div[3]/div[2]/div/div/input')
    M50A3_ele_comp2_amps_L3_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div[3]/div[3]/div/div/input')
    M50A3_ele_sup_fan_amps_SAV_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div[4]/div[1]/div/div/input')
    M50A3_ele_sup_fan_amps_VAV_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div[4]/div[2]/div/div/input')
    M50A3_ele_exh_fan_amps_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div[5]/div/div/div/input')
    M50A3_temp_out_air_temp_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[3]/div/div/div[1]/div/div/div/input')
    M50A3_temp_ret_air_temp1_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[3]/div/div/div[2]/div[1]/div/div/input')
    M50A3_temp_ret_air_temp2_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[3]/div/div/div[2]/div[2]/div/div/input')
    M50A3_temp_cool_sup_air_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[3]/div/div/div[3]/div/div/div/input')
    M50A3_temp_heat_sup_air_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[3]/div/div/div[4]/div/div/div/input')
    M50A3_temp_ele_sup_air_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[3]/div/div/div[5]/div/div/div/input')
    M50A3_pre_gas_inlet_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[4]/div/div/div[1]/div/div/div/input')
    M50A3_pre_gas_manifold1_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[4]/div/div/div[2]/div[1]/div/div/input')
    M50A3_pre_gas_manifold2_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[4]/div/div/div[2]/div[2]/div/div/input')
    M50A3_pre_gas_ref_suction1_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[4]/div/div/div[3]/div[1]/div/div/input')
    M50A3_pre_gas_ref_suction2_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[4]/div/div/div[3]/div[2]/div/div/input')
    M50A3_pre_gas_ref_dischrge1_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[4]/div/div/div[4]/div[1]/div/div/input')
    M50A3_pre_gas_ref_dischrge2_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[4]/div/div/div[4]/div[2]/div/div/input')
    M50A3_pre_gas_ref_chrge_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[4]/div/div/div[5]/div/div/div/div/div/div/div[3]/ul/li[2]/label/span')
    M50A3_pre_gas_ref_chrge_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[4]/div/div/div[5]/div/div/div/div/div/div/div[3]/ul/li[1]/label/span')

    M48HC_ele_sup_volts_L12_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div[1]/div[1]/div/div/input')
    M48HC_ele_sup_volts_L23_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div[1]/div[2]/div/div/input')
    M48HC_ele_sup_volts_L31_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div[1]/div[2]/div/div/input')
    M48HC_ele_comp1_amps_L1_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div[2]/div[1]/div/div/input')
    M48HC_ele_comp1_amps_L2_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div[2]/div[2]/div/div/input')
    M48HC_ele_comp1_amps_L3_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div[2]/div[3]/div/div/input')
    M48HC_ele_comp2_amps_L1_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div[3]/div[1]/div/div/input')
    M48HC_ele_comp2_amps_L2_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div[3]/div[2]/div/div/input')
    M48HC_ele_comp2_amps_L3_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div[3]/div[3]/div/div/input')
    M48HC_ele_infan_amps_L1_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div[4]/div[1]/div/div/input')
    M48HC_ele_infan_amps_L2_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div[4]/div[2]/div/div/input')
    M48HC_ele_infan_amps_L3_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div[4]/div[3]/div/div/input')
    M48HC_ele_outfan_amps_L1_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div[5]/div[1]/div/div/input')
    M48HC_ele_outfan_amps_L2_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div[5]/div[2]/div/div/input')
    M48HC_ele_outfan_amps_L3_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div[5]/div[3]/div/div/input')
    M48HC_pre_ret_static_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[3]/div/div/div[1]/div/div/div/input')
    M48HC_pre_sup_static_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[3]/div/div/div[2]/div/div/div/input')
    M48HC_pre_blower_rpm_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[3]/div/div/div[3]/div/div/div/input')
    M48HC_temp_outair_db_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[4]/div/div/div[1]/div[1]/div/div/input')
    M48HC_temp_outair_wb_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[4]/div/div/div[1]/div[2]/div/div/input')
    M48HC_temp_retair_db_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[4]/div/div/div[2]/div[1]/div/div/input')
    M48HC_temp_retair_wb_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[4]/div/div/div[2]/div[2]/div/div/input')
    M48HC_temp_coolair_db_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[4]/div/div/div[3]/div[1]/div/div/input')
    M48HC_temp_coolair_wb_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[4]/div/div/div[3]/div[2]/div/div/input')
    M48HC_temp_heatair_db_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[4]/div/div/div[4]/div/div/div/input')
    M48HC_pre_cm_inlet_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[5]/div/div/div[1]/div/div/div/input')
    M48HC_pre_cm_manifold_Low_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[5]/div/div/div[2]/div[1]/div/div/input')
    M48HC_pre_cm_manifold_Hi_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[5]/div/div/div[2]/div[2]/div/div/input')
    M48HC_pre_cm_ref_suct1_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[5]/div/div/div[3]/div[1]/div/div/input')
    M48HC_pre_cm_ref_suct1_temp_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[5]/div/div/div[3]/div[2]/div/div/input')
    M48HC_pre_cm_ref_suct2_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[5]/div/div/div[4]/div[1]/div/div/input')
    M48HC_pre_cm_ref_suct2_temp_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[5]/div/div/div[4]/div[2]/div/div/input')
    M48HC_pre_cm_dischrge1_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[5]/div/div/div[5]/div[1]/div/div/input')
    M48HC_pre_cm_dischrge1_temp_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[5]/div/div/div[5]/div[2]/div/div/input')
    M48HC_pre_cm_dischrge2_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[5]/div/div/div[6]/div[1]/div/div/input')
    M48HC_pre_cm_dischrge2_temp_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[5]/div/div/div[6]/div[2]/div/div/input')
    M48HC_pre_cm_blow_rotation_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[5]/div/div/div[7]/div/div/div/div/div/div/div[3]/ul/li[2]/label/span')
    M48HC_pre_cm_blow_rotation_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[5]/div/div/div[7]/div/div/div/div/div/div/div[3]/ul/li[1]/label/span')
    M48HC_pre_cm_comp_rotation_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[5]/div/div/div[8]/div/div/div/div/div/div/div[3]/ul/li[2]/label/span')
    M48HC_pre_cm_comp_rotation_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[5]/div/div/div[8]/div/div/div/div/div/div/div[3]/ul/li[1]/label/span')
    M48HC_pre_cm_ref_charge_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[5]/div/div/div[9]/div/div/div/div/div/div/div[3]/ul/li[2]/label/span')
    M48HC_pre_cm_ref_charge_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[5]/div/div/div[9]/div/div/div/div/div/div/div[3]/ul/li[1]/label/span')
    M48HC_pre_hp_ref_suctA_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[6]/div/div/div[1]/div[1]/div/div/input')
    M48HC_pre_hp_ref_suctB_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[6]/div/div/div[1]/div[2]/div/div/input')
    M48HC_pre_hp_ref_dischrgA_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[6]/div/div/div[2]/div[1]/div/div/input')
    M48HC_pre_hp_ref_dischrgB_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[6]/div/div/div[2]/div[2]/div/div/input')
    M48HC_pre_hp_ref_chrg_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[6]/div/div/div[3]/div/div/div/div/div/div/div[3]/ul/li[2]/label/span')
    M48HC_pre_hp_ref_chrg_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[6]/div/div/div[3]/div/div/div/div/div/div/div[3]/ul/li[1]/label/span')
    M48HC_pre_hp_ref_smoke_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[6]/div/div/div[4]/div/div/div/div/div/div/div[3]/ul/li[2]/label/span')
    M48HC_pre_hp_ref_smoke_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[6]/div/div/div[4]/div/div/div/div/div/div/div[3]/ul/li[1]/label/span')
    M48HC_gen_eco_min_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[7]/div/div/div/div/div/div/div/div/div/div[3]/ul/li[2]/label/span')
    M48HC_gen_eco_min_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[7]/div/div/div/div/div/div/div/div/div/div[3]/ul/li[1]/label/span')

    M48TC_ele_sup_volts_L12_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div[1]/div[1]/div/div/input')
    M48TC_ele_sup_volts_L23_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div[1]/div[2]/div/div/input')
    M48TC_ele_sup_volts_L31_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div[1]/div[2]/div/div/input')
    M48TC_ele_comp1_amps_L1_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div[2]/div[1]/div/div/input')
    M48TC_ele_comp1_amps_L2_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div[2]/div[2]/div/div/input')
    M48TC_ele_comp1_amps_L3_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div[2]/div[3]/div/div/input')
    M48TC_ele_comp2_amps_L1_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div[3]/div[1]/div/div/input')
    M48TC_ele_comp2_amps_L2_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div[3]/div[2]/div/div/input')
    M48TC_ele_comp2_amps_L3_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div[3]/div[3]/div/div/input')
    M48TC_ele_infan_amps_L1_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div[4]/div[1]/div/div/input')
    M48TC_ele_infan_amps_L2_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div[4]/div[2]/div/div/input')
    M48TC_ele_infan_amps_L3_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div[4]/div[3]/div/div/input')
    M48TC_ele_outfan_amps_L1_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div[5]/div[1]/div/div/input')
    M48TC_ele_outfan_amps_L2_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div[5]/div[2]/div/div/input')
    M48TC_ele_outfan_amps_L3_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div[5]/div[3]/div/div/input')
    M48TC_pre_ret_static_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[3]/div/div/div[1]/div/div/div/input')
    M48TC_pre_sup_static_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[3]/div/div/div[2]/div/div/div/input')
    M48TC_pre_blower_rpm_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[3]/div/div/div[3]/div/div/div/input')
    M48TC_temp_outair_db_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[4]/div/div/div[1]/div[1]/div/div/input')
    M48TC_temp_outair_wb_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[4]/div/div/div[1]/div[2]/div/div/input')
    M48TC_temp_retair_db_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[4]/div/div/div[2]/div[1]/div/div/input')
    M48TC_temp_retair_wb_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[4]/div/div/div[2]/div[2]/div/div/input')
    M48TC_temp_coolair_db_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[4]/div/div/div[3]/div[1]/div/div/input')
    M48TC_temp_coolair_wb_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[4]/div/div/div[3]/div[2]/div/div/input')
    M48TC_temp_heatair_db_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[4]/div/div/div[4]/div/div/div/input')
    M48TC_pre_cm_inlet_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[5]/div/div/div[1]/div/div/div/input')
    M48TC_pre_cm_manifold_Low_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[5]/div/div/div[2]/div[1]/div/div/input')
    M48TC_pre_cm_manifold_Hi_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[5]/div/div/div[2]/div[2]/div/div/input')
    M48TC_pre_cm_ref_suct1_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[5]/div/div/div[3]/div[1]/div/div/input')
    M48TC_pre_cm_ref_suct1_temp_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[5]/div/div/div[3]/div[2]/div/div/input')
    M48TC_pre_cm_ref_suct2_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[5]/div/div/div[4]/div[1]/div/div/input')
    M48TC_pre_cm_ref_suct2_temp_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[5]/div/div/div[4]/div[2]/div/div/input')
    M48TC_pre_cm_dischrge1_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[5]/div/div/div[5]/div[1]/div/div/input')
    M48TC_pre_cm_dischrge1_temp_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[5]/div/div/div[5]/div[2]/div/div/input')
    M48TC_pre_cm_dischrge2_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[5]/div/div/div[6]/div[1]/div/div/input')
    M48TC_pre_cm_dischrge2_temp_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[5]/div/div/div[6]/div[2]/div/div/input')
    M48TC_pre_cm_blow_rotation_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[5]/div/div/div[7]/div/div/div/div/div/div/div[3]/ul/li[2]/label/span')
    M48TC_pre_cm_blow_rotation_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[5]/div/div/div[7]/div/div/div/div/div/div/div[3]/ul/li[1]/label/span')
    M48TC_pre_cm_comp_rotation_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[5]/div/div/div[8]/div/div/div/div/div/div/div[3]/ul/li[2]/label/span')
    M48TC_pre_cm_comp_rotation_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[5]/div/div/div[8]/div/div/div/div/div/div/div[3]/ul/li[1]/label/span')
    M48TC_pre_cm_ref_charge_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[5]/div/div/div[9]/div/div/div/div/div/div/div[3]/ul/li[2]/label/span')
    M48TC_pre_cm_ref_charge_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[5]/div/div/div[9]/div/div/div/div/div/div/div[3]/ul/li[1]/label/span')
    M48TC_pre_hp_ref_suctA_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[6]/div/div/div[1]/div[1]/div/div/input')
    M48TC_pre_hp_ref_suctB_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[6]/div/div/div[1]/div[2]/div/div/input')
    M48TC_pre_hp_ref_dischrgA_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[6]/div/div/div[2]/div[1]/div/div/input')
    M48TC_pre_hp_ref_dischrgB_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[6]/div/div/div[2]/div[2]/div/div/input')
    M48TC_pre_hp_ref_chrg_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[6]/div/div/div[3]/div/div/div/div/div/div/div[3]/ul/li[2]/label/span')
    M48TC_pre_hp_ref_chrg_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[6]/div/div/div[3]/div/div/div/div/div/div/div[3]/ul/li[1]/label/span')
    M48TC_pre_hp_ref_smoke_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[6]/div/div/div[4]/div/div/div/div/div/div/div[3]/ul/li[2]/label/span')
    M48TC_pre_hp_ref_smoke_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[6]/div/div/div[4]/div/div/div/div/div/div/div[3]/ul/li[1]/label/span')
    M48TC_gen_eco_min_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[7]/div/div/div/div/div/div/div/div/div/div[3]/ul/li[2]/label/span')
    M48TC_gen_eco_min_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[7]/div/div/div/div/div/div/div/div/div/div[3]/ul/li[1]/label/span')

    M48LC_ele_sup_volts_L12_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div[1]/div[1]/div/div/input')
    M48LC_ele_sup_volts_L23_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div[1]/div[2]/div/div/input')
    M48LC_ele_sup_volts_L31_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div[1]/div[2]/div/div/input')
    M48LC_ele_comp1_amps_L1_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div[2]/div[1]/div/div/input')
    M48LC_ele_comp1_amps_L2_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div[2]/div[2]/div/div/input')
    M48LC_ele_comp1_amps_L3_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div[2]/div[3]/div/div/input')
    M48LC_ele_comp2_amps_L1_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div[3]/div[1]/div/div/input')
    M48LC_ele_comp2_amps_L2_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div[3]/div[2]/div/div/input')
    M48LC_ele_comp2_amps_L3_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div[3]/div[3]/div/div/input')
    M48LC_ele_infan_amps_L1_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div[4]/div[1]/div/div/input')
    M48LC_ele_infan_amps_L2_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div[4]/div[2]/div/div/input')
    M48LC_ele_infan_amps_L3_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div[4]/div[3]/div/div/input')
    M48LC_temp_outair_db_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[3]/div/div/div[1]/div/div/div/input')
    M48LC_temp_retair_db_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[3]/div/div/div[2]/div[1]/div/div/input')
    M48LC_temp_retair_wb_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[3]/div/div/div[2]/div[2]/div/div/input')
    M48LC_temp_coolair_db_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[3]/div/div/div[3]/div/div/div/input')
    M48LC_temp_heatair_db_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[3]/div/div/div[4]/div/div/div/input')
    M48LC_pre_inlet_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[4]/div/div/div[1]/div/div/div/input')
    M48LC_pre_manifold1_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[4]/div/div/div[2]/div[1]/div/div/input')
    M48LC_pre_manifold2_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[4]/div/div/div[2]/div[2]/div/div/input')
    M48LC_pre_ref_suctA_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[4]/div/div/div[3]/div[1]/div/div/input')
    M48LC_pre_ref_suctB_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[4]/div/div/div[3]/div[2]/div/div/input')
    M48LC_pre_dischrgeA_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[4]/div/div/div[4]/div[1]/div/div/input')
    M48LC_pre_dischrgeB_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[4]/div/div/div[4]/div[2]/div/div/input')
    M48LC_pre_ref_charge_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[4]/div/div/div[5]/div/div/div/div/div/div/div[3]/ul/li[2]/label/span')
    M48LC_pre_ref_charge_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[4]/div/div/div[5]/div/div/div/div/div/div/div[3]/ul/li[1]/label/span')
    M48LC_gen_eco_min_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[5]/div/div/div/div[1]/div/div/div/div/div/div[3]/ul/li[2]/label/span')
    M48LC_gen_eco_min_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[5]/div/div/div/div[1]/div/div/div/div/div/div[3]/ul/li[1]/label/span')
    M48LC_gen_smoke_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[5]/div/div/div/div[2]/div/div/div/div/div/div[3]/ul/li[2]/label/span')
    M48LC_gen_smoke_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[5]/div/div/div/div[2]/div/div/div/div/div/div[3]/ul/li[1]/label/span')

    M50HC_ele_sup_volts_L12_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div[1]/div[1]/div/div/input')
    M50HC_ele_sup_volts_L23_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div[1]/div[2]/div/div/input')
    M50HC_ele_sup_volts_L31_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div[1]/div[3]/div/div/input')
    M50HC_ele_comp_amps_L1_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div[2]/div[1]/div/div/input')
    M50HC_ele_comp_amps_L2_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div[2]/div[2]/div/div/input')
    M50HC_ele_comp_amps_L3_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div[2]/div[3]/div/div/input')
    M50HC_ele_fan_amps_L1_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div[3]/div[1]/div/div/input')
    M50HC_ele_fan_amps_L2_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div[3]/div[2]/div/div/input')
    M50HC_ele_fan_amps_L3_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div[3]/div[3]/div/div/input')
    M50HC_temp_outair_db_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[3]/div/div/div[1]/div[1]/div/div/input')
    M50HC_temp_outair_wb_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[3]/div/div/div[1]/div[2]/div/div/input')
    M50HC_temp_retair_db_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[3]/div/div/div[2]/div[1]/div/div/input')
    M50HC_temp_retair_wb_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[3]/div/div/div[2]/div[2]/div/div/input')
    M50HC_temp_coolair_db_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[3]/div/div/div[3]/div[1]/div/div/input')
    M50HC_temp_coolair_wb_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[3]/div/div/div[3]/div[2]/div/div/input')
    M50HC_temp_heatair_db_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[3]/div/div/div[4]/div/div/div/input')
    M50HC_pre_inlet_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[4]/div/div/div[1]/div/div/div/input')
    M50HC_pre_manifold_low_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[4]/div/div/div[2]/div[1]/div/div/input')
    M50HC_pre_manifold_hi_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[4]/div/div/div[2]/div[2]/div/div/input')
    M50HC_pre_ref_suct_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[4]/div/div/div[3]/div[1]/div/div/input')
    M50HC_pre_ref_suct_temp_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[4]/div/div/div[3]/div[2]/div/div/input')
    M50HC_pre_ref_dischrg_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[4]/div/div/div[4]/div[1]/div/div/input')
    M50HC_pre_ref_dischrg_temp_05 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[4]/div/div/div[4]/div[2]/div/div/input')
    M50HC_pre_ref_chrg_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[4]/div/div/div[5]/div/div/div/div/div/div/div[3]/ul/li[2]/label/span')
    M50HC_pre_ref_chrg_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[4]/div/div/div[5]/div/div/div/div/div/div/div[3]/ul/li[1]/label/span')
    M50HC_pre_ref_rot_direction_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[4]/div/div/div[6]/div/div/div/div/div/div/div[3]/ul/li[2]/label/span')
    M50HC_pre_ref_rot_direction_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[4]/div/div/div[6]/div/div/div/div/div/div/div[3]/ul/li[1]/label/span')
    M50HC_pre_smoke_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[4]/div/div/div[7]/div/div/div/div/div/div/div[3]/ul/li[2]/label/span')
    M50HC_pre_smoke_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[4]/div/div/div[7]/div/div/div/div/div/div/div[3]/ul/li[1]/label/span')

    M50PCPS_fan_comp_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div/div/div[1]/div[2]/div[2]/ul[1]/li[2]/label/span')
    M50PCPS_fan_comp_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div/div/div[1]/div[2]/div[2]/ul[1]/li[1]/label/span')
    M50PCPS_rotation_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div/div/div[2]/div[2]/div[2]/ul[1]/li[2]/label/span')
    M50PCPS_rotation_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div/div/div[2]/div[2]/div[2]/ul[1]/li[1]/label/span')
    M50PCPS_Default = (By.XPATH, '//*[@id="a"]')
    M50PCPS_unit_AB1_05 = 16
    M50PCPS_unit_BC1_05 = 17
    M50PCPS_unit_CA1_05 = 18
    M50PCPS_unit_AB2_05 = 19
    M50PCPS_unit_BC2_05 = 20
    M50PCPS_unit_CA2_05 = 21
    M50PCPS_control_volt_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[4]/div/div/div/div/div[1]/div[2]/div[2]/ul[1]/li[2]/label/span')
    M50PCPS_control_volt_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div/div[4]/div/div/div/div/div[1]/div[2]/div[2]/ul[1]/li[1]/label/span')
    M50PCPS_coaxial_cc_liq_line_05 = 24
    M50PCPS_coaxial_cc_fluid_in_05 = 25
    M50PCPS_coaxial_cc_fluid_out_05 = 26
    M50PCPS_coaxial_cc_press_in_05 = 27
    M50PCPS_coaxial_cc_press_out_05 = 28
    M50PCPS_coaxial_cc_flow_rate_05 = 29
    M50PCPS_coaxial_hc_liq_line_05 = 30
    M50PCPS_coaxial_hc_fluid_in_05 = 31
    M50PCPS_coaxial_hc_fluid_out_05 = 32
    M50PCPS_coaxial_hc_press_in_05 = 33
    M50PCPS_coaxial_hc_press_out_05 = 34
    M50PCPS_coaxial_hc_flow_rate_05 = 35
    M50PCPS_coil_cc_air_in_05 = 36
    M50PCPS_coil_cc_air_out_05 = 37
    M50PCPS_coil_hc_air_in_05 = 38
    M50PCPS_coil_hc_air_out_05 = 39
    M50PCPS_flow_rate_05 = 40
    M50PCPS_temp_diff_05 = 41
    M50PCPS_fluid_fac_05 = 42
    M50PCPS_suct_temp_05 = 43
    M50PCPS_suct_sat_temp_05 = 44
    M50PCPS_super_heat_05 = 45
    M50PCPS_dischrg_suct_temp_05 = 46
    M50PCPS_liq_line_temp_05 = 47
    M50PCPS_subcool_05 = 48
