from selenium.webdriver.common.by import By


class PostStartPageLocators(object):
    poststart = (By.XPATH, '//*[@id="tabdivisonsid"]/ul/li/a/span[1]/i')
    poststart_filled = (By.XPATH, '//*[@id="tabdivisonsid"]/ul/li/a/span[2]/i')
    poststart_reset = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[1]/ul/li[2]/a')
    poststart_exit = (By.XPATH, '//*[@id="aExistingForm"]/i')
    poststart_save = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[4]/ul/li[2]/a')
    poststart_cancel = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[4]/ul/li[1]/a')
    save_form = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[4]/ul/li[2]/a')
    save_form_popup = (By.XPATH, '//*[@id="AlmostDoneModal"]/div/div/div/form/div[3]/div/button')
    save_form_close_X = (By.XPATH, '//*[@id="SavedSuccessfullyModel"]/div/div/a')

    M16JB_JT_Default = (By.XPATH, '//*[@id="a"]')
    M16JB_JT_under_control_section_txt = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[4]/div[2]/div/div/div/div[2]/div/div/div/div[1]/div[2]')
    M16JB_JT_under_control_section_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[4]/div[2]/div/div/div/div[2]/div/div/div/div[1]/div[3]/ul/li[2]/label/span')
    M16JB_JT_under_control_section_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[4]/div[2]/div/div/div/div[2]/div/div/div/div[1]/div[3]/ul/li[1]/label/span')
    M16JB_JT_readings_records_txt = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[4]/div[2]/div/div/div/div[2]/div/div/div/div[2]/div[2]')
    M16JB_JT_readings_records_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[4]/div[2]/div/div/div/div[2]/div/div/div/div[2]/div[3]/ul/li[2]/label/span')
    M16JB_JT_readings_records_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[4]/div[2]/div/div/div/div[2]/div/div/div/div[2]/div[3]/ul/li[1]/label/span')
    M16JB_JT_add_alochol_txt = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[4]/div[2]/div/div/div/div[2]/div/div/div/div[3]/div[2]')
    M16JB_JT_add_alochol_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[4]/div[2]/div/div/div/div[2]/div/div/div/div[3]/div[3]/ul/li[2]/label/span')
    M16JB_JT_add_alochol_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[4]/div[2]/div/div/div/div[2]/div/div/div/div[3]/div[3]/ul/li[1]/label/span')
    M16JB_JT_chiller_startup_txt = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[4]/div[2]/div/div/div/div[2]/div/div/div/div[5]/div[2]')
    M16JB_JT_chiller_startup_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[4]/div[2]/div/div/div/div[2]/div/div/div/div[5]/div[3]/ul/li[2]/label/span')
    M16JB_JT_chiller_startup_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[4]/div[2]/div/div/div/div[2]/div/div/div/div[5]/div[3]/ul/li[1]/label/span')
    M16JB_JT_operating_hrs_txt = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[4]/div[2]/div/div/div/div[2]/div/div/div/div[4]/div[2]')
    M16JB_JT_operating_hrs = 65

    M17DA_Default = (By.XPATH, '//*[@id="a"]')
    M17DA_trim_charge_txt = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[1]/div[2]')
    M17DA_trim_charge_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[1]/div[3]/ul/li[2]/label/span')
    M17DA_trim_charge_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[1]/div[3]/ul/li[1]/label/span')
    M17DA_control_txt = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[3]/div[2]')
    M17DA_control_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[3]/div[3]/ul/li[2]/label/span')
    M17DA_control_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[3]/div[3]/ul/li[1]/label/span')
    M17DA_readings_txt = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[4]/div[2]')
    M17DA_readings_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[4]/div[3]/ul/li[2]/label/span')
    M17DA_readings_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[4]/div[3]/ul/li[1]/label/span')
    M17DA_shutdown_txt = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[5]/div[2]')
    M17DA_shutdown_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[5]/div[3]/ul/li[2]/label/span')
    M17DA_shutdown_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[5]/div[3]/ul/li[1]/label/span')
    M17DA_instructions_txt = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[6]/div[2]')
    M17DA_instructions_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[6]/div[3]/ul/li[2]/label/span')
    M17DA_instructions_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[6]/div[3]/ul/li[1]/label/span')
    M17DA_factory_txt = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[8]/div[2]')
    M17DA_factory_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[8]/div[3]/ul/li[2]/label/span')
    M17DA_factory_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[8]/div[3]/ul/li[1]/label/span')
    M17DA_final_charge_txt = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[2]/div[2]')
    M17DA_final_charge = 64
    M17DA_hours_txt = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[7]/div[2]')
    M17DA_hours = 73

    M19PIC6_Default = (By.XPATH, '//*[@id="a"]')
    M19PIC6_trim_charge_txt = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[1]/div[2]')
    M19PIC6_trim_charge_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[1]/div[3]/ul/li[2]/label/span')
    M19PIC6_trim_charge_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[1]/div[3]/ul/li[1]/label/span')
    M19PIC6_control_txt = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[3]/div[2]')
    M19PIC6_control_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[3]/div[3]/ul/li[2]/label/span')
    M19PIC6_control_no = (By.XPATH,  '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[3]/div[3]/ul/li[1]/label/span')
    M19PIC6_readings_txt = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[4]/div[2]')
    M19PIC6_readings_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[4]/div[3]/ul/li[2]/label/span')
    M19PIC6_readings_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[4]/div[3]/ul/li[1]/label/span')
    M19PIC6_shutdown_txt = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[5]/div[2]')
    M19PIC6_shutdown_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[5]/div[3]/ul/li[2]/label/span')
    M19PIC6_shutdown_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[5]/div[3]/ul/li[1]/label/span')
    M19PIC6_instructions_txt = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[6]/div[2]')
    M19PIC6_instructions_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[6]/div[3]/ul/li[2]/label/span')
    M19PIC6_instructions_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[6]/div[3]/ul/li[1]/label/span')
    M19PIC6_factory_txt = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[8]/div[2]')
    M19PIC6_factory_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[8]/div[3]/ul/li[2]/label/span')
    M19PIC6_factory_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[8]/div[3]/ul/li[1]/label/span')
    M19PIC6_final_charge_txt = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[2]/div[2]')
    M19PIC6_final_charge = 69
    M19PIC6_hours_txt = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[7]/div[2]')
    M19PIC6_hours = 78

    M19XL_Default = (By.XPATH, '//*[@id="a"]')
    M19XL_trim_charge_txt = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[1]/div[2]')
    M19XL_trim_charge_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[1]/div[3]/ul/li[2]/label/span')
    M19XL_trim_charge_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[1]/div[3]/ul/li[1]/label/span')
    M19XL_control_txt = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[2]/div[2]')
    M19XL_control_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[2]/div[3]/ul/li[2]/label/span')
    M19XL_control_no = (By.XPATH,  '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[2]/div[3]/ul/li[1]/label/span')
    M19XL_readings_txt = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[3]/div[2]')
    M19XL_readings_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[3]/div[3]/ul/li[2]/label/span')
    M19XL_readings_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[3]/div[3]/ul/li[1]/label/span')
    M19XL_shutdown_txt = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[4]/div[2]')
    M19XL_shutdown_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[4]/div[3]/ul/li[2]/label/span')
    M19XL_shutdown_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[4]/div[3]/ul/li[1]/label/span')
    M19XL_factory_txt = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[6]/div[2]')
    M19XL_factory_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[6]/div[3]/ul/li[2]/label/span')
    M19XL_factory_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[6]/div[3]/ul/li[1]/label/span')
    M19XL_hours_txt = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[5]/div[2]')
    M19XL_hours = 78

    M19XR_Default = (By.XPATH, '//*[@id="a"]')
    M19XR_trim_charge_txt = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[1]/div[2]')
    M19XR_trim_charge_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[1]/div[3]/ul/li[2]/label/span')
    M19XR_trim_charge_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[1]/div[3]/ul/li[1]/label/span')
    M19XR_control_txt = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[3]/div[2]')
    M19XR_control_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[3]/div[3]/ul/li[2]/label/span')
    M19XR_control_no = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[3]/div[3]/ul/li[1]/label/span')
    M19XR_readings_txt = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[4]/div[2]')
    M19XR_readings_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[4]/div[3]/ul/li[2]/label/span')
    M19XR_readings_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[4]/div[3]/ul/li[1]/label/span')
    M19XR_shutdown_txt = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[5]/div[2]')
    M19XR_shutdown_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[5]/div[3]/ul/li[2]/label/span')
    M19XR_shutdown_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[5]/div[3]/ul/li[1]/label/span')
    M19XR_instructions_txt = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[6]/div[2]')
    M19XR_instructions_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[6]/div[3]/ul/li[2]/label/span')
    M19XR_instructions_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[6]/div[3]/ul/li[1]/label/span')
    M19XR_factory_txt = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[8]/div[2]')
    M19XR_factory_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[8]/div[3]/ul/li[2]/label/span')
    M19XR_factory_no = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[8]/div[3]/ul/li[1]/label/span')
    M19XR_final_charge_txt = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[2]/div[2]')
    M19XR_final_charge = 64
    M19XR_hours_txt = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[7]/div[2]')
    M19XR_hours = 73

    M19XRD_Default = (By.XPATH, '//*[@id="a"]')
    M19XRD_trim_charge_txt = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[1]/div[2]')
    M19XRD_trim_charge_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[1]/div[3]/ul/li[2]/label/span')
    M19XRD_trim_charge_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[1]/div[3]/ul/li[1]/label/span')
    M19XRD_control_txt = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[3]/div[2]')
    M19XRD_control_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[3]/div[3]/ul/li[2]/label/span')
    M19XRD_control_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[3]/div[3]/ul/li[1]/label/span')
    M19XRD_readings_txt = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[4]/div[2]')
    M19XRD_readings_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[4]/div[3]/ul/li[2]/label/span')
    M19XRD_readings_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[4]/div[3]/ul/li[1]/label/span')
    M19XRD_shutdown_txt = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[5]/div[2]')
    M19XRD_shutdown_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[5]/div[3]/ul/li[2]/label/span')
    M19XRD_shutdown_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[5]/div[3]/ul/li[1]/label/span')
    M19XRD_instructions_txt = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[6]/div[2]')
    M19XRD_instructions_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[6]/div[3]/ul/li[2]/label/span')
    M19XRD_instructions_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[6]/div[3]/ul/li[1]/label/span')
    M19XRD_factory_txt = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[8]/div[2]')
    M19XRD_factory_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[8]/div[3]/ul/li[2]/label/span')
    M19XRD_factory_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[8]/div[3]/ul/li[1]/label/span')
    M19XRD_final_charge_txt = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[2]/div[2]')
    M19XRD_final_charge = 64
    M19XRD_hours_txt = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[7]/div[2]')
    M19XRD_hours = 73

    M19XRE_Default = (By.XPATH, '//*[@id="a"]')
    M19XRE_trim_charge_txt = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[1]/div[2]')
    M19XRE_trim_charge_yes = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[1]/div[3]/ul/li[2]/label/span')
    M19XRE_trim_charge_no = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[1]/div[3]/ul/li[1]/label/span')
    M19XRE_control_txt = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[3]/div[2]')
    M19XRE_control_yes = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[3]/div[3]/ul/li[2]/label/span')
    M19XRE_control_no = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[3]/div[3]/ul/li[1]/label/span')
    M19XRE_readings_txt = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[4]/div[2]')
    M19XRE_readings_yes = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[4]/div[3]/ul/li[2]/label/span')
    M19XRE_readings_no = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[4]/div[3]/ul/li[1]/label/span')
    M19XRE_shutdown_txt = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[5]/div[2]')
    M19XRE_shutdown_yes = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[5]/div[3]/ul/li[2]/label/span')
    M19XRE_shutdown_no = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[5]/div[3]/ul/li[1]/label/span')
    M19XRE_instructions_txt = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[6]/div[2]')
    M19XRE_instructions_yes = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[6]/div[3]/ul/li[2]/label/span')
    M19XRE_instructions_no = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[6]/div[3]/ul/li[1]/label/span')
    M19XRE_factory_txt = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[8]/div[2]')
    M19XRE_factory_yes = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[8]/div[3]/ul/li[2]/label/span')
    M19XRE_factory_no = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[8]/div[3]/ul/li[1]/label/span')
    M19XRE_final_charge_txt = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[2]/div[2]')
    M19XRE_final_charge = 64
    M19XRE_hours_txt = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[7]/div[2]')
    M19XRE_hours = 73

    M19XRPIC5_Default = (By.XPATH, '//*[@id="a"]')
    M19XRPIC5_trim_charge_txt = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[1]/div[2]')
    M19XRPIC5_trim_charge_yes = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[1]/div[3]/ul/li[2]/label/span')
    M19XRPIC5_trim_charge_no = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[1]/div[3]/ul/li[1]/label/span')
    M19XRPIC5_control_txt = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[3]/div[2]')
    M19XRPIC5_control_yes = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[3]/div[3]/ul/li[2]/label/span')
    M19XRPIC5_control_no = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[3]/div[3]/ul/li[1]/label/span')
    M19XRPIC5_readings_txt = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[4]/div[2]')
    M19XRPIC5_readings_yes = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[4]/div[3]/ul/li[2]/label/span')
    M19XRPIC5_readings_no = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[4]/div[3]/ul/li[1]/label/span')
    M19XRPIC5_shutdown_txt = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[5]/div[2]')
    M19XRPIC5_shutdown_yes = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[5]/div[3]/ul/li[2]/label/span')
    M19XRPIC5_shutdown_no = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[5]/div[3]/ul/li[1]/label/span')
    M19XRPIC5_instructions_txt = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[6]/div[2]')
    M19XRPIC5_instructions_yes = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[6]/div[3]/ul/li[2]/label/span')
    M19XRPIC5_instructions_no = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[6]/div[3]/ul/li[1]/label/span')
    M19XRPIC5_factory_txt = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[8]/div[2]')
    M19XRPIC5_factory_yes = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[8]/div[3]/ul/li[2]/label/span')
    M19XRPIC5_factory_no = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[8]/div[3]/ul/li[1]/label/span')
    M19XRPIC5_final_charge_txt = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[2]/div[2]')
    M19XRPIC5_final_charge = 69
    M19XRPIC5_hours_txt = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[7]/div[2]')
    M19XRPIC5_hours = 78

    M19XRV_Default = (By.XPATH, '//*[@id="a"]')
    M19XRV_trim_charge_txt = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[1]/div[2]')
    M19XRV_trim_charge_yes = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[1]/div[3]/ul/li[2]/label/span')
    M19XRV_trim_charge_no = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[1]/div[3]/ul/li[1]/label/span')
    M19XRV_control_txt = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[3]/div[2]')
    M19XRV_control_yes = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[3]/div[3]/ul/li[2]/label/span')
    M19XRV_control_no = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[3]/div[3]/ul/li[1]/label/span')
    M19XRV_VFD_txt = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[4]/div[2]')
    M19XRV_VFD_yes = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[4]/div[3]/ul/li[2]/label/span')
    M19XRV_VFD_no = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[4]/div[3]/ul/li[1]/label/span')
    M19XRV_reading_txt = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[5]/div[2]')
    M19XRV_reading_yes = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[5]/div[3]/ul/li[2]/label/span')
    M19XRV_reading_no = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[5]/div[3]/ul/li[1]/label/span')
    M19XRV_shutdown_txt = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[6]/div[2]')
    M19XRV_shutdown_yes = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[6]/div[3]/ul/li[2]/label/span')
    M19XRV_shutdown_no = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[6]/div[3]/ul/li[1]/label/span')
    M19XRV_instructions_txt = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[7]/div[2]')
    M19XRV_instructions_yes = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[7]/div[3]/ul/li[2]/label/span')
    M19XRV_instructions_no = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[7]/div[3]/ul/li[1]/label/span')
    M19XRV_factory_txt = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[9]/div[2]')
    M19XRV_factory_yes = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[9]/div[3]/ul/li[2]/label/span')
    M19XRV_factory_no = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[9]/div[3]/ul/li[1]/label/span')
    M19XRV_final_charge_txt = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[2]/div[2]')
    M19XRV_final_charge = 64
    M19XRV_hours_txt = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[8]/div[2]')
    M19XRV_hours = 75

    M23XL_Default = (By.XPATH, '//*[@id="a"]')
    M23XL_trim_charge_txt = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[4]/div[2]/div/div/div/div[2]/div/div/div/div[1]/div[2]')
    M23XL_trim_charge_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[4]/div[2]/div/div/div/div[2]/div/div/div/div[1]/div[3]/ul/li[2]/label/span')
    M23XL_trim_charge_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[4]/div[2]/div/div/div/div[2]/div/div/div/div[1]/div[3]/ul/li[1]/label/span')
    M23XL_control_txt = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[4]/div[2]/div/div/div/div[2]/div/div/div/div[2]/div[2]')
    M23XL_control_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[4]/div[2]/div/div/div/div[2]/div/div/div/div[2]/div[3]/ul/li[2]/label/span')
    M23XL_control_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[4]/div[2]/div/div/div/div[2]/div/div/div/div[2]/div[3]/ul/li[1]/label/span')
    M23XL_readings_txt = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[4]/div[2]/div/div/div/div[2]/div/div/div/div[3]/div[2]')
    M23XL_readings_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[4]/div[2]/div/div/div/div[2]/div/div/div/div[3]/div[3]/ul/li[2]/label/span')
    M23XL_readings_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[4]/div[2]/div/div/div/div[2]/div/div/div/div[3]/div[3]/ul/li[1]/label/span')
    M23XL_shutdown_txt = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[4]/div[2]/div/div/div/div[2]/div/div/div/div[4]/div[2]')
    M23XL_shutdown_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[4]/div[2]/div/div/div/div[2]/div/div/div/div[4]/div[3]/ul/li[2]/label/span')
    M23XL_shutdown_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[4]/div[2]/div/div/div/div[2]/div/div/div/div[4]/div[3]/ul/li[1]/label/span')
    M23XL_instructions_txt = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[4]/div[2]/div/div/div/div[2]/div/div/div/div[5]/div[2]')
    M23XL_instructions = 72
    M23XL_factory_txt = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[4]/div[2]/div/div/div/div[2]/div/div/div/div[6]/div[2]')
    M23XL_factory_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[4]/div[2]/div/div/div/div[2]/div/div/div/div[6]/div[3]/ul/li[2]/label/span')
    M23XL_factory_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[4]/div[2]/div/div/div/div[2]/div/div/div/div[6]/div[3]/ul/li[1]/label/span')

    M23XRV_Default = (By.XPATH, '//*[@id="a"]')
    M23XRV_trim_charge_txt = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[1]/div[2]')
    M23XRV_trim_charge_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[1]/div[3]/ul/li[2]/label/span')
    M23XRV_trim_charge_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[1]/div[3]/ul/li[1]/label/span')
    M23XRV_inspect_txt = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[3]/div[2]')
    M23XRV_inspect_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[3]/div[3]/ul/li[2]/label/span')
    M23XRV_inspect_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[3]/div[3]/ul/li[1]/label/span')
    M23XRV_control_txt = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[4]/div[2]')
    M23XRV_control_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[4]/div[3]/ul/li[2]/label/span')
    M23XRV_control_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[4]/div[3]/ul/li[1]/label/span')
    M23XRV_readings_txt = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[5]/div[2]')
    M23XRV_readings_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[5]/div[3]/ul/li[2]/label/span')
    M23XRV_readings_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[5]/div[3]/ul/li[1]/label/span')
    M23XRV_shutdown_txt = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[6]/div[2]')
    M23XRV_shutdown_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[6]/div[3]/ul/li[2]/label/span')
    M23XRV_shutdown_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[6]/div[3]/ul/li[1]/label/span')
    M23XRV_factory_txt = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[8]/div[2]')
    M23XRV_factory_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[8]/div[3]/ul/li[2]/label/span')
    M23XRV_factory_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[8]/div[3]/ul/li[1]/label/span')
    M23XRV_rockwell_txt = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[9]/div[2]')
    M23XRV_rockwell_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[9]/div[3]/ul/li[2]/label/span')
    M23XRV_rockwell_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[9]/div[3]/ul/li[1]/label/span')
    M23XRV_email_txt = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[10]/div[2]')
    M23XRV_email_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[10]/div[3]/ul/li[2]/label/span')
    M23XRV_email_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[10]/div[3]/ul/li[1]/label/span')
    M23XRV_final_charge_txt = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[2]/div[2]')
    M23XRV_final_charge = 99
    M23XRV_hours_txt = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[7]/div[2]')
    M23XRV_hours = 108

    M32XR_Default = (By.XPATH, '//*[@id="a"]')
    M32XR_trim_charge_txt = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[1]/div[2]')
    M32XR_trim_charge_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[1]/div[3]/ul/li[2]/label/span')
    M32XR_trim_charge_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[1]/div[3]/ul/li[1]/label/span')
    M32XR_control_txt = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[2]/div[2]')
    M32XR_control_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[2]/div[3]/ul/li[2]/label/span')
    M32XR_control_no = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[2]/div[3]/ul/li[1]/label/span')
    M32XR_vfd_txt = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[3]/div[2]')
    M32XR_vfd_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[3]/div[3]/ul/li[2]/label/span')
    M32XR_vfd_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[3]/div[3]/ul/li[1]/label/span')
    M32XR_readings_txt = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[4]/div[2]')
    M32XR_readings_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[4]/div[3]/ul/li[2]/label/span')
    M32XR_readings_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[4]/div[3]/ul/li[1]/label/span')
    M32XR_shutdown_txt = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[5]/div[2]')
    M32XR_shutdown_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[5]/div[3]/ul/li[2]/label/span')
    M32XR_shutdown_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[5]/div[3]/ul/li[1]/label/span')
    M32XR_instructions_txt = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[6]/div[2]')
    M32XR_instructions_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[6]/div[3]/ul/li[2]/label/span')
    M32XR_instructions_no = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[6]/div[3]/ul/li[1]/label/span')
    M32XR_factory_txt = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[8]/div[2]')
    M32XR_factory_yes = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[8]/div[3]/ul/li[2]/label/span')
    M32XR_factory_no = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[8]/div[3]/ul/li[1]/label/span')
    M32XR_final_charge_txt = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[3]/div[5]/div[2]/div/div/div/div[2]/div/div/div/div[7]/div[2]')
    M32XR_final_charge = 85
