from selenium.webdriver.common.by import By


class ESHFormPageLocators(object):
    ESHchecklist = (By.XPATH, '//*[@id="content"]/div/div[1]/div[2]/div[2]/div[2]')
    ehs_form = (By.XPATH, '//*[@id="EHSForm"]')
    create_new_form_text = (By.XPATH, '//*[@id="content"]/div/div[2]/ng-include[2]/div/div[2]/h1')
    new_form = (By.XPATH, '//*[@id="content"]/div/div[1]/div/div[1]/ul/li[2]')
    startup_form = (By.XPATH, '//*[@id="StartUpForm"]')
    create_form = (By.XPATH, '//*[@id="Create"]')
    job_name = (By.XPATH, '//*[@id="content"]/div/div[2]/ng-include[2]/div/div[3]/form/div[1]/div[1]/ul[1]/li[1]/div/input')
    job_no = (By.XPATH, '//*[@id="content"]/div/div[2]/ng-include[2]/div/div[3]/form/div[1]/div[1]/ul[1]/li[2]/div/input')
    cust_name = (By.XPATH, '//*[@id="content"]/div/div[2]/ng-include[2]/div/div[3]/form/div[1]/div[1]/ul[1]/li['
                           '4]/div/input')
    address = (By.XPATH, '//*[@id="content"]/div/div[2]/ng-include[2]/div/div[3]/form/div[1]/div[1]/ul[2]/li['
                         '1]/div/textarea')
    serial_no = (By.XPATH, '//*[@id="content"]/div/div[2]/ng-include[2]/div/div[3]/form/div[1]/div[1]/ul[1]/li['
                           '5]/div/input')
    model_no = (By.XPATH,'//*[@id="content"]/div/div[2]/ng-include[2]/div/div[3]/form/div[1]/div[1]/ul[1]/li['
                          '3]/div/div/div/button')
    model_no_dropdown = (By.XPATH, '//*[@id="content"]/div[1]/div[2]/ng-include[2]/div[1]/div[3]/form[1]/div[1]/div[1]/ul[1]/li[3]/div[1]/div[1]/div[1]/ul[1]')
    cancel = (By.XPATH, '//*[@id="content"]/div[3]/ul/li[3]/label/span')

    save_form = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list/ng-include/div/div[2]/form/div/ul/li[3]/input')
    save_form_2_old = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[3]/div/div[2]/form/div/div[4]/ul/li[2]/a')
    save_form_2 = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[4]/ul/li[2]/a')
    save_form_popup_19 = (By.XPATH, '//*[@id="AlmostDoneModal"]/div/div/div/form/div[3]/div/button')

    delete_form = (By.XPATH, '//*[@id="content"]/div/div[2]/ng-include[1]/div/div[3]/div[2]/div/div[2]')
    delete_form_yes = (By.XPATH, '//*[@id="deleteModal"]/div/div/div[3]/ul/li[2]/a')
    delete_form_no = (By.XPATH, '//*[@id="deleteModal"]/div/div/div[3]/ul/li[1]/a')
    search = (By.XPATH, '//*[@id="content"]/div/div[2]/ng-include[1]/div/div[2]/div/button')
    customer_name = (By.XPATH, '//*[@id="content"]/div/div[2]/ng-include[1]/div/div[3]/div[2]/div/div[2]')
    existing_form = (By.XPATH, '//*[@id="main_ExistingForm"]')
    form_type = (By.XPATH, '//*[@id="content"]/div/div[2]/ng-include[1]/div/div[3]/div[2]/div/div[2]')
    edit_form = (By.XPATH, '//*[@id="content"]/div/div[2]/ng-include[1]/div/div[3]/div[2]/div/div[2]')
    mail_form = (By.XPATH, '//*[@id="content"]/div/div[2]/ng-include[1]/div/div[3]/div[2]/div/div[2]/div[1]/div[7]/ul/li[2]/a/i')
    export_form = (By.XPATH, '//*[@id="content"]/div/div[2]/ng-include[1]/div/div[3]/div[2]/div/div[2]/div[1]/div[7]/ul/li[3]/a/i')
    delete_form = (By.XPATH, '//*[@id="content"]/div/div[2]/ng-include[1]/div/div[3]/div[2]/div/div[2]')


    exit_success_popup_msg_19 = (By.XPATH, '//*[@id="SavedSuccessfullyModel"]/div/div/a')

    #M16_IMP = (By.XPATH, '//*[@id="lblno1"]/span')
    DATA_SITESAFE_NO = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[1]/ng-include[1]/div/div[2]/form/div/div/div[1]/div[1]/div[3]/ul/li[1]/div[2]/div/div[2]/div[2]/textarea')
    DATA_EQUIPMENTSAFE_NO = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[1]/div/div[2]/form/div/div/div[1]/div[2]/div[3]/ul/li[1]/div[2]/div/div[2]/div[2]/textarea')
    DATA_ELECTRICALDEV_NO = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[1]/div/div[2]/form/div/div/div[1]/div[3]/div[3]/ul/li[1]/div[2]/div/div[2]/div[2]/textarea')
    DATA_ISOLATED_NO = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[1]/div/div[2]/form/div/div/div[1]/div[4]/div[3]/ul/li[1]/div[2]/div/div[2]/div[2]/textarea')
    DATA_DUALPOWER_NO = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[1]/div/div[2]/form/div/div/div[1]/div[5]/div[3]/ul/li[1]/div[2]/div/div[2]/div[2]/textarea')
    DATA_LOTO_NO = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[1]/div/div[2]/form/div/div/div[1]/div[6]/div[3]/ul/li[1]/div[2]/div/div[2]/div[2]/textarea')
    DATA_LADDER_NO = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[1]/div/div[2]/form/div/div/div[1]/div[7]/div[3]/ul/li[1]/div[2]/div/div[2]/div[2]/textarea')
    DATA_PLATFORM_NO = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[1]/div/div[2]/form/div/div/div[1]/div[8]/div[3]/ul/li[1]/div[2]/div/div[2]/div[2]/textarea')
    DATA_INSPECTLADDER_NO = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[1]/div/div[2]/form/div/div/div[1]/div[9]/div[3]/ul/li[1]/div[2]/div/div[2]/div[2]/textarea')
    DATA_MATERIALS_NO = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[1]/div/div[2]/form/div/div/div[1]/div[10]/div[3]/ul/li[1]/div[2]/div/div[2]/div[2]/textarea')

    DATA_TRIPPING_NO = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[1]/div/div[2]/form/div/div/div[1]/div[1]/div[3]/ul/li[1]/div[2]/div/div[2]/div[2]/textarea')
    DATA_HAZARDS_NO = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[1]/div/div[2]/form/div/div/div[1]/div[2]/div[3]/ul/li[1]/div[2]/div/div[2]/div[2]/textarea')
    DATA_GUARDS_NO = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[1]/div/div[2]/form/div/div/div[1]/div[3]/div[3]/ul/li[1]/div[2]/div/div[2]/div[2]/textarea')
    DATA_GFCI_NO = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[1]/div/div[2]/form/div/div/div[1]/div[4]/div[3]/ul/li[1]/div[2]/div/div[2]/div[2]/textarea')
    DATA_COMPRESSED_NO = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[1]/div/div[2]/form/div/div/div[1]/div[5]/div[3]/ul/li[1]/div[2]/div/div[2]/div[2]/textarea')
    DATA_CALIBRATED_NO = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[1]/div/div[2]/form/div/div/div[1]/div[6]/div[3]/ul/li[1]/div[2]/div/div[2]/div[2]/textarea')
    DATA_WELDING_NO = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[1]/div/div[2]/form/div/div/div[1]/div[7]/div[3]/ul/li[1]/div[2]/div/div[2]/div[2]/textarea')
    DATA_BRAZING_NO = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[1]/div/div[2]/form/div/div/div[1]/div[8]/div[3]/ul/li[1]/div[2]/div/div[2]/div[2]/textarea')
    DATA_CONFINEDSPACE_NO = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[1]/div/div[2]/form/div/div/div[1]/div[9]/div[3]/ul/li[1]/div[2]/div/div[2]/div[2]/textarea')
    DATA_ESCAPEROUTE_NO = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[1]/div/div[2]/form/div/div/div[1]/div[10]/div[3]/ul/li[1]/div[2]/div/div[2]/div[2]/textarea')

    DATA_WATERSOURCE_NO = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[1]/div/div[2]/form/div/div/div[1]/div[1]/div[3]/ul/li[1]/div[2]/div/div[2]/div[2]/textarea')
    DATA_PPE_NO = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[1]/div/div[2]/form/div/div/div[1]/div[2]/div[3]/ul/li[1]/div[2]/div/div[2]/div[2]/textarea')
    DATA_LIFTING_NO = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[1]/div/div[2]/form/div/div/div[1]/div[3]/div[3]/ul/li[1]/div[2]/div/div[2]/div[2]/textarea')

    ADD_SITESAFE_NO = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[1]/div/div[2]/form/div/div/div/div[1]/div[3]/ul/li[1]/div[2]/div/div[3]/ul/li[1]/a')
    ADD_EQUIPMENTSAFE_NO = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[1]/div/div[2]/form/div/div/div[1]/div[2]/div[3]/ul/li[1]/div[2]/div/div[3]/ul/li[1]/a')
    ADD_ELECTRICALDEV_NO = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[1]/div/div[2]/form/div/div/div[1]/div[3]/div[3]/ul/li[1]/div[2]/div/div[3]/ul/li[1]/a')
    ADD_ISOLATED_NO = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[1]/div/div[2]/form/div/div/div[1]/div[4]/div[3]/ul/li[1]/div[2]/div/div[3]/ul/li[1]/a')
    ADD_DUALPOWER_NO = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[1]/div/div[2]/form/div/div/div[1]/div[5]/div[3]/ul/li[1]/div[2]/div/div[3]/ul/li[1]/a')
    ADD_LOTO_NO = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[1]/div/div[2]/form/div/div/div[1]/div[6]/div[3]/ul/li[1]/div[2]/div/div[3]/ul/li[1]/a')
    ADD_LADDER_NO = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[1]/div/div[2]/form/div/div/div[1]/div[7]/div[3]/ul/li[1]/div[2]/div/div[3]/ul/li[1]/a')
    ADD_PLATFORM_NO = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[1]/div/div[2]/form/div/div/div[1]/div[8]/div[3]/ul/li[1]/div[2]/div/div[3]/ul/li[1]/a')
    ADD_INSPECTLADDER_NO = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[1]/div/div[2]/form/div/div/div[1]/div[9]/div[3]/ul/li[1]/div[2]/div/div[3]/ul/li[1]/a')
    ADD_MATERIALS_NO = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[1]/div/div[2]/form/div/div/div[1]/div[10]/div[3]/ul/li[1]/div[2]/div/div[3]/ul/li[1]/a')

    ADD_TRIPPING_NO = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[1]/div/div[2]/form/div/div/div[1]/div[1]/div[3]/ul/li[1]/div[2]/div/div[3]/ul/li[1]/a')
    ADD_HAZARDS_NO = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[1]/div/div[2]/form/div/div/div[1]/div[2]/div[3]/ul/li[1]/div[2]/div/div[3]/ul/li[1]/a')
    ADD_GUARDS_NO = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[1]/div/div[2]/form/div/div/div[1]/div[3]/div[3]/ul/li[1]/div[2]/div/div[3]/ul/li[1]/a')
    ADD_GFCI_NO = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[1]/div/div[2]/form/div/div/div[1]/div[4]/div[3]/ul/li[1]/div[2]/div/div[3]/ul/li[1]/a')
    ADD_COMPRESSED_NO = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[1]/div/div[2]/form/div/div/div[1]/div[5]/div[3]/ul/li[1]/div[2]/div/div[3]/ul/li[1]/a')
    ADD_CALIBRATED_NO = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[1]/div/div[2]/form/div/div/div[1]/div[6]/div[3]/ul/li[1]/div[2]/div/div[3]/ul/li[1]/a')
    ADD_WELDING_NO = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[1]/div/div[2]/form/div/div/div[1]/div[7]/div[3]/ul/li[1]/div[2]/div/div[3]/ul/li[1]/a')
    ADD_BRAZING_NO = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[1]/div/div[2]/form/div/div/div[1]/div[8]/div[3]/ul/li[1]/div[2]/div/div[3]/ul/li[1]/a')
    ADD_CONFINEDSPACE_NO = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[1]/div/div[2]/form/div/div/div[1]/div[9]/div[3]/ul/li[1]/div[2]/div/div[3]/ul/li[1]/a')
    ADD_ESCAPEROUTE_NO = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[1]/div/div[2]/form/div/div/div[1]/div[10]/div[3]/ul/li[1]/div[2]/div/div[3]/ul/li[1]/a')

    ADD_WATERSOURCE_NO = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[1]/div/div[2]/form/div/div/div[1]/div[1]/div[3]/ul/li[1]/div[2]/div/div[3]/ul/li[1]/a')
    ADD_PPE_NO = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[1]/div/div[2]/form/div/div/div[1]/div[2]/div[3]/ul/li[1]/div[2]/div/div[3]/ul/li[1]/a')
    ADD_LIFTING_NO = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[1]/div/div[2]/form/div/div/div[1]/div[3]/div[3]/ul/li[1]/div[2]/div/div[3]/ul/li[1]/a')

    Next = (By.XPATH, '//*[contains(text(), "Next")]')

    Bodytext = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[1]/ng-include[1]/div/div[2]/form/div/div/div[1]/div[4]/table/tbody/tr[2]/td')

    TEXT_DATA = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[1]/div/div[2]/form/div/div/div[1]/div[4]/table/tbody/tr[2]/td')

    M16_SITESAFE_NO = (By.XPATH, '//*[@id="lblno1"]/span')
    M16_EQUIPMENTSAFE_NO = (By.XPATH, '//*[@id="lblno2"]/span')
    M16_ELECTRICALDEV_NO = (By.XPATH, '//*[@id="lblno3"]/span')
    M16_ISOLATED_NO = (By.XPATH, '//*[@id="lblno4"]/span')
    M16_DUALPOWER_NO = (By.XPATH, '//*[@id="lblno5"]/span')
    M16_LOTO_NO = (By.XPATH, '//*[@id="lblno6"]/span')
    M16_LADDER_NO = (By.XPATH, '//*[@id="lblno7"]/span')
    M16_PLATFORM_NO = (By.XPATH, '//*[@id="lblno8"]/span')
    M16_INSPECTLADDER_NO = (By.XPATH, '//*[@id="lblno9"]/span')
    M16_MATERIALS_NO = (By.XPATH, '//*[@id="lblno10"]/span')
    M16_TRIPPING_NO =(By.XPATH, '//*[@id="lblno11"]/span')
    M16_HAZARDS_NO = (By.XPATH, '//*[@id="lblno12"]/span')
    M16_GUARDS_NO = (By.XPATH, '//*[@id="lblno13"]/span')
    M16_GFCI_NO = (By.XPATH, '//*[@id="lblno14"]/span')
    M16_COMPRESSED_NO = (By.XPATH, '//*[@id="lblno15"]/span')
    M16_CALIBRATED_NO = (By.XPATH, '//*[@id="lblno16"]/span')
    M16_WELDING_NO = (By.XPATH, '//*[@id="lblno17"]/span')
    M16_BRAZING_NO = (By.XPATH, '//*[@id="lblno18"]/span')
    M16_CONFINEDSPACE_NO = (By.XPATH, '//*[@id="lblno19"]/span')
    M16_ESCAPEROUTE_NO = (By.XPATH, '//*[@id="lblno20"]/span')
    M16_WATERSOURCE_NO =(By.XPATH, '//*[@id="lblno21"]/span')
    M16_PPE_NO = (By.XPATH, '//*[@id="lblno22"]/span')
    M16_LIFTING_NO = (By.XPATH, '//*[@id="lblno23"]/span')

    #M16_SITESAFE_YES = (By.XPATH, '//*[@id="lblno1"]/span')
    M16_SITESAFE_YES = (By.XPATH, '(//*[@id="lblno1"]/span)[2]')
    M16_EQUIPMENTSAFE_YES = (By.XPATH, '(//*[@id="lblno2"]/span)[2]')
    M16_ELECTRICALDEV_YES = (By.XPATH, '(//*[@id="lblno3"]/span)[2]')
    M16_ISOLATED_YES = (By.XPATH, '(//*[@id="lblno4"]/span)[2]')
    M16_DUALPOWER_YES = (By.XPATH, '(//*[@id="lblno5"]/span)[2]')
    M16_LOTO_YES = (By.XPATH, '(//*[@id="lblno6"]/span)[2]')
    M16_LADDER_YES = (By.XPATH, '(//*[@id="lblno7"]/span)[2]')
    M16_PLATFORM_YES = (By.XPATH, '(//*[@id="lblno8"]/span)[2]')
    M16_INSPECTLADDER_YES = (By.XPATH, '(//*[@id="lblno9"]/span)[2]')
    M16_MATERIALS_YES = (By.XPATH, '(//*[@id="lblno10"]/span)[2]')
    M16_TRIPPING_YES =(By.XPATH, '(//*[@id="lblno11"]/span)[2]')
    M16_HAZARDS_YES = (By.XPATH, '(//*[@id="lblno12"]/span)[2]')
    M16_GUARDS_YES = (By.XPATH, '(//*[@id="lblno13"]/span)[2]')
    M16_GFCI_YES = (By.XPATH, '(//*[@id="lblno14"]/span)[2]')
    M16_COMPRESSED_YES = (By.XPATH, '(//*[@id="lblno15"]/span)[2]')
    M16_CALIBRATED_YES = (By.XPATH, '(//*[@id="lblno16"]/span)[2]')
    M16_WELDING_YES = (By.XPATH, '(//*[@id="lblno17"]/span)[2]')
    M16_BRAZING_YES = (By.XPATH, '(//*[@id="lblno18"]/span)[2]')
    M16_CONFINEDSPACE_YES = (By.XPATH, '(//*[@id="lblno19"]/span)[2]')
    M16_ESCAPEROUTE_YES = (By.XPATH, '(//*[@id="lblno20"]/span)[2]')
    M16_WATERSOURCE_YES =(By.XPATH, '(//*[@id="lblno21"]/span)[2]')
    M16_PPE_YES = (By.XPATH, '(//*[@id="lblno22"]/span)[2]')
    M16_LIFTING_YES = (By.XPATH, '(//*[@id="lblno23"]/span)[2]')

    M16_SITESAFE_NA = (By.XPATH,'//*[@id="lblna1"]/span')
    M16_EQUIPMENTSAFE_NA = (By.XPATH,'//*[@id="lblna2"]/span')
    M16_ELECTRICALDEV_NA = (By.XPATH, '//*[@id="lblna3"]/span')
    M16_ISOLATED_NA = (By.XPATH, '//*[@id="lblna4"]/span')
    M16_DUALPOWER_NA = (By.XPATH, '//*[@id="lblna5"]/span')
    M16_LOTO_NA = (By.XPATH, '//*[@id="lblna6"]/span')
    M16_LADDER_NA = (By.XPATH, '//*[@id="lblna7"]/span')
    M16_PLATFORM_NA = (By.XPATH, '//*[@id="lblna8"]/span')
    M16_INSPECTLADDER_NA = (By.XPATH, '//*[@id="lblna9"]/span')
    M16_MATERIALS_NA = (By.XPATH, '//*[@id="lblna10"]/span')
    M16_TRIPPING_NA =(By.XPATH, '//*[@id="lblna11"]/span')
    M16_HAZARDS_NA = (By.XPATH, '//*[@id="lblna12"]/span')
    M16_GUARDS_NA = (By.XPATH, '//*[@id="lblna13"]/span')
    M16_GFCI_NA = (By.XPATH, '//*[@id="lblna14"]/span')
    M16_COMPRESSED_NA = (By.XPATH, '//*[@id="lblna15"]/span')
    M16_CALIBRATED_NA = (By.XPATH, '//*[@id="lblna16"]/span')
    M16_WELDING_NA = (By.XPATH, '//*[@id="lblna17"]/span')
    M16_BRAZING_NA = (By.XPATH, '//*[@id="lblna18"]/span')
    M16_CONFINEDSPACE_NA = (By.XPATH, '//*[@id="lblna19"]/span')
    M16_ESCAPEROUTE_NA = (By.XPATH, '//*[@id="lblna20"]/span')
    M16_WATERSOURCE_NA =(By.XPATH, '//*[@id="lblna21"]/span')
    M16_PPE_NA = (By.XPATH, '//*[@id="lblna22"]/span')
    M16_LIFTING_NA = (By.XPATH, '//*[@id="lblna23"]/span')

    ehs_data_reset = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[1]/ng-include[1]/div/div[1]/ul/li[2]/a')
    design_data_reset_two = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[3]/div/div[1]/ul/li[2]/a')
    # Exit
    ehs_data_exit = (By.XPATH, '//*[@id="aExistingForm"]/i')

    # Save
    design_data_save = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[4]/ul/li[2]/a')
    design_data_save_one = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[3]/div/div[2]/form/div/div[4]/ul/li[2]/a')
    # Cancel
    design_data_cancel = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[2]/div/div[2]/form/div/div[4]/ul/li[1]/a')

    design_data = (By.XPATH, '//*[@id="tabdivisonsid"]/ul/li/a/span[1]')
    design_data_two = (By.XPATH, '//*[@id="tabdivisonsid"]/ul/li/a/span[2]/i')
    design_data_three = (By.XPATH, '//*[@id="tabdivisonsid"]/ul/li/a/span[1]/i')

    # Quaterly Log Sheet
    quaterly = (By.XPATH,'//*[@id="content"]/div/div[2]/ng-include[2]/div/div[3]/form/div[1]/div[3]/ul[2]')
    logsheet = (By.XPATH,'//*[@id="logsheet"]')


    Cooler_Refridge_pressure = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[4]/div/div/div[2]/div[2]/form/div/div[1]/div[1]/div[1]/div/div[1]/div/input')
    Cooler_Refridge_temp = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[4]/div/div/div[2]/div[2]/form/div/div[1]/div[1]/div[1]/div/div[2]/div/input')
    Cooler_Water_pressure_in = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[4]/div/div/div[2]/div[2]/form/div/div[1]/div[2]/div[2]/div/div/div[1]/div[1]/input')
    Cooler_Water_pressure_out = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[4]/div/div/div[2]/div[2]/form/div/div[1]/div[2]/div[2]/div/div/div[1]/div[2]/input')
    Cooler_Water_pressure_delta = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[4]/div/div/div[2]/div[2]/form/div/div[1]/div[2]/div[2]/div/div/div[1]/div[3]/input')
    Cooler_Water_temp_in = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[4]/div/div/div[2]/div[2]/form/div/div[1]/div[2]/div[2]/div/div/div[2]/div/input')
    Cooler_Water_temp_out = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[4]/div/div/div[2]/div[2]/form/div/div[1]/div[2]/div[2]/div/div/div[3]/div/input')
    Cooler_Water_temp_delta = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[4]/div/div/div[2]/div[2]/form/div/div[1]/div[2]/div[2]/div/div/div[4]/div/input')
    Condenser_Water_approach = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[4]/div/div/div[2]/div[2]/form/div/div[1]/div[1]/div[1]/div/div[3]/div/input')
    Condenser_Refridge_pressure = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[4]/div/div/div[2]/div[2]/form/div/div[2]/div[1]/div[1]/div/div[1]/div/input')
    Condenser_Refridge_temp = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[4]/div/div/div[2]/div[2]/form/div/div[2]/div[1]/div[1]/div/div[2]/div/input')
    Condenser_Refridge_approach = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[4]/div/div/div[2]/div[2]/form/div/div[2]/div[1]/div[1]/div/div[3]/div/input')
    Condenser_Water_pressure_in = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[4]/div/div/div[2]/div[2]/form/div/div[2]/div[2]/div[2]/div/div/div[1]/div[1]/input')
    Condenser_Water_pressure_out = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[4]/div/div/div[2]/div[2]/form/div/div[2]/div[2]/div[2]/div/div/div[1]/div[2]/input')
    Condenser_Water_pressure_delta = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[4]/div/div/div[2]/div[2]/form/div/div[2]/div[2]/div[2]/div/div/div[1]/div[3]/input')
    Condenser_Water_temp_in = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[4]/div/div/div[2]/div[2]/form/div/div[2]/div[2]/div[2]/div/div/div[2]/div/input')
    Condenser_Water_temp_out = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[4]/div/div/div[2]/div[2]/form/div/div[2]/div[2]/div[2]/div/div/div[3]/div/input')
    Condenser_Water_temp_delta = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[4]/div/div/div[2]/div[2]/form/div/div[2]/div[2]/div[2]/div/div/div[4]/div/input')

    Compressor_Oil_pressure = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[4]/div/div/div[2]/div[2]/form/div/div[3]/div[1]/div[1]/div/div[1]/div/input')
    Compressor_Oil_resevtmp = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[4]/div/div/div[2]/div[2]/form/div/div[3]/div[1]/div[1]/div/div[2]/div/input')
    Compressor_Oil_resevlevel = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[4]/div/div/div[2]/div[2]/form/div/div[3]/div[1]/div[1]/div/div[3]/div/input')
    Compressor_Oil_runhrs = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[4]/div/div/div[2]/div[2]/form/div/div[4]/div[1]/div/div/div[1]/div/input')
    Compressor_Oil_nostarts = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[4]/div/div/div[2]/div[2]/form/div/div[4]/div[1]/div/div/div[2]/div/input')
    Compressor_Oil_capacity = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[4]/div/div/div[2]/div[2]/form/div/div[4]/div[1]/div/div/div[3]/div/input')

    Compressor_motor_tmp = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[4]/div/div/div[2]/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div[1]/div/input')
    Compressor_motor_bearingtmp = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[4]/div/div/div[2]/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div[2]/div/input')

    Quaterly_logsheet_save = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[4]/div/div/div[2]/div[2]/form/ul/li[2]/a')
    logsheet_form_popup_19 = (By.XPATH, '//*[@id="AlmostDoneModal"]/div/div/div/form/div[3]/div')
   # '//*[@id="content"]/div/div[2]/ng-include[1]/div/div[3]/div[2]/div/div[2]/div[1]/div[7]/ul/li[1]/a/i'

    logs_data_reset = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[4]/div/div/div[2]/div[1]/ul/li[2]/a')

    annual_logs_data_reset = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[5]/div/div/div[2]/div[1]/ul/li[2]/a')

    annual_logsheet = (By.XPATH,'//*[@id="annualLogsheet"]')
    # Annual Log Sheet
    annual = (By.XPATH,'//*[@id="content"]/div/div[2]/ng-include[2]/div/div[3]/form/div[1]/div[3]/ul[2]/li[1]/label/strong')

    annual_Cooler_Refridge_pressure = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[5]/div/div/div[2]/div[2]/form/div/div[1]/div[1]/div[1]/div/div[1]/div/input')
    annual_Cooler_Refridge_temp = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[5]/div/div/div[2]/div[2]/form/div/div[1]/div[1]/div[1]/div/div[2]/div/input')
    annual_Cooler_Water_pressure_in = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[5]/div/div/div[2]/div[2]/form/div/div[1]/div[2]/div[2]/div/div/div[1]/div[1]/input')
    annual_Cooler_Water_pressure_out = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[5]/div/div/div[2]/div[2]/form/div/div[1]/div[2]/div[2]/div/div/div[1]/div[2]/input')
    annual_Cooler_Water_pressure_delta = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[5]/div/div/div[2]/div[2]/form/div/div[1]/div[2]/div[2]/div/div/div[1]/div[3]/input')
    annual_Cooler_Water_temp_in = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[5]/div/div/div[2]/div[2]/form/div/div[1]/div[2]/div[2]/div/div/div[2]/div/input')
    annual_Cooler_Water_temp_out = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[5]/div/div/div[2]/div[2]/form/div/div[1]/div[2]/div[2]/div/div/div[3]/div/input')
    annual_Cooler_Water_temp_delta = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[5]/div/div/div[2]/div[2]/form/div/div[1]/div[2]/div[2]/div/div/div[4]/div/input')
    annual_Condenser_Water_approach = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[5]/div/div/div[2]/div[2]/form/div/div[1]/div[1]/div[1]/div/div[3]/div/input')
    annual_Condenser_Refridge_pressure = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[5]/div/div/div[2]/div[2]/form/div/div[2]/div[1]/div[1]/div/div[1]/div/input')
    annual_Condenser_Refridge_temp = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[5]/div/div/div[2]/div[2]/form/div/div[2]/div[1]/div[1]/div/div[2]/div/input')
    annual_Condenser_Refridge_approach = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[5]/div/div/div[2]/div[2]/form/div/div[2]/div[1]/div[1]/div/div[3]/div/input')
    annual_Condenser_Water_pressure_in = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[5]/div/div/div[2]/div[2]/form/div/div[2]/div[2]/div[2]/div/div/div[1]/div[1]/input')
    annual_Condenser_Water_pressure_out = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[5]/div/div/div[2]/div[2]/form/div/div[2]/div[2]/div[2]/div/div/div[1]/div[2]/input')
    annual_Condenser_Water_pressure_delta = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[5]/div/div/div[2]/div[2]/form/div/div[2]/div[2]/div[2]/div/div/div[1]/div[3]/input')
    annual_Condenser_Water_temp_in = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[5]/div/div/div[2]/div[2]/form/div/div[2]/div[2]/div[2]/div/div/div[2]/div/input')
    annual_Condenser_Water_temp_out = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[5]/div/div/div[2]/div[2]/form/div/div[2]/div[2]/div[2]/div/div/div[3]/div/input')
    annual_Condenser_Water_temp_delta = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[5]/div/div/div[2]/div[2]/form/div/div[2]/div[2]/div[2]/div/div/div[4]/div/input')

    annual_Compressor_Oil_pressure = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[5]/div/div/div[2]/div[2]/form/div/div[3]/div[1]/div[1]/div/div[1]/div/input')
    annual_Compressor_Oil_resevtmp = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[5]/div/div/div[2]/div[2]/form/div/div[3]/div[1]/div[1]/div/div[2]/div/input')
    annual_Compressor_Oil_resevlevel = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[5]/div/div/div[2]/div[2]/form/div/div[3]/div[1]/div[1]/div/div[3]/div/input')
    annual_Compressor_Oil_runhrs = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[5]/div/div/div[2]/div[2]/form/div/div[4]/div[1]/div/div/div[1]/div/input')
    annual_Compressor_Oil_nostarts = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[5]/div/div/div[2]/div[2]/form/div/div[4]/div[1]/div/div/div[2]/div/input')
    annual_Compressor_Oil_capacity = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[5]/div/div/div[2]/div[2]/form/div/div[4]/div[1]/div/div/div[3]/div/input')

    annual_Compressor_motor_tmp = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[5]/div/div/div[2]/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div[1]/div/input')
    annual_Compressor_motor_bearingtmp = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[2]/ng-include[5]/div/div/div[2]/div[2]/form/div/div[3]/div[2]/div[2]/div/div/div[2]/div/input')

    annual_logsheet_save = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[2]/ng-include[5]/div/div/div[2]/div[2]/form/ul/li[2]/a')

    checklist_new= (By.XPATH, '//*[@id="content"]/div/div[2]/ng-include[2]/div/div[3]/form/div[1]/div[3]/ul[3]/li[2]')
    checklist_annual_new = (By.XPATH, '//*[@id="annualChecklist"]')
    checklist_quarterly = (By.XPATH, '//*[@id="lblquarterly"]/span')
    checklist_annual = (By.XPATH, '//*[@id="content"]/div/div[2]/ng-include[2]/div/div[3]/form/div[1]/div[3]/ul[2]/li[1]/label/span')

    checklist_Next = (By.XPATH, '//*[@id="quarterlyNextbtn"]')
    chekclist_annual_Next = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/ul/li[2]/a')

    checklist_quarter_1_results_no = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[2]/div/div[2]/form/div/div/div[2]/div[1]/div[4]/ul/li[1]/label/span')
    checklist_quarter_2_results_no = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[2]/div/div[2]/form/div/div/div[2]/div[2]/div[4]/ul/li[1]/label/span')
    checklist_quarter_3_results_no = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[2]/div/div[2]/form/div/div/div[2]/div[3]/div[4]/ul/li[1]/label/span')
    checklist_quarter_4_results_no = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[2]/div/div[2]/form/div/div/div[2]/div[4]/div[4]/ul/li[1]/label/span')
    checklist_quarter_5_results_no = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[2]/div/div[2]/form/div/div/div[2]/div[5]/div[4]/ul/li[1]/label/span')
    checklist_quarter_6_results_no = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[2]/div/div[2]/form/div/div/div[2]/div[6]/div[4]/ul/li[1]/label/span')
    checklist_quarter_7_results_no = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[2]/div/div[2]/form/div/div/div[2]/div[7]/div[4]/ul/li[1]/label/span')
    checklist_quarter_8_results_no = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[2]/div/div[2]/form/div/div/div[2]/div[8]/div[4]/ul/li[1]/label/span')
    checklist_quarter_9_results_no = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[2]/div/div[2]/form/div/div/div[2]/div[9]/div[4]/ul/li[1]/label/span')
    checklist_quarter_10_results_no = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[2]/div/div[2]/form/div/div/div[2]/div[10]/div[4]/ul/li[1]/label/span')
    checklist_quarter_11_results_no = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[2]/div/div[2]/form/div/div/div[2]/div[1]/div[4]/ul/li[1]/label/span')
    checklist_quarter_12_results_no = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[2]/div/div[2]/form/div/div/div[2]/div[2]/div[4]/ul/li[1]/label/span')

    checklist_quarter_1_results_yes = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[2]/div/div[2]/form/div/div/div[2]/div[1]/div[4]/ul/li[2]/label/span')
    checklist_quarter_2_results_yes = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[2]/div/div[2]/form/div/div/div[2]/div[2]/div[4]/ul/li[2]/label/span')
    checklist_quarter_3_results_yes = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[2]/div/div[2]/form/div/div/div[2]/div[3]/div[4]/ul/li[2]/label/span')
    checklist_quarter_4_results_yes = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[2]/div/div[2]/form/div/div/div[2]/div[4]/div[4]/ul/li[2]/label/span')
    checklist_quarter_5_results_yes = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[2]/div/div[2]/form/div/div/div[2]/div[5]/div[4]/ul/li[2]/label/span')
    checklist_quarter_6_results_yes = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[2]/div/div[2]/form/div/div/div[2]/div[6]/div[4]/ul/li[2]/label/span')
    checklist_quarter_7_results_yes = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[2]/div/div[2]/form/div/div/div[2]/div[7]/div[4]/ul/li[2]/label/span')
    checklist_quarter_8_results_yes = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[2]/div/div[2]/form/div/div/div[2]/div[8]/div[4]/ul/li[2]/label/span')
    checklist_quarter_9_results_yes = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[2]/div/div[2]/form/div/div/div[2]/div[9]/div[4]/ul/li[2]/label/span')
    checklist_quarter_10_results_yes = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[2]/div/div[2]/form/div/div/div[2]/div[10]/div[4]/ul/li[2]/label/span')
    checklist_quarter_11_results_yes = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[2]/div/div[2]/form/div/div/div[2]/div[1]/div[4]/ul/li[2]/label/span')
    checklist_quarter_12_results_yes = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[2]/div/div[2]/form/div/div/div[2]/div[2]/div[4]/ul/li[2]/label/span')

    checklist_quarter_1_spares_no = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[2]/div/div[2]/form/div/div/div[2]/div[1]/div[5]/ul/li[1]/label/span')
    checklist_quarter_2_spares_no = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[2]/div/div[2]/form/div/div/div[2]/div[2]/div[5]/ul/li[1]/label/span')
    checklist_quarter_3_spares_no = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[2]/div/div[2]/form/div/div/div[2]/div[3]/div[5]/ul/li[1]/label/span')
    checklist_quarter_4_spares_no = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[2]/div/div[2]/form/div/div/div[2]/div[4]/div[5]/ul/li[1]/label/span')
    checklist_quarter_5_spares_no = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[2]/div/div[2]/form/div/div/div[2]/div[5]/div[5]/ul/li[1]/label/span')
    checklist_quarter_6_spares_no = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[2]/div/div[2]/form/div/div/div[2]/div[6]/div[5]/ul/li[1]/label/span')
    checklist_quarter_7_spares_no = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[2]/div/div[2]/form/div/div/div[2]/div[7]/div[5]/ul/li[1]/label/span')
    checklist_quarter_8_spares_no = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[2]/div/div[2]/form/div/div/div[2]/div[8]/div[5]/ul/li[1]/label/span')
    checklist_quarter_9_spares_no = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[2]/div/div[2]/form/div/div/div[2]/div[9]/div[5]/ul/li[1]/label/span')
    checklist_quarter_10_spares_no = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[2]/div/div[2]/form/div/div/div[2]/div[10]/div[5]/ul/li[1]/label/span')
    checklist_quarter_11_spares_no = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[2]/div/div[2]/form/div/div/div[2]/div[1]/div[5]/ul/li[1]/label/span')
    checklist_quarter_12_spares_no = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[2]/div/div[2]/form/div/div/div[2]/div[2]/div[5]/ul/li[1]/label/span')

    checklist_quarter_1_spares_yes = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[2]/div/div[2]/form/div/div/div[2]/div[1]/div[5]/ul/li[2]/label/span')
    checklist_quarter_2_spares_yes = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[2]/div/div[2]/form/div/div/div[2]/div[2]/div[5]/ul/li[2]/label/span')
    checklist_quarter_3_spares_yes = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[2]/div/div[2]/form/div/div/div[2]/div[3]/div[5]/ul/li[2]/label/span')
    checklist_quarter_4_spares_yes = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[2]/div/div[2]/form/div/div/div[2]/div[4]/div[5]/ul/li[2]/label/span')
    checklist_quarter_5_spares_yes = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[2]/div/div[2]/form/div/div/div[2]/div[5]/div[5]/ul/li[2]/label/span')
    checklist_quarter_6_spares_yes = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[2]/div/div[2]/form/div/div/div[2]/div[6]/div[5]/ul/li[2]/label/span')
    checklist_quarter_7_spares_yes = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[2]/div/div[2]/form/div/div/div[2]/div[7]/div[5]/ul/li[2]/label/span')
    checklist_quarter_8_spares_yes = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[2]/div/div[2]/form/div/div/div[2]/div[8]/div[5]/ul/li[2]/label/span')
    checklist_quarter_9_spares_yes = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[2]/div/div[2]/form/div/div/div[2]/div[9]/div[5]/ul/li[2]/label/span')
    checklist_quarter_10_spares_yes = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[2]/div/div[2]/form/div/div/div[2]/div[10]/div[5]/ul/li[2]/label/span')
    checklist_quarter_11_spares_yes = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[2]/div/div[2]/form/div/div/div[2]/div[1]/div[5]/ul/li[2]/label/span')
    checklist_quarter_12_spares_yes = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[2]/div/div[2]/form/div/div/div[2]/div[2]/div[5]/ul/li[2]/label/span')

    checklist_quarter_1_textarea = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[2]/div/div[2]/form/div/div/div[2]/div[1]/div[7]/div[2]/div/div[2]/div[2]/textarea')
    checklist_quarter_2_textarea = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[2]/div/div[2]/form/div/div/div[2]/div[2]/div[7]/div[2]/div/div[2]/div[2]/textarea')
    checklist_quarter_3_textarea = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[2]/div/div[2]/form/div/div/div[2]/div[3]/div[7]/div[2]/div/div[2]/div[2]/textarea')
    checklist_quarter_4_textarea = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[2]/div/div[2]/form/div/div/div[2]/div[4]/div[7]/div[2]/div/div[2]/div[2]/textarea')
    checklist_quarter_5_textarea = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[2]/div/div[2]/form/div/div/div[2]/div[5]/div[7]/div[2]/div/div[2]/div[2]/textarea')
    checklist_quarter_6_textarea = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[2]/div/div[2]/form/div/div/div[2]/div[6]/div[7]/div[2]/div/div[2]/div[2]/textarea')
    checklist_quarter_7_textarea = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[2]/div/div[2]/form/div/div/div[2]/div[7]/div[7]/div[2]/div/div[2]/div[2]/textarea')
    checklist_quarter_8_textarea = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[2]/div/div[2]/form/div/div/div[2]/div[8]/div[7]/div[2]/div/div[2]/div[2]/textarea')
    checklist_quarter_9_textarea = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[2]/div/div[2]/form/div/div/div[2]/div[9]/div[7]/div[2]/div/div[2]/div[2]/textarea')
    checklist_quarter_10_textarea = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[2]/div/div[2]/form/div/div/div[2]/div[10]/div[7]/div[2]/div/div[2]/div[2]/textarea')
    checklist_quarter_11_textarea = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[2]/div/div[2]/form/div/div/div[2]/div[1]/div[7]/div[2]/div/div[2]/div[2]/textarea')
    checklist_quarter_12_textarea = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[2]/div/div[2]/form/div/div/div[2]/div[2]/div[7]/div[2]/div/div[2]/div[2]/textarea')

    checklist_quarter_1_addbutton = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[2]/div/div[2]/form/div/div/div[2]/div[1]/div[7]/div[2]/div/div[3]/ul/li[1]/a')
    checklist_quarter_2_addbutton = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[2]/div/div[2]/form/div/div/div[2]/div[2]/div[7]/div[2]/div/div[3]/ul/li[1]/a')
    checklist_quarter_3_addbutton = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[2]/div/div[2]/form/div/div/div[2]/div[3]/div[7]/div[2]/div/div[3]/ul/li[1]/a')
    checklist_quarter_4_addbutton = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[2]/div/div[2]/form/div/div/div[2]/div[4]/div[7]/div[2]/div/div[3]/ul/li[1]/a')
    checklist_quarter_5_addbutton = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[2]/div/div[2]/form/div/div/div[2]/div[5]/div[7]/div[2]/div/div[3]/ul/li[1]/a')
    checklist_quarter_6_addbutton = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[2]/div/div[2]/form/div/div/div[2]/div[6]/div[7]/div[2]/div/div[3]/ul/li[1]/a')
    checklist_quarter_7_addbutton = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[2]/div/div[2]/form/div/div/div[2]/div[7]/div[7]/div[2]/div/div[3]/ul/li[1]/a')
    checklist_quarter_8_addbutton = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[2]/div/div[2]/form/div/div/div[2]/div[8]/div[7]/div[2]/div/div[3]/ul/li[1]/a')
    checklist_quarter_9_addbutton = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[2]/div/div[2]/form/div/div/div[2]/div[9]/div[7]/div[2]/div/div[3]/ul/li[1]/a')
    checklist_quarter_10_addbutton = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[2]/div/div[2]/form/div/div/div[2]/div[10]/div[7]/div[2]/div/div[3]/ul/li[1]/a')
    checklist_quarter_11_addbutton = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[2]/div/div[2]/form/div/div/div[2]/div[1]/div[7]/div[2]/div/div[3]/ul/li[1]/a')
    checklist_quarter_12_addbutton = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[2]/div/div[2]/form/div/div/div[2]/div[2]/div[7]/div[2]/div/div[3]/ul/li[1]/a')

    checklist_bodytext = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[2]/div/div[2]/form/div/div/div[2]/div[3]/table/tbody/tr[2]/td')
    checklist_exit = (By.XPATH,'//*[@id="existButtonQutrChecklist"]/a')
    checklist_annual_exit = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[1]/ul/li[1]/a')
    checklist_data_reset = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[1]/ng-include[2]/div/div[1]/ul/li[2]/a')
    checklist_data_annual_reset = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[1]/ul/li[2]/a')

    checklist_annual_1_results_no = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[1]/div[3]/ul/li[1]/label/span')
    checklist_annual_2_results_no = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[2]/div[3]/ul/li[1]/label/span')
    checklist_annual_3_results_no = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[3]/div[3]/ul/li[1]/label/span')
    checklist_annual_4_results_no = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[4]/div[3]/ul/li[1]/label/span')
    checklist_annual_5_results_no = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[5]/div[3]/ul/li[1]/label/span')
    checklist_annual_6_results_no = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[6]/div[3]/ul/li[1]/label/span')
    checklist_annual_7_results_no = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[7]/div[3]/ul/li[1]/label/span')
    checklist_annual_8_results_no = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[8]/div[3]/ul/li[1]/label/span')
    checklist_annual_9_results_no = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[9]/div[3]/ul/li[1]/label/span')
    checklist_annual_10_results_no = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[10]/div[3]/ul/li[1]/label/span')
    checklist_annual_11_results_no = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[1]/div[3]/ul/li[1]/label/span')
    checklist_annual_12_results_no = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[2]/div[3]/ul/li[1]/label/span')
    checklist_annual_13_results_no = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[3]/div[3]/ul/li[1]/label/span')
    checklist_annual_14_results_no = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[4]/div[3]/ul/li[1]/label/span')
    checklist_annual_15_results_no = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[5]/div[3]/ul/li[1]/label/span')
    checklist_annual_16_results_no = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[6]/div[3]/ul/li[1]/label/span')
    checklist_annual_17_results_no = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[7]/div[3]/ul/li[1]/label/span')
    checklist_annual_18_results_no = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[8]/div[3]/ul/li[1]/label/span')
    checklist_annual_19_results_no = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[9]/div[3]/ul/li[1]/label/span')
    checklist_annual_20_results_no = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[10]/div[3]/ul/li[1]/label/span')
    checklist_annual_21_results_no = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[1]/div[3]/ul/li[1]/label/span')
    checklist_annual_22_results_no = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[2]/div[3]/ul/li[1]/label/span')
    checklist_annual_23_results_no = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[3]/div[3]/ul/li[1]/label/span')
    checklist_annual_24_results_no = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[4]/div[3]/ul/li[1]/label/span')
    checklist_annual_25_results_no = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[5]/div[3]/ul/li[1]/label/span')
    checklist_annual_26_results_no = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[6]/div[3]/ul/li[1]/label/span')


    checklist_annual_1_textarea = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[1]/div[5]/div[2]/div/div[2]/div[2]/textarea')
    checklist_annual_2_textarea = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[2]/div[5]/div[2]/div/div[2]/div[2]/textarea')
    checklist_annual_3_textarea = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[3]/div[5]/div[2]/div/div[2]/div[2]/textarea')
    checklist_annual_4_textarea = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[4]/div[5]/div[2]/div/div[2]/div[2]/textarea')
    checklist_annual_5_textarea = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[5]/div[5]/div[2]/div/div[2]/div[2]/textarea')
    checklist_annual_6_textarea = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[6]/div[5]/div[2]/div/div[2]/div[2]/textarea')
    checklist_annual_7_textarea = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[7]/div[5]/div[2]/div/div[2]/div[2]/textarea')
    checklist_annual_8_textarea = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[8]/div[5]/div[2]/div/div[2]/div[2]/textarea')
    checklist_annual_9_textarea = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[9]/div[5]/div[2]/div/div[2]/div[2]/textarea')
    checklist_annual_10_textarea = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[10]/div[5]/div[2]/div/div[2]/div[2]/textarea')
    checklist_annual_11_textarea = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[1]/div[5]/div[2]/div/div[2]/div[2]/textarea')
    checklist_annual_12_textarea = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[2]/div[5]/div[2]/div/div[2]/div[2]/textarea')
    checklist_annual_13_textarea = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[3]/div[5]/div[2]/div/div[2]/div[2]/textarea')
    checklist_annual_14_textarea = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[4]/div[5]/div[2]/div/div[2]/div[2]/textarea')
    checklist_annual_15_textarea = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[5]/div[5]/div[2]/div/div[2]/div[2]/textarea')
    checklist_annual_16_textarea = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[6]/div[5]/div[2]/div/div[2]/div[2]/textarea')
    checklist_annual_17_textarea = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[7]/div[5]/div[2]/div/div[2]/div[2]/textarea')
    checklist_annual_18_textarea = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[8]/div[5]/div[2]/div/div[2]/div[2]/textarea')
    checklist_annual_19_textarea = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[9]/div[5]/div[2]/div/div[2]/div[2]/textarea')
    checklist_annual_20_textarea = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[10]/div[5]/div[2]/div/div[2]/div[2]/textarea')
    checklist_annual_21_textarea = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[1]/div[5]/div[2]/div/div[2]/div[2]/textarea')
    checklist_annual_22_textarea = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[2]/div[5]/div[2]/div/div[2]/div[2]/textarea')
    checklist_annual_23_textarea = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[3]/div[5]/div[2]/div/div[2]/div[2]/textarea')
    checklist_annual_24_textarea = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[4]/div[5]/div[2]/div/div[2]/div[2]/textarea')
    checklist_annual_25_textarea = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[5]/div[5]/div[2]/div/div[2]/div[2]/textarea')
    checklist_annual_26_textarea = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[6]/div[5]/div[2]/div/div[2]/div[2]/textarea')

    checklist_annual_1_addbutton =  (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[1]/div[5]/div[2]/div/div[3]/ul/li[1]/a')
    checklist_annual_2_addbutton =  (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[2]/div[5]/div[2]/div/div[3]/ul/li[1]/a')
    checklist_annual_3_addbutton =  (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[3]/div[5]/div[2]/div/div[3]/ul/li[1]/a')
    checklist_annual_4_addbutton =  (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[4]/div[5]/div[2]/div/div[3]/ul/li[1]/a')
    checklist_annual_5_addbutton =  (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[5]/div[5]/div[2]/div/div[3]/ul/li[1]/a')
    checklist_annual_6_addbutton =  (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[6]/div[5]/div[2]/div/div[3]/ul/li[1]/a')
    checklist_annual_7_addbutton =  (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[7]/div[5]/div[2]/div/div[3]/ul/li[1]/a')
    checklist_annual_8_addbutton =  (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[8]/div[5]/div[2]/div/div[3]/ul/li[1]/a')
    checklist_annual_9_addbutton =  (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[9]/div[5]/div[2]/div/div[3]/ul/li[1]/a')
    checklist_annual_10_addbutton =  (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[10]/div[5]/div[2]/div/div[3]/ul/li[1]/a')
    checklist_annual_11_addbutton =  (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[1]/div[5]/div[2]/div/div[3]/ul/li[1]/a')
    checklist_annual_12_addbutton =  (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[2]/div[5]/div[2]/div/div[3]/ul/li[1]/a')
    checklist_annual_13_addbutton =  (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[3]/div[5]/div[2]/div/div[3]/ul/li[1]/a')
    checklist_annual_14_addbutton =  (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[4]/div[5]/div[2]/div/div[3]/ul/li[1]/a')
    checklist_annual_15_addbutton =  (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[5]/div[5]/div[2]/div/div[3]/ul/li[1]/a')
    checklist_annual_16_addbutton =  (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[6]/div[5]/div[2]/div/div[3]/ul/li[1]/a')
    checklist_annual_17_addbutton =  (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[7]/div[5]/div[2]/div/div[3]/ul/li[1]/a')
    checklist_annual_18_addbutton =  (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[8]/div[5]/div[2]/div/div[3]/ul/li[1]/a')
    checklist_annual_19_addbutton =  (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[9]/div[5]/div[2]/div/div[3]/ul/li[1]/a')
    checklist_annual_20_addbutton =  (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[10]/div[5]/div[2]/div/div[3]/ul/li[1]/a')

    checklist_annual_21_addbutton =  (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[1]/div[5]/div[2]/div/div[3]/ul/li[1]/a')
    checklist_annual_22_addbutton =  (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[2]/div[5]/div[2]/div/div[3]/ul/li[1]/a')
    checklist_annual_23_addbutton =  (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[3]/div[5]/div[2]/div/div[3]/ul/li[1]/a')
    checklist_annual_24_addbutton =  (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[4]/div[5]/div[2]/div/div[3]/ul/li[1]/a')
    checklist_annual_25_addbutton =  (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[5]/div[5]/div[2]/div/div[3]/ul/li[1]/a')
    checklist_annual_26_addbutton =  (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[6]/div[5]/div[2]/div/div[3]/ul/li[1]/a')

    checklist_annual_bodytext = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[7]/table/tbody/tr[2]/td')
    checklist_annual_Next = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/ul/li[2]/a')

    checklist_annual_1_spares_yes = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[1]/div[4]/ul/li[2]/label/span')
    checklist_annual_2_spares_yes = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[2]/div[4]/ul/li[2]/label/span')
    checklist_annual_3_spares_yes = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[3]/div[4]/ul/li[2]/label/span')
    checklist_annual_4_spares_yes = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[4]/div[4]/ul/li[2]/label/span')
    checklist_annual_5_spares_yes = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[5]/div[4]/ul/li[2]/label/span')
    checklist_annual_6_spares_yes = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[6]/div[4]/ul/li[2]/label/span')
    checklist_annual_7_spares_yes = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[7]/div[4]/ul/li[2]/label/span')
    checklist_annual_8_spares_yes = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[8]/div[4]/ul/li[2]/label/span')
    checklist_annual_9_spares_yes = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[9]/div[4]/ul/li[2]/label/span')
    checklist_annual_10_spares_yes = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[10]/div[4]/ul/li[2]/label/span')
    checklist_annual_11_spares_yes = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[1]/div[4]/ul/li[2]/label/span')
    checklist_annual_12_spares_yes = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[2]/div[4]/ul/li[2]/label/span')
    checklist_annual_13_spares_yes = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[3]/div[4]/ul/li[2]/label/span')
    checklist_annual_14_spares_yes = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[4]/div[4]/ul/li[2]/label/span')
    checklist_annual_15_spares_yes = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[5]/div[4]/ul/li[2]/label/span')
    checklist_annual_16_spares_yes = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[6]/div[4]/ul/li[2]/label/span')
    checklist_annual_17_spares_yes = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[7]/div[4]/ul/li[2]/label/span')
    checklist_annual_18_spares_yes = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[8]/div[4]/ul/li[2]/label/span')
    checklist_annual_19_spares_yes = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[9]/div[4]/ul/li[2]/label/span')
    checklist_annual_20_spares_yes = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[10]/div[4]/ul/li[2]/label/span')
    checklist_annual_21_spares_yes = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[1]/div[4]/ul/li[2]/label/span')
    checklist_annual_22_spares_yes = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[2]/div[4]/ul/li[2]/label/span')
    checklist_annual_23_spares_yes = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[3]/div[4]/ul/li[2]/label/span')
    checklist_annual_24_spares_yes = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[4]/div[4]/ul/li[2]/label/span')
    checklist_annual_25_spares_yes = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[5]/div[4]/ul/li[2]/label/span')
    checklist_annual_26_spares_yes = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[3]/div/div[2]/form/div/div/div[2]/div[6]/div[4]/ul/li[2]/label/span')

    M16_SITESAFE_COMMENT = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[1]/div/div[2]/form/div/div/div[1]/div[1]/div[3]/ul/li[1]/a')
    DATA_SITESAFE_COMMENT = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[1]/div/div[2]/form/div/div/div[1]/div[1]/div[3]/ul/li[1]/div[2]/div/div[2]/div[2]/textarea')
    ADD_SITESAFE_COMMENT = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[1]/div/div[2]/form/div/div/div/div[1]/div[3]/ul/li[1]/div[2]/div/div[3]/ul/li[1]/a')

    EHS_CANCEL_BUTTON = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[1]/div/div[2]/form/div/div/div[1]/div[1]/div[3]/ul/li[1]/div[2]/div/div[3]/ul/li[2]/a')

    checklist_quarter_1_comment = (By.XPATH, '//*[@id="content"]/div/div[2]/check-list[1]/ng-include[2]/div/div[2]/form/div/div/div[2]/div[1]/div[7]/a')
    checklist_cancel_comment = (By.XPATH,'//*[@id="content"]/div/div[2]/check-list[1]/ng-include[2]/div/div[2]/form/div/div/div[2]/div[1]/div[7]/div[2]/div/div[3]/ul/li[2]/a')