from selenium.webdriver.common.by import By
#Updated by Uday 8-Aug-2018

class ConnectPageLocators(object):
    connection_ccn = (By.XPATH, "//*[@id='content']/div[1]/div[1]/div[2]/div[1]/div[1]")
    connection_bacnet = (By.XPATH, '//*[@id="content"]/div[1]/div[1]/div[2]/div[1]/div[2]')
    connect_ccn_title=(By.XPATH,'//*[@id="content"]/div/div[10]/div[2]/div[2]/h3')

    connect_bacnet_title = (By.XPATH, '//*[@id="content"]/div[1]/div[3]/div[1]/h3[1]')
    connectivity_TITLE = (By.XPATH,'//*[@id="content"]/div/div[1]/div/div[1]/ul/li[1]/a')
    connectivity_icon_ccn = (By.XPATH, '//*[@id="side"]/div[1]/div[2]/ul[1]/li[1]/a')
    connectivity_icon_bacnet = (By.XPATH, '//*[@id="side"]/div[1]/div[2]/ul[1]/li[2]/a')
    bacnet_conn_status =  (By.XPATH, '//*[@id="top"]/div[1]/div[1]/div[1]/div[3]/ul[1]/li[7]/a/img')
    bacnet_conn_status_text = (By.XPATH,'//*[@id="top"]/div/div[1]/div/div[3]/ul/li[7]/div/div[2]/div/div')
    ccn_conn_status_btn = (By.XPATH, '//*[@id="top"]/div/div[1]/div/div[3]/ul/li[6]/a/img')
    ccn_conn_status_txt =(By.XPATH,'//*[@id="top"]/div/div[1]/div/div[3]/ul/li[6]/div/div[2]/div/div')
    ccn_connect_btn = (By.XPATH,'//*[@id="btn_ConnectCCN"]')
    ccn_connect_override_dialog = (By.XPATH,'//*[@id="disConnectCCNModal"]/div/div')
    ccn_connect_override_yes_btn = (By.XPATH,'//*[@id="btn_yes"]')
    ccn_connect_override_no_btn = (By.XPATH, '//*[@id="btn_no"]')
    license_warning_dialog = (By.XPATH, '//*[@id="licenseExpired"]/div/div')
    ccn_disconnect_btn = (By.XPATH, '//*[@id="btn_DisConnectCCN"]')
    ccn_msg_txt= (By.XPATH,'//*[@id="content"]/div/div[10]/div[2]/div[1]/span')
    add_ccnid_btn = (By.XPATH,'//*[@id="btn_addCCN"]')
    ccnid_name_lbl=(By.XPATH,'//*[@id="lbl_name"]')
    ccnid_name_input =(By.XPATH,'//*[@id="txt_name"]')
    ccnid_name_error = (By.XPATH,'//*[@id="content"]/div/div[11]/div[1]/div/div/div[6]/form/fieldset[1]/div[2]/div')
    ccnid_bus_lbl= (By.XPATH,'//*[@id="lbl_BusNum"]')
    ccnid_bus_input=(By.XPATH,'//*[@id="txt_busNum"]')
    ccnid_elem_lbl=(By.XPATH,'//*[@id="lbl_ele"]')
    ccnid_elem_usb_input =(By.XPATH,'//*[@id="txt_ele_USB"]')
    ccnid_elem_lan_input = (By.XPATH, '//*[@id="txt_ele_LAN"]')
    ccnid_refresh_lbl=(By.XPATH,'//*[@id="lbl_autoRefreshRate"]')
    ccnid_refresh_input=(By.XPATH,'//*[@id="txt_autoRefreshRate"]')
    ccnid_ip_lbl =(By.XPATH,'//*[@id="lbl_referenceNum"]')
    ccnid_ip_addr1=(By.XPATH,'//*[@id="txt_ip1"]')
    ccnid_ip_addr2 =(By.XPATH,'//*[@id="txt_ip2"]')
    ccnid_ip_addr3 =(By.XPATH,'//*[@id="txt_ip3"]')
    ccnid_ip_addr4 =(By.XPATH,'//*[@id="txt_ip4"]')
    delete_ccnid_btn = (By.XPATH,'//*[@id="btn_deleteCCN"]')
    config_ccnid_btn = (By.XPATH, '//*[@id="btn_editCCN"]')
    device_manager_btn = (By.XPATH, '//*[@id="btn_LaunchDM"]')
    trace_btn= (By.XPATH,'//*[@id="btn_LaunchDCAT"]')
    fw_loader_btn =(By.XPATH,'//*[@id="content"]/div/div[11]/div[1]/div/div/div[4]/form/div[12]/button')
    network_monit_btn = (By.XPATH, '//*[@id="btn_NetworkMonitor"]')

    ccn_conn_prmpt_dialog =(By.XPATH,'//*[@id="modalCCNCntConfirm"]/div/div')

    ccn_conn_yes_btn = (By.XPATH,'//*[@id="modalCCNCntConfirm"]/div/div/div[3]/ul/li[3]/a')
    ccn_conn_no_btn =(By.XPATH,'//*[@id="modalCCNCntConfirm"]/div/div/div[3]/ul/li[2]/a')
    ccn_conn_cancel_btn =(By.XPATH,'//*[@id="modalCCNCntConfirm"]/div/div/div[3]/ul/li[1]/a')
    ccn_tbl_header = (By.XPATH,'//*[@id="content"]/div/div[11]/div[1]/div/div/div[6]/div/div/table/thead/tr')

    ccn_tbl = (By.XPATH, '//*[@id="content"]/div/div[11]/div[1]/div/div/div[6]/div/div/table/tbody/tr')

    ccnid_search_lbl = (By.XPATH,'ccnid_search_lbl')
    ccnid_search_input = (By.XPATH,'//*[@id="content"]/div/div[11]/div[1]/div/div/div[5]/div/div/input')

    loader_txt = (By.XPATH,'//*[@id="spanLoader"]')
    ccn_disconnect_dialog = (By.XPATH,'//*[@id="disConnectCCNModal"]/div[1]/div[1]')
    ccn_disconnect_dialog_txt = (By.XPATH, '//*[@id="disConnectCCNModal"]/div[1]/div[1]/div[2]/div[1]')
    ccn_disconnect_dialog_ccn_name = (By.XPATH, '//*[@id="disConnectCCNModal"]/div[1]/div[1]/div[2]/div[1]/p[1]/span[1]')
    ccn_disconnect_dialog_yes = (By.XPATH, '//*[@id="btn_yes"]')
    ccn_disconnect_dialog_no = (By.XPATH, '//*[@id="btn_no"]')
    ccnid_name_lbl = (By.XPATH,'//*[@id="lbl_name"]')
    ccnid_name_input = (By.XPATH,'//*[@id="txt_name"]')
    ccnid_type_lbl = (By.XPATH,'//*[@id="lbl_secondaryBaudRate"]')
    ccnid_type_btn = (By.XPATH,'// *[ @ id = "btn_protocolType"]')
    ccnid_type_loe = (By.XPATH, '//*[@id="content"]/div/div[10]/div[1]/div/div/div[6]/form/fieldset[1]/div[1]/div/div[2]/div/div/div/ul/li')
    ccnid_type_usb = (By.XPATH,'//*[@id="content"]/div/div[10]/div[1]/div/div/div[6]/form/fieldset[1]/div[1]/div/div[2]/div/div/div/ul/li[1]')
    ccnid_type_lan = (By.XPATH,'//*[@id="content"]/div/div[10]/div[1]/div/div/div[6]/form/fieldset[1]/div[1]/div/div[2]/div/div/div/ul/li[2]')
    ccnid_type_db = (By.XPATH,'//*[@id="content"]/div/div[10]/div[1]/div/div/div[6]/form/fieldset[1]/div[1]/div/div[2]/div/div/div/ul/li[3]')
    ccnid_save_btn= (By.XPATH,'//*[@id="btn_save"]')
    ccnid_add_cancel_btn =(By.XPATH,'//*[@id="btn_cancelAdd"]')
    ccnid_delete_btn=(By.XPATH,'//*[@id="btn_deleteCCN"]')
    ccnid_delete_msg= (By.XPATH,'//*[@id="deleteCCNModal"]/div/div/div[2]/div[2]/p')
    ccnid_delete_yes= (By.XPATH,'//*[@id="deleteCCNModal"]/div/div/div[3]/ul/li[2]/a')
    ccnid_delete_no = (By.XPATH,'//*[@id="deleteCCNModal"]/div/div/div[3]/ul/li[1]/a')
    ccnid_delete_err= (By.XPATH,'//*[@id="deleteCCNWarningModal"]/div/div')
    ccnid_delete_err_close =(By.XPATH,'//*[@id="deleteCCNWarningModal"]/div/div/div[1]/div[2]/a')

    ccn_export_btn =(By.XPATH,'//*[@id="btn_export"]')
    ccn_export_path = (By.XPATH,'//*[@id="txt_ImportExportPath"]')
    ccn_export_path_yes_btn = (By.XPATH,'//*[@id="exportImportCCNModal"]/div/div/div[3]/ul/li[2]')
    ccn_export_path_no_btn = (By.XPATH,'//*[@id="exportImportCCNModal"]/div/div/div[3]/ul/li[1]')
    ccn_import_btn = (By.XPATH, '//*[@id="btn_Import"]')

    #Bacnet connect element locators
    bacnet_device_scan_btn =(By.XPATH,'//*[@id="btn_DeviceScan"]')
    bacnet_device_scan_lbl =(By.XPATH,'//*[@id="lbl_id"]')
    bacnet_connect_btn = (By.XPATH,'//*[@id="content"]/div[1]/div[3]/div[2]/div[2]/button[1]')
    bacnet_disconnect_btn = (By.XPATH,'//*[@id="content"]/div[1]/div[3]/div[2]/div[2]/button[2]')
    bacnet_ip_lbl = (By.XPATH,'//*[@id="lbl_ip"]')
    bacnet_ip_txt = (By.XPATH,'//*[@id="txt_ip"]')
    bacnet_id_lbl = (By.XPATH,'//*[@id="lbl_id"]')
    bacnet_id_txt = (By.XPATH,'//*[@id="txt_id"]')
    bacnet_device_tbl_header = (By.XPATH,'//*[@id="content"]/div[1]/div[3]/div[4]/div[1]/table[1]/thead')
    bacnet_device_tbl = (By.XPATH,'//*[@id="content"]/div[1]/div[3]/div[4]/div[1]/table[1]/tbody[1]/tr')

    bacnet_nodevice_dialog_title = (By.XPATH,'//*[@id="no-available-device"]/div[1]/div[1]/div[1]/div[1]')
    bacnet_nodevice_dialog_ok_btn = (By.XPATH, '//*[@id="no-available-device"]/div[1]/div[1]/div[3]/ul[1]/li[1]')
    bacnet_object_view_lbl = (By.XPATH,'//*[@id="content"]/div[1]/div[4]/div[3]/div[2]/h4[1]')

    # key ending with _LOE indicates that the return type is a list of elements
    connection_protocol_LOE = (By.XPATH, "//*[@id='dropdownMenu1']")
    bacnet_device_selection_LOE =  (By.XPATH, "//*[@id='dropdownMenu2']")
    bacnet_device_load = (By.XPATH, "//*[@id='spnSelected']")
    bacnet_device_item1 = (By.XPATH, "//*[@id='content']/div/div[2]/div[1]/div/div/div/div[2]/div[1]/div[4]/div/div[2]/div[1]/ul/li")
    bacnet_avail_device = (By.XPATH,"//*[@id='aAvilDevice']/span")
    ccn_protocol = (By.XPATH, "//*[text()='CCN']")
    bacnet_protocol = (By.XPATH, "//*[text()='Native BACnet']")
    available_devices = (By.XPATH, "//*[@id='spnSelected']")
    bus = (By.XPATH, "//*[@id='content']/div[1]/div[3]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[2]/div[2]/div["
                     "1]/div[1]/div[2]/input[1]")
    element = (By.XPATH,
               '//*[@id="content"]/div[1]/div[3]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[2]/div[2]/div[1]/div[2]/div[2]/input[1]')
    # key ending with _LOE indicates that the return type is a list of elements
    baudrate_btn = (By.XPATH,'//*[@id="btn_primaryBaudRate"]')
    baudrate_LOE = (By.XPATH,'//*[@id="content"]/div/div[10]/div[1]/div/div/div[6]/form/fieldset[2]/div/div[3]/div/div/ul')
     # <button class="btn-default dropdown-toggle ng-binding"
    #added individual bauds
    baud_9600 = (By.XPATH, '//*[@id="content"]/div/div[10]/div[1]/div/div/div[6]/form/fieldset[2]/div/div[3]/div/div/ul/li[1]/a')
    baud_19200 = (By.XPATH, '//*[@id="content"]/div/div[10]/div[1]/div/div/div[6]/form/fieldset[2]/div/div[3]/div/div/ul/li[2]/a')
    baud_38400 = (By.XPATH, '//*[@id="content"]/div/div[10]/div[1]/div/div/div[6]/form/fieldset[2]/div/div[3]/div/div/ul/li[3]/a')
    connect = (By.XPATH, '//*[@id="content"]/div[1]/div[3]/div[1]/div/div/div/div[1]/div[3]/div[1]/ul[1]/li[1]/button[1]')
    loading = (By.XPATH, "//*[@id='bodyExport']/div[2]/img")
    alarm_loading = (By.XPATH,'//*[@id ="spanLoader"]')
    overview_opt = (By.XPATH, "//*[@id='over_0'']")
    connection_text = (By.XPATH, '//*[@id="content"]/div[1]/div[2]/div[2]/div[2]/h3[1]')
    connect_message = (By.XPATH, "//*[@id='content']/div[1]/div[2]/div[2]/div[1]")
    bacnet_connect_side_btn = (By.XPATH,'//*[@id="side"]/div[1]/div[2]/ul[1]/li[2]/a/img')
